import 'package:aetherlink_flutter/shared/domain/skill.dart';

/// The built-in skill catalog, ported from the web
/// `src/shared/config/builtinSkills/*` (the per-file `Skill` definitions
/// aggregated by `builtinSkills`). Adding a new built-in skill is a matter of
/// adding an entry here.
///
/// UI-only milestone: the SKILL.md `content` bodies (consumed only by the
/// editor) aren't ported yet, and `enabled` is a display default — the real
/// enabled state will come from the persisted store once the feature is wired.
const List<Skill> kBuiltinSkills = [
  // —— 编程开发 ——
  Skill(
    id: 'builtin-code-review',
    name: '代码审查',
    description: '审查代码变更，检查潜在bug、代码风格、性能问题和安全隐患',
    emoji: '💻',
    tags: ['编程', '审查'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  Skill(
    id: 'builtin-unit-testing',
    name: '单元测试',
    description: '为代码生成全面的单元测试，覆盖正常路径、边界条件和异常场景',
    emoji: '🧪',
    tags: ['编程', '测试', '质量'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  Skill(
    id: 'builtin-debugging',
    name: 'Bug 诊断',
    description: '系统化分析和定位代码Bug，提供根因分析和修复建议',
    emoji: '🐛',
    tags: ['编程', '调试', '排错'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  Skill(
    id: 'builtin-refactoring',
    name: '代码重构',
    description: '识别代码异味并提供重构方案，提升代码可读性、可维护性和性能',
    emoji: '♻️',
    tags: ['编程', '重构', '质量'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  Skill(
    id: 'builtin-git-assistant',
    name: 'Git 助手',
    description: '生成规范的 commit message 和 PR 描述，遵循 Conventional Commits 规范',
    emoji: '🔀',
    tags: ['Git', '编程', '规范'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  Skill(
    id: 'builtin-api-design',
    name: 'API 设计',
    description: '设计 RESTful API，遵循最佳实践，包括路由设计、状态码、错误处理和版本管理',
    emoji: '🔗',
    tags: ['API', '设计', '后端'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  Skill(
    id: 'builtin-sql-optimization',
    name: 'SQL 优化',
    description: '分析SQL查询性能，提供索引建议、执行计划分析和查询重写方案',
    emoji: '🗄️',
    tags: ['数据库', 'SQL', '性能'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  // —— 写作办公 ——
  Skill(
    id: 'builtin-doc-writing',
    name: '文档写作',
    description: '按照结构化模板撰写技术文档，包括 API 文档、设计文档和用户指南',
    emoji: '📝',
    tags: ['写作', '文档'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  Skill(
    id: 'builtin-creative-writing',
    name: '创意写作',
    description: '辅助创意文案撰写，包括营销文案、故事创作、社交媒体内容等',
    emoji: '✨',
    tags: ['写作', '创意', '文案'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  Skill(
    id: 'builtin-meeting-notes',
    name: '会议纪要',
    description: '将会议内容整理为结构化纪要，包括议题、决策、待办事项和负责人',
    emoji: '📋',
    tags: ['办公', '会议', '纪要'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  // —— 数据与信息 ——
  Skill(
    id: 'builtin-data-analysis',
    name: '数据分析',
    description: '分析数据集，生成统计摘要、趋势分析和可视化建议',
    emoji: '📊',
    tags: ['数据', '分析', '统计'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  Skill(
    id: 'builtin-web-summary',
    name: '网页摘要',
    description: '提取和总结网页内容的关键信息，生成结构化摘要',
    emoji: '🌐',
    tags: ['阅读', '摘要', '网页'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  Skill(
    id: 'builtin-news-analysis',
    name: '新闻分析',
    description: '搜索、汇总和深度分析指定日期或主题的新闻事件，提供多角度解读',
    emoji: '📰',
    tags: ['新闻', '分析', '时事', '搜索'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  // —— 语言工具 ——
  Skill(
    id: 'builtin-translation',
    name: '专业翻译',
    description: '在中英日韩等语言之间进行高质量翻译，保留原文语气和专业术语',
    emoji: '🌍',
    tags: ['翻译', '语言', '国际化'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
  // —— 工具集成 ——
  Skill(
    id: 'builtin-mcp-bridge',
    name: 'MCP 工具大师',
    description: '智能发现和调用当前可用的 MCP 工具服务器，无需手动配置即可使用所有已启用的工具能力',
    emoji: '🔌',
    tags: ['MCP', '工具', '自动化'],
    source: SkillSource.builtin,
    version: '1.0.0',
    author: 'AetherLink',
    enabled: true,
  ),
];
