// 电子宠物像素图：六角恐龙：粉色 + 两侧外鳃。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt axolotlArt = BuddyPixelArt(
  rows: [
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '...........mm......................................................................................mm...........................',
    '.........mmmmmm..................................................................................mmmmmm.........................',
    '.........mmmmmmmm..............................................................................mmmmmmmm.........................',
    '........mmmmmmmmmm............................................................................mmmmmmmmmm........................',
    '........mmmmmmmmmm............................................................................mmmmmmmmmm........................',
    '........mmmmmmmmmmm..........................................................................mmmmmmmmmmm........................',
    '........mmmmmmmmmmm..........................................................................mmmmmmmmmmm........................',
    '........mmmmmmmmmmmm........................................................................mmmmmmmmmmmm........................',
    '........mmmmmmmmmmmm...................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...................mmmmmmmmmmmm........................',
    '.........mmmmmmmmmmmm................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH................mmmmmmmmmmmm.........................',
    '.........mmmmmmmmmmmm..............HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..............mmmmmmmmmmmm.........................',
    '..........mmmmmmmmmmmm...........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...........mmmmmmmmmmmm..........................',
    '..........mmmmmmmmmmmm.........HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHH.........mmmmmmmmmmmm..........................',
    '...........mmmmmmmmmmmm......HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHH......mmmmmmmmmmmm...........................',
    '.............mmmmmmmmmm....HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHH....mmmmmmmmmm.............................',
    '..............mmmmmmmmmm.HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHH.mmmmmmmmmm..............................',
    '..............mmmmmmmmmmHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHmmmmmmmmmm..............................',
    '...............mmmmmmmmmHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHmmmmmmmmm...............................',
    '...............mmmmmmmmmHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHmmmmmmmmm...............................',
    '................mmmmmmmmHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHmmmmmmmm................................',
    '................mmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmm................................',
    '...............mmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmm...............................',
    '...............mmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmm...............................',
    '.............mmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmm.............................',
    '...........mmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmm...........................',
    '.........mmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmm.........................',
    '.........mmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmm.........................',
    '........mmmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmmm........................',
    '........mmmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmmm........................',
    '.........mmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmm.........................',
    '.........mmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmm.........................',
    '...........mmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmm...........................',
    '.............mmmmmmmmmmmbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbmmmmmmmmmmm.............................',
    '...............mmmmmmmmmbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbmmmmmmmmm...............................',
    '...............mmmmmmmmmbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbmmmmmmmmm...............................',
    '................mmmmmmmmbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbmmmmmmmm................................',
    '................mmmmmmmmbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbmmmmmmmm................................',
    '...............mmmmmmmmmbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbmmmmmmmmm...............................',
    '...............mmmmmmmmmbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbmmmmmmmmm...............................',
    '.............mmmmmmmmmmmbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbmmmmmmmmmmm.............................',
    '...........mmmmmmmmmmmmmbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbmmmmmmmmmmmmm...........................',
    '.........mmmmmmmmmmmmmmbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbmmmmmmmmmmmmmm.........................',
    '.........mmmmmmmmmmmmmmbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbmmmmmmmmmmmmmm.........................',
    '........mmmmmmmmmmmmmmbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbmmmmmmmmmmmmmm........................',
    '........mmmmmmmmmmmmmmbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbmmmmmmmmmmmmmm........................',
    '.........mmmmmmmmmmmmbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbmmmmmmmmmmmm.........................',
    '.........mmmmmmmmmmbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbmmmmmmmmmmmm.........................',
    '...........mmmmmmbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbmmmmmmmmm...........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................',
    '................bbbbbbbbbbbppbbbbbbbbbbbbbbbbbbbbbbnnnnnnnnnnbbbbbbbbbbbbbbbbbbbbbbppbbbbbbbSSSS................................',
    '................bbbbbbbbbppppppbbbbbbbbbbbbbbbbbbnnnnnnnnnnnnnnbbbbbbbbbbbbbbbbbbppppppbbbbbSSSS................................',
    '................bbbbbbbbbppppppppbbbbbbbbbbbbbbbbnnnnnnnnnnnnnnbbbbbbbbbbbbbbbbppppppppbbbbbSSSS................................',
    '................bbbbbbbbppppppppppbbbbbbbbbbbbbbnnnnnnnnnnnnnnnnbbbbbbbbbbbbbbppppppppppbbbbSSSS................................',
    '................bbbbbbbbppppppppppbbbbbbbbbbbbbbnnnnnnnnnnnnnnnnbbbbbbbbbbbbbbppppppppppbbbbSSSS................................',
    '................bbbbbbbbpppppppppppbbbbbbbbbbbbbbnnnnnnnnnnnnnnbbbbbbbbbbbbbbpppppppppppbbbbSSSS................................',
    '................bbbbbbbbpppppppppppppbbbbbbbbbbbbnnnnnnnnnnnnnnbbbbbbbbbbbbpppppppppppppbbbbSSSS................................',
    '................bbbbbbbbppppppppppppppbbbbbbbbbbbbbnnnnnnnnnnbbbbbbbbbbbbbppppppppppppppbbbbSSSS................................',
    '................bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS................................',
    '................bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbSSSS................................',
    '................bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbSSSS................................',
    '................bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbSSSS................................',
    '................bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbSSSS................................',
    '................bbbbbbbbbbbppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppbbbbbbbbSSS................................',
    '................bbbbbbbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbbbbbbbSSS................................',
    '................bbbbbbbbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbbbbbbbbbbS................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbH...............................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHH.............................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHH...........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHH.........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHH.......................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHH.....................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHH.....................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHH....................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '.................SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.................',
    '.................SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.................',
    '...................SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS....................',
    '....................SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS....................',
    '.....................SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.....................',
    '.....................SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.....................',
    '.......................SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS......................',
    '........................bbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbbbbbbbbbbSSSS......................',
    '........................bbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbbbbbbbSSSS.......................',
    '........................bbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbbbbbSSSS.......................',
    '........................bbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbbSSSS........................',
    '........................SbbbbbbbbbbbbbbSSSSSSSS..................................SSSSSSSSbbbbbbbbbbbSSSS........................',
    '.........................SSbbbbbbbbbbSSSSSSSS......................................SSSSSSSSbbbbbbbbSSSS.........................',
    '.........................SSSSbbbbbbSSSSSSSS..........................................SSSSSSSSbbbbbbSSSS.........................',
    '..........................SSSSSbbSSSSSSSS..............................................SSSSSSSSbbSSSSS..........................',
    '..........................SSSSSSSSSSSSS..................................................SSSSSSSSSSSSS..........................',
    '...........................SSSSSSSSSS......................................................SSSSSSSSSS...........................',
    '.............................SSSSSS..........................................................SSSSSS.............................',
    '...............................SS..............................................................SS...............................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'b': 0xFFF6C6CF,
    'm': 0xFFE87F96,
    'n': 0xFFD96A84,
    'E': kBuddyEyeColor,
    'p': 0xFFED9DAD,
    'S': 0xFFCAA2AA,
    'H': 0xFFF8D3DA,
  },
);
