// 电子宠物像素图：六角恐龙：粉色 + 两侧外鳃。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt axolotlArt = BuddyPixelArt(
  rows: [
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '.....mm..........................................mm.............',
    '....mmmmm......................................mmmmm............',
    '....mmmmm......................................mmmmm............',
    '....mmmmmm....................................mmmmmm............',
    '....mmmmmm.........HHHHHHHHHHHHHHHHHH.........mmmmmm............',
    '.....mmmmmm......HHHHHHHHHHHHHHHHHHHHHH......mmmmmm.............',
    '.....mmmmmm....HHHHbbbbbbbbbbbbbbbbbbHHHH....mmmmmm.............',
    '.......mmmmm.HHHHbbbbbbbbbbbbbbbbbbbbbbHHHH.mmmmm...............',
    '.......mmmmmHHHbbbbbbbbbbbbbbbbbbbbbbbbbbHHHmmmmm...............',
    '........mmmmHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHmmmm................',
    '........mmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmm................',
    '.......mmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmm...............',
    '.....mmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmm.............',
    '....mmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmm............',
    '....mmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmm............',
    '.....mmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmm.............',
    '.......mmmmmbbbbbbbEEbbbbbbbbbbbbbbEEbbbbbbbmmmmm...............',
    '........mmmmbbbbbEEEEEEbbbbbbbbbbEEEEEEbbbbbmmmm................',
    '........mmmmbbbbbEEEEEEbbbbbbbbbbEEEEEEbbbbbmmmm................',
    '.......mmmmmbbbbEEEEEEEEbbbbbbbbEEEEEEEEbbbbmmmmm...............',
    '.....mmmmmmmbbbbEEEEEEEEbbbbbbbbEEEEEEEEbbbbmmmmmmm.............',
    '....mmmmmmmbbbbbbEEEEEEbbbbbbbbbbEEEEEEbbbbbbmmmmmmm............',
    '....mmmmmmmbbbbbbEEEEEEbbbbbbbbbbEEEEEEbbbbbbmmmmmmm............',
    '.....mmmmbbbbbbbbbbEEbbbbbbbbbbbbbbEEbbbbbbbbbmmmmm.............',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS................',
    '........bbbbbppbbbbbbbbbbnnnnnnbbbbbbbbbbppbbbSS................',
    '........bbbbpppppbbbbbbbnnnnnnnnbbbbbbbpppppbbSS................',
    '........bbbbpppppbbbbbbbnnnnnnnnbbbbbbbpppppbbSS................',
    '........bbbbpppppppbbbbbbnnnnnnbbbbbbpppppppbbSS................',
    '........bbbbpppppppbbbbbbbbbbbbbbbbbbpppppppbbSS................',
    '........bbbbbpppppppbbbbbbbbbbbbbbbbpppppppbbbSS................',
    '........bbbbbpppppppbbbbbbbbbbbbbbbbpppppppbbbSS................',
    '........bbbbbbbppppbbbbbbbbbbbbbbbbbbppppbbbbbbS................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbH...............',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHH.............',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHH...........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHH..........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS.........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '.........SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.........',
    '..........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.........',
    '..........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS..........',
    '..........SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS..........',
    '...........SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS...........',
    '............bbbbbbbbbbbSSSSSSSSSSSSSSSSSSbbbbbbbbbbSS...........',
    '............bbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSbbbbbbbSS............',
    '............SbbbbbbSSSS..................SSSSbbbbbSS............',
    '.............SSbbSSSS......................SSSSbbSS.............',
    '.............SSSSSS..........................SSSSSS.............',
    '...............SS..............................SS...............',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'b': 0xFFF6C6CF,
    'm': 0xFFE87F96,
    'n': 0xFFD96A84,
    'E': kBuddyEyeColor,
    'p': 0xFFED9DAD,
    'S': 0xFFCAA2AA,
    'H': 0xFFF8D3DA,
  },
);
