// 电子宠物像素图：六角恐龙：粉色 + 两侧外鳃。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt axolotlArt = BuddyPixelArt(
  rows: [
    '................................',
    '................................',
    '..mm....................mm......',
    '..mmm..................mmm......',
    '..mmm....HHHHHHHHHH....mmm......',
    '...mmm.HHbbbbbbbbbbHH.mmm.......',
    '....mmHbbbbbbbbbbbbbbHmm........',
    '....mmbbbbbbbbbbbbbbbbmm........',
    '..mmmmbbbbbbbbbbbbbbbbmmmm......',
    '..mmmmbbbbbbbbbbbbbbbbmmmm......',
    '....mmbbbEEbbbbbbEEbbbmm........',
    '....mmbbEEEEbbbbEEEEbbmm........',
    '..mmmmbbEEEEbbbbEEEEbbmmmm......',
    '..mmmbbbbEEbbbbbbEEbbbbmmm......',
    '....bbbbbbbbbbbbbbbbbbbS........',
    '....bbbbbbbbbbbbbbbbbbbS........',
    '....bbppbbbbnnnnbbbbppbS........',
    '....bbpppbbbnnnnbbbpppbS........',
    '....bbppppbbbbbbbbppppbS........',
    '....bbbpppbbbbbbbbpppbbS........',
    '....bbbbbbbbbbbbbbbbbbbb........',
    '....bbbbbbbbbbbbbbbbbbbbH.......',
    '....bbbbbbbbbbbbbbbbbbbbbHH.....',
    '....bbbbbbbbbbbbbbbbbbbbbbbS....',
    '....SbbbbbbbbbbbbbbbbbbbbbbS....',
    '.....bbbbbbbbbbbbbbbbbbbbbS.....',
    '.....SbbbbbbbbbbbbbbbbbbbbS.....',
    '......bbbbbSSSSSSSSSSbbbbS......',
    '......SbbSS..........SSbbS......',
    '.......SS..............SS.......',
    '................................',
    '................................',
  ],
  palette: {
    'b': 0xFFF6C6CF,
    'm': 0xFFE87F96,
    'n': 0xFFD96A84,
    'E': kBuddyEyeColor,
    'p': 0xFFED9DAD,
    'S': 0xFFCAA2AA,
    'H': 0xFFF8D3DA,
  },
);
