// 电子宠物像素图：果冻：半透明感绿色布丁。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt blobArt = BuddyPixelArt(
  rows: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...........HHHHHHHHHH...........',
    '.........HHbbbbbbbbbbHH.........',
    '.......HHbbbbbbbbbbbbbbHH.......',
    '.....HHbbbbbbbbbbbbbbbbbbS......',
    '.....bbbllbbbbbbbbbbbbbbbS......',
    '....HbblllbbbbbbbbbbbbbbbS......',
    '....bblllbbEEbbbbbbEEbbbbb......',
    '....bbllbbEEEEbbbbEEEEbbbbS.....',
    '....bbbbbbEEEEbbbbEEEEbbbbb.....',
    '....bbbbbbbEEbbbbbbEEbbbbbbS....',
    '....bbbbbbbbbbbbbbbbbbbbbbbS....',
    '....bbbbbbbbbbbbbbbbbbbbbbbS....',
    '....bbppbbbbbbmmmmbbbbbbppbS....',
    '....bbpppbbbbbmmmmbbbbbpppbS....',
    '....bbppppbbbbbbbbbbbbppppbS....',
    '....bbbpppbbbbbbbbbbbbpppbbS....',
    '....bbbbbbbbbbbbbbbbbbbbbbbb....',
    '...HbbbbbbbbbbbbbbbbbbbbbbbbS...',
    '...bbbbbbbbbbbbbbbbbbbbbbbbbb...',
    '..HbbbbbbbbbbbbbbbbbbbbbbbbbbS..',
    '..SbbbbbbbbbbbbbbbbbbbbbbbbbbS..',
    '...SbbbbbbbbbbbbbbbbbbbbbbbbS...',
    '....dbbbbbddbbbbddbbbbddbbbSS...',
    '.....dSSSSddSSSSddSSSSddSSS.....',
    '................................',
    '................................',
  ],
  palette: {
    'b': 0xFF6FD98B,
    'l': 0xFFA8EFBB,
    'd': 0xFF4CB86B,
    'm': 0xFF3C8F52,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF5BB272,
    'H': 0xFF8FE1A5,
  },
);
