// 电子宠物像素图：果冻：半透明感绿色布丁。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt blobArt = BuddyPixelArt(
  rows: [
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '...............................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...............................................',
    '.............................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.............................................',
    '...........................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...........................................',
    '.........................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.........................................',
    '.......................................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHH.......................................',
    '.....................................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHH.....................................',
    '...................................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHH...................................',
    '.................................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHH.................................',
    '...............................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHH...............................',
    '.............................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHH.............................',
    '...........................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHH.............................',
    '.........................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHH............................',
    '.......................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...........................',
    '.....................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.........................',
    '.....................HHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.........................',
    '....................HHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '....................bbbbbbbbbbbbbbbllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '....................bbbbbbbbbbbbbllllllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '....................bbbbbbbbbbbllllllllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '....................bbbbbbbbbbllllllllllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '...................HbbbbbbbbbbllllllllllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '.................HHbbbbbbbbbbllllllllllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS........................',
    '.................HHbbbbbbbbllllllllllllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS........................',
    '................HbbbbbbbbbllllllllllllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS........................',
    '................bbbbbbbbbbllllllllllllbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbllllllllllllbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbllllllllllbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbllllllllllbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbllllllllllbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbS.......................',
    '................bbbbbbbbbllllllllbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbSS.....................',
    '................bbbbbbbbbllllllbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbSS.....................',
    '................bbbbbbbbbbbllbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbS....................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbb....................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbb....................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbb....................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbb....................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbS...................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbSSS.................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbSSS.................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppbbbbbbbSSSS................',
    '................bbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbSSSS................',
    '................bbbbbbbbbppppppppbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbppppppppbbbbbSSSS................',
    '................bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbSSSS................',
    '................bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbSSSS................',
    '................bbbbbbbbpppppppppppbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbpppppppppppbbbbSSSS................',
    '................bbbbbbbbpppppppppppppbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbpppppppppppppbbbbSSSS................',
    '................bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS................',
    '................bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS................',
    '................bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbSSSS................',
    '................bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbSSSS................',
    '................bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbSSSS................',
    '................bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbSSSS................',
    '................bbbbbbbbbbbppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppbbbbbbbbSSS................',
    '................bbbbbbbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbbbbbbbSSS................',
    '................bbbbbbbbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbbbbbbbbbbS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '...............HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...............',
    '.............HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............',
    '.............HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............',
    '............HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS............',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '...........HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...........',
    '.........HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.........',
    '.........HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.........',
    '........HHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........',
    '........SSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........',
    '.........SSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.........',
    '.........SSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.........',
    '..........SSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..........',
    '..........SSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..........',
    '...........SSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...........',
    '.............SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSS...........',
    '...............SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSS............',
    '................dbbbbbbbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbbbbbbbbbSSSSSS............',
    '.................ddbbbbbbbbbbbbbbbbbbbbbbddddddbbbbbbbbbbbbbbbbbbddddddbbbbbbbbbbbbbbbbbbddddddbbbbbbbbbbbbbbSSSSSS.............',
    '.................ddddbbbbbbbbbbbbbbbbbbbbddddddbbbbbbbbbbbbbbbbbbddddddbbbbbbbbbbbbbbbbbbddddddbbbbbbbbbbbbSSSSSSSS.............',
    '..................dddddbbbbbbbbbbbbbbbbbddddddddbbbbbbbbbbbbbbbbddddddddbbbbbbbbbbbbbbbbddddddddbbbbbbbbbSSSSSSSS...............',
    '..................ddddddSSSSSSSSSSSSSSSSddddddddSSSSSSSSSSSSSSSSddddddddSSSSSSSSSSSSSSSSddddddddSSSSSSSSSSSSSSS.................',
    '...................dddddSSSSSSSSSSSSSSSSddddddddSSSSSSSSSSSSSSSSddddddddSSSSSSSSSSSSSSSSddddddddSSSSSSSSSSSSS...................',
    '.....................dddSSSSSSSSSSSSSSSSddddddddSSSSSSSSSSSSSSSSddddddddSSSSSSSSSSSSSSSSddddddddSSSSSSSSSSS.....................',
    '.......................dSSSSSSSSSSSSSSSSddddddddSSSSSSSSSSSSSSSSddddddddSSSSSSSSSSSSSSSSddddddddSSSSSSSSS.......................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'b': 0xFF6FD98B,
    'l': 0xFFA8EFBB,
    'd': 0xFF4CB86B,
    'm': 0xFF3C8F52,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF5BB272,
    'H': 0xFF8FE1A5,
  },
);
