// 电子宠物像素图：果冻：半透明感绿色布丁。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt blobArt = BuddyPixelArt(
  rows: [
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '.......................HHHHHHHHHHHHHHHHHH.......................',
    '.....................HHHHHHHHHHHHHHHHHHHHHH.....................',
    '...................HHHHbbbbbbbbbbbbbbbbbbHHHH...................',
    '.................HHHHbbbbbbbbbbbbbbbbbbbbbbHHHH.................',
    '...............HHHHbbbbbbbbbbbbbbbbbbbbbbbbbbHHHH...............',
    '.............HHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHH..............',
    '...........HHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS.............',
    '..........HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS............',
    '..........bbbbbbbllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS............',
    '..........bbbbblllllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS............',
    '.........HbbbbblllllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS............',
    '........HbbbbllllllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS............',
    '........bbbbbllllllbbbbEEbbbbbbbbbbbbbbEEbbbbbbbbbbb............',
    '........bbbblllllbbbbEEEEEEbbbbbbbbbbEEEEEEbbbbbbbbb............',
    '........bbbblllllbbbbEEEEEEbbbbbbbbbbEEEEEEbbbbbbbbbS...........',
    '........bbbbbllbbbbbEEEEEEEEbbbbbbbbEEEEEEEEbbbbbbbbbS..........',
    '........bbbbbbbbbbbbEEEEEEEEbbbbbbbbEEEEEEEEbbbbbbbbbb..........',
    '........bbbbbbbbbbbbbEEEEEEbbbbbbbbbbEEEEEEbbbbbbbbbbb..........',
    '........bbbbbbbbbbbbbEEEEEEbbbbbbbbbbEEEEEEbbbbbbbbbbbS.........',
    '........bbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbEEbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbppbbbbbbbbbbbbbbmmmmmmbbbbbbbbbbbbbbppbbbSS........',
    '........bbbbpppppbbbbbbbbbbbmmmmmmmmbbbbbbbbbbbpppppbbSS........',
    '........bbbbpppppbbbbbbbbbbbmmmmmmmmbbbbbbbbbbbpppppbbSS........',
    '........bbbbpppppppbbbbbbbbbbmmmmmmbbbbbbbbbbpppppppbbSS........',
    '........bbbbpppppppbbbbbbbbbbbbbbbbbbbbbbbbbbpppppppbbSS........',
    '........bbbbbpppppppbbbbbbbbbbbbbbbbbbbbbbbbpppppppbbbSS........',
    '........bbbbbpppppppbbbbbbbbbbbbbbbbbbbbbbbbpppppppbbbSS........',
    '........bbbbbbbppppbbbbbbbbbbbbbbbbbbbbbbbbbbppppbbbbbbS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........',
    '.......HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS.......',
    '......HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS......',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb......',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb......',
    '.....HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS.....',
    '....HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS....',
    '....SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS....',
    '.....SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.....',
    '.....SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.....',
    '.......SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS......',
    '........dbbbbbbbbbbbbddbbbbbbbbbbddbbbbbbbbbbddbbbbbbbbSSS......',
    '.........ddbbbbbbbbbddddbbbbbbbbddddbbbbbbbbddddbbbbbSSSS.......',
    '.........dddSSSSSSSSddddSSSSSSSSddddSSSSSSSSddddSSSSSSS.........',
    '...........dSSSSSSSSddddSSSSSSSSddddSSSSSSSSddddSSSSS...........',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'b': 0xFF6FD98B,
    'l': 0xFFA8EFBB,
    'd': 0xFF4CB86B,
    'm': 0xFF3C8F52,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF5BB272,
    'H': 0xFF8FE1A5,
  },
);
