// 蓝咕咕：以 Codex Pets 官方 Blue Guga 精灵图（待机第 1 帧）为参考
// 量化的 128×128 高清像素版——冰蓝企鹅连体衣、棕发圆脸、大眼睛、黄色小脚。

import 'pixel_art.dart';

const BuddyPixelArt blueGugaArt = BuddyPixelArt(
  rows: [
    '........................................................ttttttttttttttt.........................................................',
    '....................................................tttsnnnnnnnnnnnnnnnsttt.....................................................',
    '...................................................srrrnkkkkkkkjjjkkkkknrrr.....................................................',
    '................................................sstrjkjkkkkkkkkkkkkkkkkkkjkrtss.................................................',
    '.............................................ttrkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklttt..............................................',
    '...........................................ttnnnkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkknnntt............................................',
    '..........................................rrrkjkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkjlrnr...........................................',
    '.........................................snjkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkjns..........................................',
    '........................................tnkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkknt.........................................',
    '.......................................tnkkkkkjgggjkkkkkkkkkkkkkkkkkkkkkkkkkjgggjkkkkknt........................................',
    '......................................snkkkkkjgaaagjkkkkkkkkkkkkkkkkkkkkkkkjcaaagjkkkkknr.......................................',
    '.....................................snjkkkkjaflhhfcjkkkkkkkkkkkkkkkkkkkkkjcfhhhdcjkkkkjns......................................',
    '....................................tnjkkkkjabmtttmackkkkkkkkkkkkkkkkkkkkjbamtstlabjkkkkjnt.....................................',
    '...................................tnkkkkkkjaoohstmadkkkkkjknnnnnnnkjkkkkjdamrhrsmakkkkkkknt....................................',
    '...................................tnjkkkkjgaosmstmadkkkknnmmmmmmmmmnnkkkjaamtmstoagjkkkkkkns...................................',
    '..................................tnlkkkkkgaaotttrlagkkknmomiiiiiiimmmnkkjgalrtttoaagkkkkkkknr..................................',
    '.................................srkkkkkkkgaamssshagkkkloiiiiiiiiiiiiiolkkkgahsssmaajkkkkkkkjnt.................................',
    '................................tojkkkkkkkgabdhffagkkjnmiiffiiiiiiiiiiimnjkkgagfhdaajkkkkkkkjrt.................................',
    '...............................tnlkkkkkkkkjgaaaaagjkjnmiifiiiiiiiiiiiiiimnjkjgaaaaajjkkkkkkkkknt................................',
    '...............................tnjkkkkkkkkkkgggggjkknoiiifiiiiiiiiiiiiiiimnkkjgggggkkkkkkkkkkjnt................................',
    '...............................snkkkkkkkkkkkkkkkkkknsmiiiiiiiiiiiiiiiiiiimsnkkkkkkkkkkkkkkkkkkns................................',
    '..............................tnkkkkkkkkkkkkkkkkkknttmiiiiiiiiiiiiiiiiiiimttnkkkkkkkkkkkkkkkkkklt...............................',
    '..............................tnkkkkkkkkkkkkkkkkkrtsrsqiiiiiiiiiiiiiiiiimssssrkkkkkkkkkkkkkkkkklt...............................',
    '..............................rlkkkkkkkkkkkkkklnnssqqsqqqiiiiiiiiiiiiiqqqsqrssnnkkkkkkkkkkkkkkkko...............................',
    '.............................skkkkkkkkkkkkkkkknttsqoqortsmmmiiiiiiiimmstsoooqsstnkkkkkkkkkkkkkkkjr..............................',
    '.............................skkkkkkkkkkkkkkkrtqoqoooqooqttqiiiiiiiqttqooqqorrortrjkkkkkkkkkkkkkkr..............................',
    '.............................tkkkkkjkkkkkkkkrsrqqoqrooooqqrrssssssssrqqoooqorsoqqrrkkkkkkkkkkkkkks..............................',
    '............................rnkkkkknnlkkkjkrsqooqqrrooooqoorsssssssrqooooooorrrqorsnkkkkkkkkkkkkknr.............................',
    '...........................trjkkkknstrkkkkntrqoqorrooooooooooooooooooooooooooqsqoortnkkkkkkkkkkkkjrt............................',
    '...........................trkkkknsnnrrkkrtroqoqosrooooooooooooooooooooooooooqrooqqqtrkkkkkkkkkkkkrt............................',
    '...........................trkkkjntnnnrrsnrtoooorsqomooooooooooooooooooooooooqsqoooqrsrjkkkkkkkkkjrt............................',
    '...........................rnkkkklrrnnntrnntqooqssqmmoooqooooooooooooooooooooqrrqoooqqrrkkkkkkkkkknr............................',
    '..........................tnjkkkkkkrnnnrnnrsqoqqqromoooorooooooooooooorqooooooosqoooqoqtnlkkkkkkkkjnt...........................',
    '..........................tnkkkkkkkksrnnrtsqqorsioqmoooqsqoooooooooooqsqooooooosqoqooqqqtnkkkkkkkkknt...........................',
    '..........................tnjkkkkjntrrrnnssoqqrmioroqooqsqoooooooooooqsqooooooosroqoooqqrsrkkkkkkkjnt...........................',
    '..........................tnjkkjnrrnnssnnnrsosoiiorooooqsqoooooooooooqsqooooooqssqooooooqrsrkkkkkkjnt...........................',
    '..........................tnjkknrsnnrrsrnnnsrqmfioroooqrsqoooooooooooqsqooooooqtooroooqqoqssnlkkkkjnt...........................',
    '..........................tnkkkrrnntsnntnnnrtmffioroqqrssqooooqqoooooqsqoqqqqqotimsoooqsqoqrtnkkkkknt...........................',
    '.........................tnkkkkknttrnrtrtnnnsiffiossssrqsqoooosroooooqtqqssssrqtimsoqoqrqoqqsnkkkkkknt..........................',
    '.........................tnkkkkjntrnrrrqqrssmifhrsrqrqoqtqoooosroooooomqrqqqqqstimtoooqsqoqoqsnkkkkklt..........................',
    '.........................tnkkkjnrsrrsroqostoiffhmrrooorqmqqooosrooooqqiqsooooqsmhiorqoqtqoqqorsnkkkknt..........................',
    '.........................tnkkklssqttqoqqosriffffaosoqorqiqqooosrooooqriqsoqoorriffisqoqtroooqorslkkklt..........................',
    '.........................tnkkktroqoooqoqosriffffforooorrirrooosroooorsiqsoooorqfffitqoqtqooooqoqtnkklt..........................',
    '.........................tnjnsqqoqqooooqqsoffffffiqtsstriqssssmotsssssiqtssstqifffhiqrqtqoqooooqrsljnt..........................',
    '.........................tllrsooqqqooooosoifffffffimmmmmiimmmmiimmmmmihmEmmmmiffffffEEEtroooooooorrnlt..........................',
    '.........................snosoqoooooooootmiffffhiiiiiiiifffiiiffiiiifffiiiiiiiiihfffmEEsqoooooooqosrns..........................',
    '........................skssoqqqoqqoooootmffhfiEEEEEEEEffffffffffffffffhmEEEEEEEmfhfimErqoooqooooqorskr.........................',
    '........................trrqoooqorsqooootmffEEEEmEEEEEEEffffffffffffffdEEEEEEEmEEEEffmEqqooorqooooooqrt.........................',
    '.....................stssroqroooorsoooootmfoEEEhdmEEEEEEEhfffffffffffhEEEEEEEEfhEEEEflEooooosqoqoorrqqsstt......................',
    '.....................ttssrrrroooorsqooootmmtEElahEEEEEEEEifffffffffffhEEEEEEEEhaiEEEmmEooooosqoqoorrqrsstt......................',
    '.......................ttttroqooorsqooootttsEhagEEEEEdaEmhfffffffffffhmlabEEEEEfahEEEEEqoooosroooooqstttt.......................',
    '........................ntroooooortqooootttthaadEEEEEmmEEifffffffffffhEEmmEEEEEdaahEEEEqoooqsrooooooqtr.........................',
    '.........................sqqroooortqooootomthaafEEEEEEEEEhfffffffffffhEEEEEEEEEdaahEEEEqoooosrooooqqqs..........................',
    '........................trorroooortqooootmithaadEEEEEEEEEhfffffffffffhEEEEEEEEEdaahEimEoooootroooorroqs.........................',
    '........................sqorroooortqooootmishaadEEnEEEnEEifffffffffffhEEnEEEnEEdaahEimEooqootroooorroos.........................',
    '........................tqorsoooqstqooootmffifafEEnnnnnEEifffffffffffhEEnnnnnEEfafihhmEoooootsqooorroos.........................',
    '........................tqorsoooqstqooootmiffdaahEElllEEifffffffffffffiEElllEEhaadffimEooooqtsqoqossoos.........................',
    '........................tqossoooqstooooosqmffffffmEEEEEmfffffffffffffffmEEEEEmffffffmEEoooootsqooossoos.........................',
    '........................trossooorstqooooqtoffiiiiimEEElffffffffffffffffflEEEmiiiiiffEEEqoooqtsqoqqssoqs.........................',
    '.........................tqstqqoqstsqooootofiiiiiiiifffffffffffffffffffffffiiiiiiiifrsooooqstsqoorsrqt..........................',
    '.........................tqrtsqoqrstrooootofiiiiiiiifffffffffifffifffffffffiiiiiiiiirsoqoortsrooostrqt..........................',
    '..........................rrstqooqrtrooqosrmiiiiiiiffffffffffiiiifffffffffffiiiiiiimssoqqortrqooqtsrrt..........................',
    '..........................tsrtsroqrtroooorttmiiiiiffffffffffffiiiffffffffffffiiiiimtsrooqortrqoqstrst...........................',
    '..........................tsrstsqqrssrooorsttmiiiffffffffffffffffffffffffffffhiiimttsqooorssrqqstsqst...........................',
    '...........................ssstsrqrrtsqooqrtsssqiifffffffffffffffffffffffffdfiirssstrqqorttrrqrstsss............................',
    '............................tssssrrrsssrqoqssrnoqqomffffffffffffffffffffffimooqrnrtsqoqrstsrrrstsss.............................',
    '.............................srttssrrstsqoqrtnknsssrmiiiiiiiiiiiiiiiiiiiiimrsssnkntrqorstsrrssttss..............................',
    '..............................tttttsrsttsrqqtnknkkkntttttmmmmmmmmmmmmmtttttnkkknkntqqqsttsrsttttt...............................',
    '..................................tttqottsrossnkkkkkknnnnstqiiiiiiiqtsnnnnnkkkkknssorsttoottt...................................',
    '....................................tss.sttsqtrkkkkkkkkkknnnqiiiiiqonnkkkkkkkjkkrsqsttt..st.....................................',
    '.....................................tt.srrrrssnlkkkkkjkkkknromiiornkkkkkkkkkknnssrrrrs..t......................................',
    '.......................................trlgjrsrtrnkknkkkkkkknsmimtnkkkkkkknllnstssrjgjnt........................................',
    '.......................................tnjggjjmtlrsnnnnnjjkkkkrtrkkkkkknnnnstrjsnjlgggln........................................',
    '.......................................tlggggghlglllllllnnnnkknrnkknnnllllllllgljggggggls.......................................',
    '......................................tohggggggggggghggglllllnllklllllggggggggggggggggggmr......................................',
    '.....................................trggggggggggghhgdaaaachlnhdlnjgcaaaacghjgggggggggggamt.....................................',
    '.....................................rggggggggggggggabbbbbagngggjngabbbbbbbgggggggggggggggnt....................................',
    '...................................togggggggghjggggbcbbbbcagngjnlgbbbbbbbbcgggggjhgggggggclt....................................',
    '...................................tncgggggggjjgggcbbbbbbcagnggjgabcbaaaaaaabgggjjggggggggho....................................',
    '...................................rlggggggglljggdbcbbbbbbagngaaabbacggggggggcggjllgggggggggr...................................',
    '..................................shcgggggggnlcggdbbbbbbbbagngadcbbagnnnnnnnjcggclnggggggggggot.................................',
    '..................................thgggggggcnlcgcbbbcbbbbbagngaaacajldddggdcljagclncggggggggcot.................................',
    '.................................rlggggggggllgggcbbbbbbbbbagncgkjaajlgggggggllaggjllggggggggglot................................',
    '.................................rcggggggghnhcggcbbbbbbbbbagnjjlljajkgjjhhhgllagggjngggggggggalt................................',
    '................................olgggggggghnhgggcbbbcbbbbbagnnjggkajkacccccallaggghnhggggggggglr................................',
    '...............................tmaggggggclnggggbbbbbbbbbbbagngjnkcajkccddddblladggggnlcgggggggcht...............................',
    '...............................tncggggggclnggggabbbbbbbbbcagndgggbalkadddddallabggggnlggggggggglt...............................',
    '..............................tmhgggggggclngggdbbbbbbbbbbcagngaaacagljcccbcgljabdgggnlcgggggggggms..............................',
    '..............................tnggggggggglnggcacbbbbbbbbbbagngacbbcagkggggglgacbadggnlggggggggggjs..............................',
    '..............................tnkggggggcnlcggcbbbbbbbbbbbbagngacbbbbagnnnnngacbbadggcnncgggggggknrs.............................',
    '.............................tnkkkggggggnlgggcbbbbbbbbbbbbagngaaacbbbbgggggcbbbbbdggglngggggglnkkjrt............................',
    '.............................skkkkkngcggnlcggcbbbbbbbbbbbbagncgjgabbbbaaaaabcbbbadggcnnggcgklkkkkkrt............................',
    '.............................skkkkkkkllnljgggcbbbbbbbbbbbbagngjnlgcbbbbbcbbbbbbbadggglnnlkkkkkkkknrt............................',
    '.............................tnnkkkkknnnlggggcbbbbbbbbbbbbagnnjgjkgabbbbbbbbbbbbbdgggglnnnkkkkkknns.............................',
    '..............................ttrkkkkkknjggggcbbbbbbbbbbbcagnglnkgcccbbbbbbbbbbbbdggggjnkjkkkkkntt..............................',
    '..............................timtstnkknjggggcbcbbbbbbbbbbagndgjgabbbbbbbbbbbbbbbdggggjnnkkksttshr..............................',
    '..............................tihmirtrrnjggggcbbbbbbbbbbbbagngaaacbcbbbbbbbbbbbbadgggglnrrrrmmmifr..............................',
    '..............................tmhffmortnhggggcbbbbbbbbbbbbagngacbbbbbbbbbbbbbbbbbdgggghnstsohfffir..............................',
    '...............................tmfhffmtjgggggdbcbbbbbbbbbbagngabbbbbbbbbbbbbbbbbbdggggggrtofhhfit...............................',
    '................................sssssssjggggggdbbbbbbbbbbcagngaccbbbbbbbbbbbbbbbggggggggr..sssss................................',
    '......................................sjgggggggbbbbbbbbbbbagngaaabbbbbbbbbbbbbbbggggggggr.......................................',
    '......................................sjggggggdbcbcbbbbbbbagncgljabbbbbbbbbbbbbbggggggggrt......................................',
    '......................................sjgggggggcbbbbbbbbbbagnjjllgdbbbcbbbbbbbbcggggggggrts..ssss...............................',
    '......................................sjggggggggbbbbbbbbbbagnnjgjkgabbbbbbbbbbcgggggggggsnnttnkkkr..............................',
    '......................................sjggggggggbbbbbbbbbcagndjnkbcbbbbbbbbbbbcgggggggggrnkllkkkkr..............................',
    '......................................sjgggggggggcbbbbbbbbagkggggbbbbbbbbbbbbbgggggggghgrnkjkkkkks..............................',
    '......................................sjggggggggggcbbbbbbbagngaaabbbbcbbbbcbcgggggggggjgrrkkkkknns..............................',
    '......................................sljggggggggggbbbbbbcagngaccbbbbbbbbbbbggggggggggjlrnknnnnnt...............................',
    '.......................................tlgggggggggggbbbcbbagngabbbbbbbbcbbbgggggggggggltnknnnknt................................',
    '.......................................tlgggggggggggggdbbbagndacbbbbbbbadggggggggggggglsnknkkns.................................',
    '.......................................tlgjggggggggggggddbagllgabbbbbbddggggggggggggjgltnknnnr..................................',
    '.......................................tlgjhgggggggggggggcdbanjaddccbdggggggggggggghjgltnnntt...................................',
    '........................................olgjjggggggggggggggggnlgjhggggggggggggggggjjglrsttt.....................................',
    '........................................tngjhjgggggggggggggggjllghggggggggggggggghjjgnt.........................................',
    '.........................................rngjjggggggggggggggghllljhggggggggggggghjjgnr..........................................',
    '..........................................rljghjjgggggggggljgggjlghjjgggggggggjjhgjlr...........................................',
    '...........................................tljjghjjhggggghllllmnnnlllhggggghjjhjjlls............................................',
    '............................................trmljjjjjjjjjjglrtttttrlgjjjjjjjjjjlnnt.............................................',
    '............................................tqqqnknljjjjjjlnt.....tnljjjjjjknnnqqst.............................................',
    '...........................................sqmiioqqrkkkknkrt.......trknkkknnqqqiimqs............................................',
    '..........................................tsiiiiimmmooooostt.......ttsooooommmmiiiist...........................................',
    '.........................................tqmiiiiiiiimmmmmqst.......tsqmmmmmiiiiiiiiiqt..........................................',
    '.........................................tmiiiiiiiiiiiiiiiqt.......triiiiiiiiiiiiiiimt..........................................',
    '.........................................tqiiiiiiiiiiiiiimrt.......triiiiiiiiiiiiiiiqt..........................................',
    '.........................................tsqqiiiiimmiiiimrs.........srmiiiimmiiiiiqqst..........................................',
    '..........................................ttsmiiioqqiiiiqt...........tqmiiiqqoiiimstt...........................................',
    '............................................tqmmostsqmmqt.............tqomqstsqmmqt.............................................',
    '.............................................tttt...tttt...............tttt...tttt..............................................',
  ],
  palette: {
    'E': 0xFF2E2C36,
    'a': 0xFFF5F7F9,
    'b': 0xFFF0F3F7,
    'c': 0xFFEEF4F8,
    'd': 0xFFEEF0EF,
    'f': 0xFFEFE6DC,
    'g': 0xFFD5E3F0,
    'h': 0xFFDADBD2,
    'i': 0xFFE6C68A,
    'j': 0xFF8BB9E5,
    'k': 0xFF78AFE6,
    'l': 0xFF88AACA,
    'm': 0xFF8A7A6A,
    'n': 0xFF4B709B,
    'o': 0xFF5B493E,
    'q': 0xFF594336,
    'r': 0xFF393335,
    's': 0xFF211A1C,
    't': 0xFF09050E,
  },
);
