// 蓝咕咕：以 Codex Pets 官方 Blue Guga 精灵图（待机第 1 帧）为参考
// 量化的 64×64 高清像素版——冰蓝企鹅连体衣、棕发圆脸、大眼睛、黄色小脚。

import 'pixel_art.dart';

const BuddyPixelArt blueGugaArt = BuddyPixelArt(
  rows: [
    '...........................srrrrrrrs............................',
    '........................trnnikiiiiinnrt.........................',
    '......................rnkkikkkkkkkkkikknr.......................',
    '....................rnkkkkkkkkkkkkkkkkkkkns.....................',
    '...................skikfikkkkkkkkkkkkkiikiks....................',
    '..................skikfgdfkkkkiiikkkkfdgfkikr...................',
    '.................rkikfhrsaikkknnnkkkicorlfkikr..................',
    '.................nikjbotobiknmmhmmnkicotrajkikr.................',
    '................nkkkialmfiknhhhhhhhnkigmlaikkin.................',
    '...............rkkkkkibbfknhhhhhhhhhmkfbbikkkkkr................',
    '...............nikkkkkkkkrmhhhhhhhhhmrkkkkkkkkin................',
    '..............skikkkkkknrsqmmhhhhhmmqtrnikkkkkkks...............',
    '..............nikikkkintqoqsqmhhhmqsqostnikkkkkin...............',
    '..............niknkkinsoqqooqsssssqooqqqsnikkkkin...............',
    '.............skinrrknsoosqoqooooooooooqqosnkkkkkks..............',
    '.............rkinnnrnsoqsmooooooooooooqqoosnkkkkkr..............',
    '.............nikirnnrqqqomoqqoooooqqooosqoosnikkin..............',
    '.............niknrrnrqshmqosqoooooqqooosqooosnkkin..............',
    '.............ninrrrrnsmdmqqsqoooooqsoqqqmqoqqtniin..............',
    '............rkintnrsrrhhssqsqoqqoooqsssqmsosqqrkkkr.............',
    '............rikosrqotmdgqqqoooqsoqmmqosmgqqsqoqrkir.............',
    '............rkrqqqoqsgdcmssomsqqssomsqqhdmqsqooqrir.............',
    '............roqoooosmddghEmhghhhhhhhmEEhddqEqoooqor.............',
    '...........trqooqqoshgmqEEEEdddddddEEEEqmghEoqqooqrs............',
    '..........ttsqqosqosmssgoEEEhdddddhEEEogEEmEoqsoqqqtt...........',
    '...........ttqoosqostscgEEEohdddddhmEEEgaEEEoqsooqtt............',
    '............rqqosqosomaEEEEEhdddddhEEEEEamoEoqsooqq.............',
    '...........tqsqotqosmhaEoEEohdddddhoEEoEahmEoqtoqsqt............',
    '...........tqsqqtqosmdddEEEEdddddddEEEmdddmqoqtqqsot............',
    '............ssqqtsoqsdhhhEEdddddddddEEhhhgEqostqqss.............',
    '............sssostoqshhhhdddddhhhdddddhhhhsootsosss.............',
    '.............stsqtqosthhdddddddhdddddddhhtsoqtqqts..............',
    '.............tttqstqqtsomhdddddddddddhmostqqtsqttt..............',
    '..............tttsttosnnnommmhhhhhmmmonnnsottsttt...............',
    '.................tsttsskiknnrqmhmqrnnkikssttst..................',
    '...................tnmtrnkkiikomonikkknrtmnr....................',
    '...................rffllnnkkkknrnkkkknnnlfbl....................',
    '...................lfffbffffgjlikjfcffffffffn...................',
    '..................lbffffffbaafjjjaaaaffffffffr..................',
    '.................obfffjfcbbbafffbaffffbfjfffbl..................',
    '................tgbfbjlbcbbbaffaafjjjjfbljfffbl.................',
    '................nbffflffbbbbafjjfiifffjbflfffffr................',
    '...............rffffjlfcbbbbafkjfifbcfjbfljfffbl................',
    '...............nbffblgbbbbbbafffaifaafiafglbffffr...............',
    '..............tlfffflfbbbbbbaffabbijjibbbflgfffin...............',
    '..............rkjibjlbcbbbbbafffbabffbbbcbllbijkks..............',
    '..............rkkkklffbbbbbbafkjibbaabbbcffnkkkknt..............',
    '...............onnknffbbbbbbafiifbbbbbbbcffnkknnr...............',
    '...............hgmrnffbbbbbbaifabbbbbbbbbffltohgm...............',
    '...............rmmslffcbbbbbaifabbbbbbbbfffgtmlm................',
    '..................tjfffbbbbbafffcbbbbbbbfffgt...................',
    '..................tjfffbbbbbafkjiabbbbbcfffgrrrnr...............',
    '..................tjffffbbbbafiifbbbbbbffffjokkin...............',
    '...................lfffffbbbaifabbbbbbffffflrkknr...............',
    '...................offffffbbaifabbbbbffffffonknr................',
    '...................offffffffbfjcbbbffffffffonns.................',
    '....................lfffffffffljfffffffffflt....................',
    '....................rjfffffffgfjiffffffffjr.....................',
    '.....................rnlifffflorrlffffijnr......................',
    '......................mmnnkkkr...rkkknnmmt......................',
    '.....................mhhhmmmqt...tqmmmhhhm......................',
    '....................shhhhhhhmt...tmhhhhhhhs.....................',
    '....................tqmhmmhms.....smhmmhmst.....................',
    '......................qqttqs.......sqttqq.......................',
  ],
  palette: {
    'E': 0xFF2E2C36,
    'a': 0xFFF8F8F8,
    'b': 0xFFEFF4F8,
    'c': 0xFFEFF0EE,
    'd': 0xFFEEE7DE,
    'f': 0xFFD4E2EF,
    'g': 0xFFD0D3C2,
    'h': 0xFFD0BFA0,
    'i': 0xFF87BAEC,
    'j': 0xFF84B2DF,
    'k': 0xFF76AEE6,
    'l': 0xFF909FAC,
    'm': 0xFF846C56,
    'n': 0xFF4C719C,
    'o': 0xFF574B46,
    'q': 0xFF544033,
    'r': 0xFF393941,
    's': 0xFF322929,
    't': 0xFF1B141A,
  },
);
