// 电子宠物像素图：仙人掌：绿色 + 花盆 + 小花。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt cactusArt = BuddyPixelArt(
  rows: [
    '...........................ff...................................',
    '.........................ffffff.................................',
    '.......................ffffffffff...............................',
    '......................ffffffffffff..............................',
    '......................ffffffffffff..............................',
    '.....................ffffffffffffff.............................',
    '.....................ffffffffffffff.............................',
    '....................ffffffffffffffff............................',
    '...................HbbbbbbbbbbbbbbbbH...........................',
    '.................HHbbbbbbbbbbbbbbbbbbH..........................',
    '.................HHbbbbbbbbbbbbbbbbbbbS.........................',
    '................HbbbbbbbbbbbbbbbbbbbbbSS........................',
    '................bbbbbbbbbbbbbbbbbbbbbbSS........................',
    '................bbbbbbbbbbbbbbbbbbbbbbSS........................',
    '................bbbbbbbbbbbbbbbbbbbbbbSS........................',
    '................bbbbbbbbbbbbbbbbbbbbbbSS........................',
    '.......HH.......bbbbbbbEEbbbbbbbbbbEEEEE........................',
    '.....HHHHH......bbbbbEEEEEEbbbbbbEEEEEEE........................',
    '.....HHbbbS.....bbbbbEEEEEEbbbbbbEEEEEEE........................',
    '....HbbbbbSS....bbbbEEEEEEEEbbbbEEEEEEEE........................',
    '....bbbbbbSS....bbbbEEEEEEEEbbbbEEEEEEEE.......HH...............',
    '....bbbbbbbS....bbbbbEEEEEEbbbbbbEEEEEEE.....HHHHH..............',
    '....bbbbbbbb....bbbbbEEEEEEbbbbbbEEEEEEE.....HHbbbS.............',
    '....bbbbbbbb....bbbbbbbEEbbbbbbbbbbEEEEE....HbbbbbSS............',
    '....SbbbbbbbHHHHbbbbbbbbbbbbbbbbbbbbbbSS....bbbbbbSS............',
    '.....SbbbbbbbHHbbbbbbbbbbbbbbbbbbbbbbbbS....bbbbbbSS............',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....bbbbbbSS............',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....bbbbbbSS............',
    '......SSSbbbbbbbbbbbbppbbbbbbbbbbppbbbbbHHHHbbbbbbSS............',
    '.......SSSSbbbbbbbbbpppppbbbbbbbpppppbbbbHHbbbbbbSS.............',
    '.........SSSSbbbbbbbpppppbbbbbbbpppppbbbbbbbbbbSSSS.............',
    '...........SSSSbbbbbpppppppbbbbbpppppppbbbbbbSSSS...............',
    '.............SSbbbbbpppppppbbbbbpppppppbbbbSSSS.................',
    '...............SbbbbbpppppppbbbbbpppppppbSSSS...................',
    '................bbbbbpppppppbbbbbpppppppSSS.....................',
    '................bbbbbbbppppbbbbbbbbpppppSS......................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbSS......................',
    '................bbbbbbbbbbbbbbbbbbbbbbbSS.......................',
    '................bbbbbbbbbbbbbbbbbbbbbbbSS.......................',
    '................bbbbbbbbbbbbbbbbbbbbbbSS........................',
    '................bbbbbbbbbbbbbbbbbbbbbbSS........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbS........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbb........................',
    '.............tttttttttttttttttttttttttttttt.....................',
    '............tttttttttttttttttttttttttttttttt....................',
    '............tttttttttttttttttttttttttttttttt....................',
    '.............tttttttttttttttttttttttttttttt.....................',
    '.............tttttttttttttttttttttttttttttt.....................',
    '...............tttttttttttttttttttttttttt.......................',
    '...............tttttttttttttttttttttttttt.......................',
    '................tttttttttttttttttttttttt........................',
    '................tttttttttttttttttttttttt........................',
    '................tttttttttttttttttttttttt........................',
    '................tttttttttttttttttttttttt........................',
    '................tttttttttttttttttttttttt........................',
    '................tttttttttttttttttttttttt........................',
    '.................tttttttttttttttttttttt.........................',
    '.................tttttttttttttttttttttt.........................',
    '...................tttttttttttttttttt...........................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'b': 0xFF74C27A,
    'f': 0xFFF2A0C0,
    't': 0xFFC9764A,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF5F9F64,
    'H': 0xFF93CF97,
  },
);
