// 电子宠物像素图：仙人掌：绿色 + 花盆 + 小花。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt cactusArt = BuddyPixelArt(
  rows: [
    '.............ff.................',
    '...........ffffff...............',
    '...........ffffff...............',
    '..........ffffffff..............',
    '.........HbbbbbbbbH.............',
    '........HbbbbbbbbbbS............',
    '........bbbbbbbbbbbS............',
    '........bbbbbbbbbbbS............',
    '...HH...bbbEEbbbbEEE............',
    '..HbbS..bbEEEEbbEEEE............',
    '..bbbS..bbEEEEbbEEEE...HH.......',
    '..bbbb..bbbEEbbbbEEE..HbbS......',
    '..SbbbHHbbbbbbbbbbbS..bbbS......',
    '...bbbbbbbbbbbbbbbbb..bbbS......',
    '...SSbbbbbppbbbbppbbHHbbbS......',
    '.....SSbbbpppbbbpppbbbbSS.......',
    '.......SbbppppbbppppbSS.........',
    '........bbbpppbbbpppS...........',
    '........bbbbbbbbbbbbS...........',
    '........bbbbbbbbbbbS............',
    '........bbbbbbbbbbbS............',
    '........bbbbbbbbbbbb............',
    '......tttttttttttttttt..........',
    '......tttttttttttttttt..........',
    '.......tttttttttttttt...........',
    '........tttttttttttt............',
    '........tttttttttttt............',
    '........tttttttttttt............',
    '........tttttttttttt............',
    '.........tttttttttt.............',
    '................................',
    '................................',
  ],
  palette: {
    'b': 0xFF74C27A,
    'f': 0xFFF2A0C0,
    't': 0xFFC9764A,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF5F9F64,
    'H': 0xFF93CF97,
  },
);
