// 电子宠物像素图：仙人掌：绿色 + 花盆 + 小花。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt cactusArt = BuddyPixelArt(
  rows: [
    '......................................................ffff......................................................................',
    '.....................................................ffffff.....................................................................',
    '...................................................ffffffffff...................................................................',
    '.................................................ffffffffffffff.................................................................',
    '...............................................ffffffffffffffffff...............................................................',
    '.............................................ffffffffffffffffffffff.............................................................',
    '.............................................ffffffffffffffffffffff.............................................................',
    '............................................ffffffffffffffffffffffff............................................................',
    '............................................ffffffffffffffffffffffff............................................................',
    '...........................................ffffffffffffffffffffffffff...........................................................',
    '...........................................ffffffffffffffffffffffffff...........................................................',
    '..........................................ffffffffffffffffffffffffffff..........................................................',
    '..........................................ffffffffffffffffffffffffffff..........................................................',
    '.........................................ffffffffffffffffffffffffffffff.........................................................',
    '.........................................ffffffffffffffffffffffffffffff.........................................................',
    '........................................ffffffffffffffffffffffffffffffff........................................................',
    '.......................................HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbH.......................................................',
    '.....................................HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHH.....................................................',
    '...................................HHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHH.....................................................',
    '..................................HHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbH....................................................',
    '..................................HHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...................................................',
    '.................................HHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.................................................',
    '.................................HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.................................................',
    '................................HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................................',
    '...............HH...............bbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEE................................................',
    '.............HHHHHH.............bbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEE................................................',
    '...........HHHHHHHH.............bbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbEEEEEEEEEEEEE................................................',
    '..........HHHHHHHHHH............bbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbEEEEEEEEEEEEEE................................................',
    '..........HHHHHbbbbbS...........bbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbEEEEEEEEEEEEEE................................................',
    '.........HHHHbbbbbbbSSS.........bbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbEEEEEEEEEEEEEEE................................................',
    '.........HHbbbbbbbbbSSS.........bbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbEEEEEEEEEEEEEEE................................................',
    '........HbbbbbbbbbbbSSSS........bbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbEEEEEEEEEEEEEEEE................................................',
    '........bbbbbbbbbbbbSSSS........bbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbEEEEEEEEEEEEEEEE...............HH...............................',
    '........bbbbbbbbbbbbbSSS........bbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbEEEEEEEEEEEEEEE.............HHHHHH.............................',
    '........bbbbbbbbbbbbbSSS........bbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbEEEEEEEEEEEEEEE...........HHHHHHHH.............................',
    '........bbbbbbbbbbbbbbbS........bbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbEEEEEEEEEEEEEE..........HHHHHHHHHH............................',
    '........bbbbbbbbbbbbbbbb........bbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbEEEEEEEEEEEEEE..........HHHHHbbbbbS...........................',
    '........bbbbbbbbbbbbbbbb........bbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbEEEEEEEEEEEEE.........HHHHbbbbbbbSSS.........................',
    '........bbbbbbbbbbbbbbbb........bbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEE.........HHbbbbbbbbbSSS.........................',
    '........bbbbbbbbbbbbbbbb........bbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEE........HbbbbbbbbbbbSSSS........................',
    '........SbbbbbbbbbbbbbbbHHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........................',
    '.........SSbbbbbbbbbbbbbbHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS........bbbbbbbbbbbbSSSS........................',
    '.........SSbbbbbbbbbbbbbbHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS........bbbbbbbbbbbbSSSS........................',
    '...........SbbbbbbbbbbbbbbbHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS........bbbbbbbbbbbbSSSS........................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........bbbbbbbbbbbbSSSS........................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........bbbbbbbbbbbbSSSS........................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........bbbbbbbbbbbbSSSS........................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........bbbbbbbbbbbbSSSS........................',
    '............SSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbppbbbbbbbbbbbbbbbbbbbbbbppbbbbbbbbbbbHHHHHHHHbbbbbbbbbbbbSSSS........................',
    '.............SSSSSSbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbbbbbbbbbbbbbbppppppbbbbbbbbbbHHHHHHbbbbbbbbbbbbSSSS.........................',
    '.............SSSSSSSSbbbbbbbbbbbbbbbbbbbbppppppppbbbbbbbbbbbbbbbbppppppppbbbbbbbbHHHHHHbbbbbbbbbbbbSSSS.........................',
    '...............SSSSSSSSbbbbbbbbbbbbbbbbbppppppppppbbbbbbbbbbbbbbppppppppppbbbbbbbbbHHbbbbbbbbbbbbSSSSS..........................',
    '.................SSSSSSSSbbbbbbbbbbbbbbbppppppppppbbbbbbbbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbSSSSSSS..........................',
    '...................SSSSSSSSbbbbbbbbbbbbbpppppppppppbbbbbbbbbbbbbpppppppppppbbbbbbbbbbbbbbbbbbSSSSSSSS...........................',
    '.....................SSSSSSSSbbbbbbbbbbbpppppppppppppbbbbbbbbbbbpppppppppppppbbbbbbbbbbbbbbSSSSSSSS.............................',
    '.......................SSSSSSSbbbbbbbbbbppppppppppppppbbbbbbbbbbppppppppppppppbbbbbbbbbbbSSSSSSSS...............................',
    '.........................SSSSSbbbbbbbbbbppppppppppppppbbbbbbbbbbppppppppppppppbbbbbbbbbSSSSSSSS.................................',
    '...........................SSSSbbbbbbbbbbppppppppppppppbbbbbbbbbbppppppppppppppbbbbbbSSSSSSSS...................................',
    '.............................SSbbbbbbbbbbppppppppppppppbbbbbbbbbbppppppppppppppbbbbSSSSSSSS.....................................',
    '...............................SbbbbbbbbbbppppppppppppppbbbbbbbbbbppppppppppppppbSSSSSSSS.......................................',
    '................................bbbbbbbbbbppppppppppppppbbbbbbbbbbppppppppppppppSSSSSSS.........................................',
    '................................bbbbbbbbbbbppppppppppppbbbbbbbbbbbbpppppppppppppSSSSS...........................................',
    '................................bbbbbbbbbbbbbppppppppppbbbbbbbbbbbbbbpppppppppppSSSSS...........................................',
    '................................bbbbbbbbbbbbbbbppppppbbbbbbbbbbbbbbbbbbpppppppppSSSS............................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS............................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.............................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.............................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..............................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..............................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...............................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...............................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................................',
    '................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................................',
    '...........................tttttttttttttttttttttttttttttttttttttttttttttttttttttttttt...........................................',
    '.........................tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt.........................................',
    '.........................tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt.........................................',
    '........................tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt........................................',
    '........................tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt........................................',
    '.........................tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt.........................................',
    '.........................tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt.........................................',
    '..........................tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt..........................................',
    '..........................tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt..........................................',
    '...........................tttttttttttttttttttttttttttttttttttttttttttttttttttttttttt...........................................',
    '.............................tttttttttttttttttttttttttttttttttttttttttttttttttttttt.............................................',
    '..............................tttttttttttttttttttttttttttttttttttttttttttttttttttt..............................................',
    '..............................tttttttttttttttttttttttttttttttttttttttttttttttttttt..............................................',
    '...............................tttttttttttttttttttttttttttttttttttttttttttttttttt...............................................',
    '...............................tttttttttttttttttttttttttttttttttttttttttttttttttt...............................................',
    '................................tttttttttttttttttttttttttttttttttttttttttttttttt................................................',
    '................................tttttttttttttttttttttttttttttttttttttttttttttttt................................................',
    '................................tttttttttttttttttttttttttttttttttttttttttttttttt................................................',
    '................................tttttttttttttttttttttttttttttttttttttttttttttttt................................................',
    '................................tttttttttttttttttttttttttttttttttttttttttttttttt................................................',
    '................................tttttttttttttttttttttttttttttttttttttttttttttttt................................................',
    '................................tttttttttttttttttttttttttttttttttttttttttttttttt................................................',
    '................................tttttttttttttttttttttttttttttttttttttttttttttttt................................................',
    '................................tttttttttttttttttttttttttttttttttttttttttttttttt................................................',
    '................................tttttttttttttttttttttttttttttttttttttttttttttttt................................................',
    '.................................tttttttttttttttttttttttttttttttttttttttttttttt.................................................',
    '.................................tttttttttttttttttttttttttttttttttttttttttttttt.................................................',
    '..................................tttttttttttttttttttttttttttttttttttttttttttt..................................................',
    '..................................tttttttttttttttttttttttttttttttttttttttttttt..................................................',
    '...................................tttttttttttttttttttttttttttttttttttttttttt...................................................',
    '.....................................tttttttttttttttttttttttttttttttttttttt.....................................................',
    '.......................................tttttttttttttttttttttttttttttttttt.......................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'b': 0xFF74C27A,
    'f': 0xFFF2A0C0,
    't': 0xFFC9764A,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF5F9F64,
    'H': 0xFF93CF97,
  },
);
