// 电子宠物像素图：猫：灰色三角耳 + 胡须。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt catArt = BuddyPixelArt(
  rows: [
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '...........HH..............................HH...................',
    '.........HHHHHH..........................HHHHH..................',
    '.........HHbbHHHS......................HHHHbbbS.................',
    '........HbbbbbHHSS....................HHHHbbbbSS................',
    '........bbbbbdddbb....................bbdddbbbSS................',
    '........bbbbdddddb....................bdddddbbSS................',
    '........bbbbddddddHHS..............HHHddddddbbSS................',
    '........bbbbdddddddHSS............HHHdddddddbbSS................',
    '........bbbbddddddddbb............bbddddddddbbSS................',
    '........bbbbbdddddddbb............bbdddddddbbbSS................',
    '........bbbbbdddddddbbHHH......HHHbbdddddddbbbSS................',
    '........bbbbbbbddddbbbbHHHH..HHHHbbbbddddbbbbbbS................',
    '........bbbbbbbbbbbbbbbbbHHHHHHbbbbbbbbbbbbbbbbb................',
    '........bbbbbbbbbbbbbbbbbbbHHbbbbbbbbbbbbbbbbbbb................',
    '.......HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...............',
    '......HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS..............',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..............',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..............',
    '.....HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS.............',
    '....HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS............',
    '....bbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbSS............',
    '....bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbS............',
    '....bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbb............',
    '....bbbbbbbbEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEbbbbbbbb............',
    '.wwwbbbbbbbbEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEbbbbbbbbwww.........',
    'wwwwbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbwwww........',
    'wwwwbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbwwww........',
    '.wwwbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbwww.........',
    '....bbbbbppbbbbbbbbbbbbbbbbmmbbbbbbbbbbbbbbbbppbbbbS............',
    '....bbbbpppppbbbbbbbbbbbbmmmmmmbbbbbbbbbbbbpppppbbSS............',
    '....bbbbpppppbbbbbbbbbbbbmmmmmmbbbbbbbbbbbbpppppbbSS............',
    '....bbbbpppppppbbbbbbbbbmmmmmmmmbbbbbbbbbpppppppbbSS............',
    '....bbbbpppppppbbbbbbbbbmmmmmmmmbbbbbbbbbpppppppbbSS............',
    '....bbbbbpppppppbbbbbbbbbmmmmmmbbbbbbbbbpppppppbbbSS............',
    '....bbbbbpppppppbbbbbbbbbmmmmmmbbbbbbbbbpppppppbbbSS............',
    '....bbbbbbbppppbbbbbbbbbbbbmmbbbbbbbbbbbbppppbbbbbSS............',
    '....SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS............',
    '.....SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS..............',
    '......SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS..............',
    '.......SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...............',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd...............',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdd.............',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddd...........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddd.........',
    '........Sbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddd.........',
    '.........Sbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddd........',
    '..........bbbbbbbbbbbbbSSbbbbbbbbbbbbbbSSSSSSSSbbbbbdddd........',
    '..........bbbbbbbbbbbSSSSSSbbbbbbbbbbSSSSSSSSSSSbbbdddd.........',
    '..........SSSbbbbbbSSSS..SSSSbbbbbbSSSS.........ddddddd.........',
    '...........SSSSbbSSSS......SSSSbbSSSS...........ddddd...........',
    '.............SSSSSS..........SSSSSS.............ddddd...........',
    '...............SS..............SS................dd.............',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'b': 0xFF9E9AA7,
    'd': 0xFF6F6A7A,
    'm': 0xFFE08AA0,
    'w': 0xFFDDDAE2,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF827E89,
    'H': 0xFFB3B0BA,
  },
);
