// 电子宠物像素图：猫：灰色三角耳 + 胡须。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt catArt = BuddyPixelArt(
  rows: [
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '.......................HH..............................................................HH.......................................',
    '.....................HHHHHH..........................................................HHHHHH.....................................',
    '...................HHHHHHHHHH......................................................HHHHHHHH.....................................',
    '..................HHHHHHHHHHHHH..................................................HHHHHHHHHHH....................................',
    '..................HHHHHbbHHHHHHHS..............................................HHHHHHHHbbbbbS...................................',
    '.................HHHHbbbbbbHHHHHSSS..........................................HHHHHHHHbbbbbbbSSS.................................',
    '.................HHbbbbbbbbHHHHHSSS..........................................HHHHHHHHbbbbbbbSSS.................................',
    '................HbbbbbbbbbbbHHHHSSSS........................................HHHHHHHHbbbbbbbbSSSS................................',
    '................bbbbbbbbbbbdddddbbbb........................................bbbbdddddbbbbbbbSSSS................................',
    '................bbbbbbbbbddddddddbbb........................................bbbddddddddbbbbbSSSS................................',
    '................bbbbbbbbbddddddddbbb........................................bbbddddddddbbbbbSSSS................................',
    '................bbbbbbbbdddddddddddb........................................bdddddddddddbbbbSSSS................................',
    '................bbbbbbbbddddddddddddHHHHS..............................HHHHHddddddddddddbbbbSSSS................................',
    '................bbbbbbbbdddddddddddddHHHSSS..........................HHHHHHdddddddddddddbbbbSSSS................................',
    '................bbbbbbbbdddddddddddddHHHSSS..........................HHHHHHdddddddddddddbbbbSSSS................................',
    '................bbbbbbbbdddddddddddddddHSSSS........................HHHHHdddddddddddddddbbbbSSSS................................',
    '................bbbbbbbbddddddddddddddddbbbb........................bbbbddddddddddddddddbbbbSSSS................................',
    '................bbbbbbbbbdddddddddddddddbbbb........................bbbbdddddddddddddddbbbbbSSSS................................',
    '................bbbbbbbbbdddddddddddddddbbbb........................bbbbdddddddddddddddbbbbbSSSS................................',
    '................bbbbbbbbbbddddddddddddddbbbb........................bbbbddddddddddddddbbbbbbSSSS................................',
    '................bbbbbbbbbbddddddddddddddbbbbHHHHH..............HHHHHbbbbddddddddddddddbbbbbbSSSS................................',
    '................bbbbbbbbbbbddddddddddddbbbbbbHHHHHH..........HHHHHHbbbbbbddddddddddddbbbbbbbbSSS................................',
    '................bbbbbbbbbbbbbddddddddddbbbbbbHHHHHHHH......HHHHHHHHbbbbbbddddddddddbbbbbbbbbbSSS................................',
    '................bbbbbbbbbbbbbbbddddddbbbbbbbbbbHHHHHHHH..HHHHHHHHbbbbbbbbbbddddddbbbbbbbbbbbbbbS................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '...............HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...............................',
    '.............HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............................',
    '.............HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............................',
    '............HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS............................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '...........HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...........................',
    '.........HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.........................',
    '.........HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.........................',
    '........HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbSSS........................',
    '........bbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbSSS........................',
    '........bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbS........................',
    '........bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbb........................',
    '........bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbb........................',
    '........bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbb........................',
    '........bbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbb........................',
    '...wwwwwbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbwwwww...................',
    '.wwwwwwwbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbwwwwwww.................',
    'wwwwwwwwbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbwwwwwww.................',
    'wwwwwwwwbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbwwwwwwww................',
    'wwwwwwwwbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbwwwwwwww................',
    'wwwwwwwwbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbwwwwwww.................',
    '.wwwwwwwbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbwwwwwww.................',
    '...wwwwwbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbwwwww...................',
    '........bbbbbbbbbbbppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppbbbbbbbbbbS........................',
    '........bbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbbSSS........................',
    '........bbbbbbbbbppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppbbbbbbSSS........................',
    '........bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbSSSS........................',
    '........bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbSSSS........................',
    '........bbbbbbbbpppppppppppbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbpppppppppppbbbbSSSS........................',
    '........bbbbbbbbpppppppppppppbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbpppppppppppppbbbbSSSS........................',
    '........bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS........................',
    '........bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS........................',
    '........bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbSSSS........................',
    '........bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbSSSS........................',
    '........bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbSSSS........................',
    '........bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbSSSS........................',
    '........bbbbbbbbbbbppppppppppppbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbppppppppppppbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbmmmmmmbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbmmbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbbbbbbbSSSS........................',
    '........SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '.........SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.........................',
    '.........SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.........................',
    '...........SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..........................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..........................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...........................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...........................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS............................',
    '............SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS............................',
    '.............SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.............................',
    '.............SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.............................',
    '...............SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...............................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd...............................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdd.............................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddd...........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddd.........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddd.......................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddd.....................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddd...................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddd..................',
    '................Sbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddd..................',
    '.................SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddd.................',
    '.................SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddd.................',
    '...................Sbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddd................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSbbbbbbbbbbbdddddddd................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSbbbbbbbbdddddddd.................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSbbbbbbbbdddddddd.................',
    '....................bbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSSbbbbbddddddddd..................',
    '....................SSSSSbbbbbbbbbbbbbbSSSSSSSS..SSSSSSSSbbbbbbbbbbbbbbSSSSSSSS.................dddddddddddddd..................',
    '.....................SSSSSSbbbbbbbbbbSSSSSSSS......SSSSSSSSbbbbbbbbbbSSSSSSSS...................ddddddddddddd...................',
    '.....................SSSSSSSSbbbbbbSSSSSSSS..........SSSSSSSSbbbbbbSSSSSSSS.....................ddddddddddd.....................',
    '.......................SSSSSSSSbbSSSSSSSS..............SSSSSSSSbbSSSSSSSS.......................dddddddddd......................',
    '.........................SSSSSSSSSSSSSS..................SSSSSSSSSSSSSS.........................dddddddddd......................',
    '...........................SSSSSSSSSS......................SSSSSSSSSS............................dddddddd.......................',
    '.............................SSSSSS..........................SSSSSS..............................dddddd.........................',
    '...............................SS..............................SS..................................dd...........................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'b': 0xFF9E9AA7,
    'd': 0xFF6F6A7A,
    'm': 0xFFE08AA0,
    'w': 0xFFDDDAE2,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF827E89,
    'H': 0xFFB3B0BA,
  },
);
