// 电子宠物像素图：猫：灰色三角耳 + 胡须。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt catArt = BuddyPixelArt(
  rows: [
    '................................',
    '................................',
    '.....HH..............HH.........',
    '....HbbHS..........HHbbS........',
    '....bbddb..........bddbS........',
    '....bbdddHS......HHdddbS........',
    '....bbddddb......bddddbS........',
    '....bbbdddbHH..HHbdddbbS........',
    '....bbbbbbbbbHHbbbbbbbbb........',
    '...HbbbbbbbbbbbbbbbbbbbbS.......',
    '...bbbbbbbbbbbbbbbbbbbbbb.......',
    '..HbbbbbbbbbbbbbbbbbbbbbbS......',
    '..bbbbbEEbbbbbbbbbbEEbbbbS......',
    '..bbbbEEEEbbbbbbbbEEEEbbbb......',
    'wwbbbbEEEEbbbbbbbbEEEEbbbbww....',
    'wwbbbbbEEbbbbbbbbbbEEbbbbbww....',
    '..bbppbbbbbbbmmbbbbbbbppbS......',
    '..bbpppbbbbbmmmmbbbbbpppbS......',
    '..bbppppbbbbmmmmbbbbppppbS......',
    '..bbbpppbbbbbmmbbbbbpppbbS......',
    '..SbbbbbbbbbbbbbbbbbbbbbbS......',
    '...bbbbbbbbbbbbbbbbbbbbbS.......',
    '...SbbbbbbbbbbbbbbbbbbbbS.......',
    '....bbbbbbbbbbbbbbbbbbbb........',
    '....bbbbbbbbbbbbbbbbbbbbd.......',
    '....bbbbbbbbbbbbbbbbbbbbbdd.....',
    '....Sbbbbbbbbbbbbbbbbbbbbbdd....',
    '.....bbbbbbSSbbbbbbSSSSSbbdd....',
    '.....SSbbSS..SSbbSS.....ddd.....',
    '.......SS......SS.......dd......',
    '................................',
    '................................',
  ],
  palette: {
    'b': 0xFF9E9AA7,
    'd': 0xFF6F6A7A,
    'm': 0xFFE08AA0,
    'w': 0xFFDDDAE2,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF827E89,
    'H': 0xFFB3B0BA,
  },
);
