// 电子宠物像素图：胖猫：滚圆灰橘猫 + 眯眯眼。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt chonkArt = BuddyPixelArt(
  rows: [
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '.......................HH..............................................................................HH.......................',
    '.....................HHHHHH..........................................................................HHHHHH.....................',
    '...................HHHHHHHHHH......................................................................HHHHHHHH.....................',
    '..................HHHHHHHHHHHHH..................................................................HHHHHHHHHHH....................',
    '..................HHHHHbbHHHHHHHS..............................................................HHHHHHHHbbbbbS...................',
    '.................HHHHbbbbbbHHHHHSSS..........................................................HHHHHHHHbbbbbbbSSS.................',
    '.................HHbbbbbbbbHHHHHSSS..........................................................HHHHHHHHbbbbbbbSSS.................',
    '................HbbbbbbbbbbbHHHHSSSS........................................................HHHHHHHHbbbbbbbbSSSS................',
    '................bbbbbbbbbbbdddddbbbb........................................................bbbbdddddbbbbbbbSSSS................',
    '................bbbbbbbbbdddddddbbbb........................................................bbbbdddddddbbbbbSSSS................',
    '................bbbbbbbbbdddddddbbbb........................................................bbbbdddddddbbbbbSSSS................',
    '................bbbbbbbbddddddddbbbb........................................................bbbbddddddddbbbbSSSS................',
    '................bbbbbbbbddddddddbbbbHHHHH..............................................HHHHHbbbbddddddddbbbbSSSS................',
    '................bbbbbbbbbddddddbbbbbbHHHHHH..........................................HHHHHHbbbbbbddddddbbbbbbSSS................',
    '................bbbbbbbbbddddddbbbbbbHHHHHHHH......................................HHHHHHHHbbbbbbddddddbbbbbbSSS................',
    '................bbbbbbbbbbbddbbbbbbbbbbHHHHHHHH..................................HHHHHHHHbbbbbbbbbbddbbbbbbbbbbS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '...............HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...............',
    '.............HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............',
    '.............HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............',
    '............HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS............',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '.......HHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHS.......',
    '.....HHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHSSS.....',
    '.....HHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHSSS.....',
    '....HHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHSSSS....',
    '....bbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbb....',
    '....bbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbb....',
    '....bbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbb....',
    '....bbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbb....',
    '...HbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbS...',
    '.HHbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbSSS.',
    'HHHbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbSSSS',
    'HbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppbbbbbbbSSSS',
    'bbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbSSSS',
    'bbbbbbbbbppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppbbbbbSSSS',
    'bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbSSSS',
    'bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbSSSS',
    'bbbbbbbbpppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpppppppppppbbbbSSSS',
    'bbbbbbbbpppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpppppppppppppbbbbSSSS',
    'bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS',
    'bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS',
    'bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbSSSS',
    'bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbSSSS',
    'bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbSSSS',
    'bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbSSSS',
    'bbbbbbbbbbbppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppbbbbbbbSSSS',
    'bbbbbbbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS',
    'SSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSS',
    '.SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.',
    '...SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..',
    '....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..',
    '....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...',
    '....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSS...',
    '....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSS....',
    '....SSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSS....',
    '.....SSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSS.....',
    '.....SSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSS.....',
    '.......SSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSS.......',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSS.........',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...........',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSS...........',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSS............',
    '............SSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSS............',
    '.............SSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSS.............',
    '.............SSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSS.............',
    '...............SSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSS...............',
    '....................bbbbbbbbbbbbbbbbbbbbbbbSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSbbbbbbbbbbbbbbbbbbbbbSSSSS.................',
    '....................bbbbbbbbbbbbbbbbbbbbbSSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSbbbbbbbbbbbbbbbbbbSSSS...................',
    '....................bbbbbbbbbbbbbbbbbbbSSSSSSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSbbbbbbbbbbbbbbSSSSSS...................',
    '....................bbbbbbbbbbbbbbbbbbSSSSSSSSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSbbbbbbbbbbbbSSSSSS....................',
    '....................SSSSSbbbbbbbbbbbbbSSSSS..SSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSS..SSSSSbbbbbbbbbbbbSSSSSS....................',
    '.....................SSSSSSbbbbbbbbbbSSSS......SSSSbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS......SSSSbbbbbbbbbbSSSSSS.....................',
    '.....................SSSSSSSSbbbbbbSSSS..........SSSSbbbbbbbbbbbbbbbbbbbbbbSSSS..........SSSSbbbbbbSSSSSSSS.....................',
    '.......................SSSSSSSSbbSSSSS............SSSSSbbbbbbbbbbbbbbbbbbSSSSS............SSSSSbbSSSSSSSS.......................',
    '.........................SSSSSSSSSSSSS............SSSSSSSSSSSSSSSSSSSSSSSSSSSS............SSSSSSSSSSSSS.........................',
    '...........................SSSSSSSSSS..............SSSSSSSSSSSSSSSSSSSSSSSSSS..............SSSSSSSSSS...........................',
    '.............................SSSSSS..................SSSSSSSSSSSSSSSSSSSSSS..................SSSSSS.............................',
    '...............................SS......................SSSSSSSSSSSSSSSSSS......................SS...............................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'b': 0xFFE0B27A,
    'd': 0xFFB98A52,
    'm': 0xFFC97E5A,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFB89264,
    'H': 0xFFE7C397,
  },
);
