// 电子宠物像素图：胖猫：滚圆灰橘猫 + 眯眯眼。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt chonkArt = BuddyPixelArt(
  rows: [
    '................................',
    '................................',
    '.....HH..................HH.....',
    '....HbbHS..............HHbbS....',
    '....bbddb..............bddbS....',
    '....bbddbHH..........HHbddbS....',
    '....bbbbbbbHHHHHHHHHHbbbbbbb....',
    '...HbbbbbbbbbbbbbbbbbbbbbbbbS...',
    '...bbbbbbbbbbbbbbbbbbbbbbbbbb...',
    '.HHbbbbbbbbbbbbbbbbbbbbbbbbbbHS.',
    '.bbbbbEEEEbbbbbbbbbbbbEEEEbbbbb.',
    'HbbbbbEEEEbbbbbbbbbbbbEEEEbbbbbS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS',
    'bbppbbbbbbbbbbbmmbbbbbbbbbbbppbS',
    'bbpppbbbbbbbbbmmmmbbbbbbbbbpppbS',
    'bbppppbbbbbbbbmmmmbbbbbbbbppppbS',
    'bbbpppbbbbbbbbbmmbbbbbbbbbpppbbS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS',
    'SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS',
    '.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbS.',
    '.SSbbbbbbbbbbbbbbbbbbbbbbbbbbSS.',
    '...bbbbbbbbbbbbbbbbbbbbbbbbbS...',
    '...SSbbbbbbbbbbbbbbbbbbbbbbSS...',
    '.....bbbbbSSbbbbbbbbSSbbbbS.....',
    '.....SSbbS..SbbbbbbS..SbbSS.....',
    '.......SS....SSSSSS....SS.......',
    '................................',
    '................................',
  ],
  palette: {
    'b': 0xFFE0B27A,
    'd': 0xFFB98A52,
    'm': 0xFFC97E5A,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFB89264,
    'H': 0xFFE7C397,
  },
);
