// 电子宠物像素图：胖猫：滚圆灰橘猫 + 眯眯眼。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt chonkArt = BuddyPixelArt(
  rows: [
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '...........HH......................................HH...........',
    '.........HHHHHH..................................HHHHH..........',
    '.........HHbbHHHS..............................HHHHbbbS.........',
    '........HbbbbbHHSS............................HHHHbbbbSS........',
    '........bbbbbdddbb............................bbdddbbbSS........',
    '........bbbbddddbb............................bbddddbbSS........',
    '........bbbbddddbbHHH......................HHHbbddddbbSS........',
    '........bbbbbddbbbbHHHH..................HHHHbbbbddbbbbS........',
    '........bbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbb........',
    '........bbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbb........',
    '.......HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS.......',
    '......HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS......',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb......',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb......',
    '...HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHS...',
    '..HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHSS..',
    '..bbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbb..',
    '..bbbbbbbbbbEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEbbbbbbbbbb..',
    '.HbbbbbbbbbbEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEbbbbbbbbbbS.',
    'HbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS',
    'bbbbbppbbbbbbbbbbbbbbbbbbbbbbbbmmbbbbbbbbbbbbbbbbbbbbbbbbppbbbSS',
    'bbbbpppppbbbbbbbbbbbbbbbbbbbbmmmmmmbbbbbbbbbbbbbbbbbbbbpppppbbSS',
    'bbbbpppppbbbbbbbbbbbbbbbbbbbbmmmmmmbbbbbbbbbbbbbbbbbbbbpppppbbSS',
    'bbbbpppppppbbbbbbbbbbbbbbbbbmmmmmmmmbbbbbbbbbbbbbbbbbpppppppbbSS',
    'bbbbpppppppbbbbbbbbbbbbbbbbbmmmmmmmmbbbbbbbbbbbbbbbbbpppppppbbSS',
    'bbbbbpppppppbbbbbbbbbbbbbbbbbmmmmmmbbbbbbbbbbbbbbbbbpppppppbbbSS',
    'bbbbbpppppppbbbbbbbbbbbbbbbbbmmmmmmbbbbbbbbbbbbbbbbbpppppppbbbSS',
    'bbbbbbbppppbbbbbbbbbbbbbbbbbbbbmmbbbbbbbbbbbbbbbbbbbbppppbbbbbSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS',
    'SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS',
    '.SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.',
    '..bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.',
    '..bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS..',
    '..SSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS..',
    '...SSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.....',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS......',
    '......SSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS......',
    '.......SSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.......',
    '..........bbbbbbbbbbbSSbbbbbbbbbbbbbbbbbbSSbbbbbbbbbbSS.........',
    '..........bbbbbbbbbSSSSSSbbbbbbbbbbbbbbSSSSSSbbbbbbSSS..........',
    '..........SSSbbbbbbSS..SSbbbbbbbbbbbbbbSS..SSbbbbbbSSS..........',
    '...........SSSSbbSS......SSbbbbbbbbbbSS......SSbbSSSS...........',
    '.............SSSSSS......SSSSSSSSSSSSSS......SSSSSS.............',
    '...............SS..........SSSSSSSSSS..........SS...............',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'b': 0xFFE0B27A,
    'd': 0xFFB98A52,
    'm': 0xFFC97E5A,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFB89264,
    'H': 0xFFE7C397,
  },
);
