// 电子宠物像素图：龙：绿色 + 角 + 小翅膀。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt dragonArt = BuddyPixelArt(
  rows: [
    '.............yy..........................yy.....................',
    '...........yyyyy........................yyyyy...................',
    '...........yyyyy........................yyyyy...................',
    '..........yyyyyy........................yyyyyy..................',
    '..........yyyyyy........................yyyyyy..................',
    '.........yyyyyyy........................yyyyyyy.................',
    '.........yyyyyyy........................yyyyyyy.................',
    '........yyyyyyyy........................yyyyyyyy................',
    '........bbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHHbbbbbbbb................',
    '........bbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbb................',
    '.......HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...............',
    '......HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS..............',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..............',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..............',
    '.....HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS.............',
    '....HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS............',
    '....bbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbSS............',
    '....bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS............',
    '....bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS............',
    '....bbbbbbbbEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEbbbbbbSS............',
    '....bbbbbbbbEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEbbbbbbSS............',
    '....bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS............',
    '....bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS............',
    '....bbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbSS............',
    '....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS............',
    '....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS............',
    '....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS............',
    '....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS............',
    '....bbbbbppbbbbbbbbbbnnnnnnnnnnnnnnbbbbbbbbbbppbbbSS............',
    '....bbbbpppppbbbbbbbnnnnnnnnnnnnnnnnbbbbbbbpppppbbSS............',
    '....bbbbpppppbbbbbbbnnnnnnnnnnnnnnnnbbbbbbbpppppbbSS............',
    '....bbbbpppppppbbbbbbnnnnnnnnnnnnnnbbbbbbpppppppbbSS............',
    '....bbbbpppppppbbbbbbbbbbbbbbbbbbbbbbbbbbpppppppbbSS............',
    '....bbbbbpppppppbbbbbbbbbbbbbbbbbbbbbbbbpppppppbbbbS............',
    '....bbbbbpppppppbbbbbbbbbbbbbbbbbbbbbbbbpppppppbbbbb............',
    '....bbbbbbbppppbbbbbbbbbbbbbbbbbbbbbbbbbbppppbbbbbbb............',
    '...dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd...........',
    '.ddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddd.........',
    '.ddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddd.........',
    'ddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddd........',
    'ddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddd........',
    '.ddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddd.........',
    '.ddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddd.........',
    '..ddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddd..........',
    '..ddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddd..........',
    '...dddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddd...........',
    '.....dddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddd.............',
    '.......dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd...............',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '........Sbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbyyyyyyy.........',
    '.........Sbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbyyyyyyyy........',
    '..........bbbbbbbbbbbbbSSSSSSbbbbbbbbbbbbbbSSSSSyyyyyyyy........',
    '..........bbbbbbbbbbbSSSSSSSSSSbbbbbbbbbbSSSSSSSyyyyyyy.........',
    '..........SSSbbbbbbSSSS......SSSSbbbbbbSSSS.....yyyyyyy.........',
    '...........SSSSbbSSSS..........SSSSbbSSSS.......yyyyy...........',
    '.............SSSSSS..............SSSSSS.........yyyyy...........',
    '...............SS..................SS............yy.............',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'b': 0xFF6DBF6D,
    'd': 0xFF4A9B57,
    'y': 0xFFF2C14E,
    'n': 0xFF9FE0A0,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF599D59,
    'H': 0xFF8DCD8D,
  },
);
