// 电子宠物像素图：龙：绿色 + 角 + 小翅膀。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt dragonArt = BuddyPixelArt(
  rows: [
    '......yy............yy..........',
    '.....yyy............yyy.........',
    '.....yyy............yyy.........',
    '....yyyy............yyyy........',
    '....bbbbHHHHHHHHHHHHbbbb........',
    '...HbbbbbbbbbbbbbbbbbbbbS.......',
    '...bbbbbbbbbbbbbbbbbbbbbb.......',
    '..HbbbbbbbbbbbbbbbbbbbbbbS......',
    '..bbbbbEEbbbbbbbbbbEEbbbbS......',
    '..bbbbEEEEbbbbbbbbEEEEbbbS......',
    '..bbbbEEEEbbbbbbbbEEEEbbbS......',
    '..bbbbbEEbbbbbbbbbbEEbbbbS......',
    '..bbbbbbbbbbbbbbbbbbbbbbbS......',
    '..bbbbbbbbbbbbbbbbbbbbbbbS......',
    '..bbppbbbbnnnnnnnnbbbbppbS......',
    '..bbpppbbbnnnnnnnnbbbpppbS......',
    '..bbppppbbbbbbbbbbbbppppbS......',
    '..bbbpppbbbbbbbbbbbbpppbbb......',
    '.dbbbbbbbbbbbbbbbbbbbbbbbbd.....',
    'dddbbbbbbbbbbbbbbbbbbbbbbddd....',
    'dddbbbbbbbbbbbbbbbbbbbbbbddd....',
    '.dddbbbbbbbbbbbbbbbbbbbbddd.....',
    '.dddbbbbbbbbbbbbbbbbbbbbddd.....',
    '...dbbbbbbbbbbbbbbbbbbbbd.......',
    '....bbbbbbbbbbbbbbbbbbbS........',
    '....bbbbbbbbbbbbbbbbbbbb........',
    '....Sbbbbbbbbbbbbbbbbbbbyyyy....',
    '.....bbbbbbSSSSbbbbbbSSSyyyy....',
    '.....SSbbSS....SSbbSS...yyy.....',
    '.......SS........SS.....yy......',
    '................................',
    '................................',
  ],
  palette: {
    'b': 0xFF6DBF6D,
    'd': 0xFF4A9B57,
    'y': 0xFFF2C14E,
    'n': 0xFF9FE0A0,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF599D59,
    'H': 0xFF8DCD8D,
  },
);
