// 电子宠物像素图：龙：绿色 + 角 + 小翅膀。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt dragonArt = BuddyPixelArt(
  rows: [
    '..........................yyyy....................................................yyyy..........................................',
    '.........................yyyyyy..................................................yyyyyy.........................................',
    '.......................yyyyyyyy..................................................yyyyyyyy.......................................',
    '......................yyyyyyyyyy................................................yyyyyyyyyy......................................',
    '......................yyyyyyyyyy................................................yyyyyyyyyy......................................',
    '.....................yyyyyyyyyyy................................................yyyyyyyyyyy.....................................',
    '.....................yyyyyyyyyyy................................................yyyyyyyyyyy.....................................',
    '....................yyyyyyyyyyyy................................................yyyyyyyyyyyy....................................',
    '....................yyyyyyyyyyyy................................................yyyyyyyyyyyy....................................',
    '...................yyyyyyyyyyyyy................................................yyyyyyyyyyyyy...................................',
    '...................yyyyyyyyyyyyy................................................yyyyyyyyyyyyy...................................',
    '..................yyyyyyyyyyyyyy................................................yyyyyyyyyyyyyy..................................',
    '..................yyyyyyyyyyyyyy................................................yyyyyyyyyyyyyy..................................',
    '.................yyyyyyyyyyyyyyy................................................yyyyyyyyyyyyyyy.................................',
    '.................yyyyyyyyyyyyyyy................................................yyyyyyyyyyyyyyy.................................',
    '................yyyyyyyyyyyyyyyy................................................yyyyyyyyyyyyyyyy................................',
    '................bbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbbbbbb................................',
    '...............HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...............................',
    '.............HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............................',
    '.............HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............................',
    '............HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS............................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '...........HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...........................',
    '.........HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.........................',
    '.........HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.........................',
    '........HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbppbbbbbbbbbbbbbbbbbbbbbbnnnnnnnnnnnnnnnnnnnnnnnnnnbbbbbbbbbbbbbbbbbbbbbbppbbbbbbbSSSS........................',
    '........bbbbbbbbbppppppbbbbbbbbbbbbbbbbbbnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnbbbbbbbbbbbbbbbbbbppppppbbbbbSSSS........................',
    '........bbbbbbbbbppppppppbbbbbbbbbbbbbbbbnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnbbbbbbbbbbbbbbbbppppppppbbbbbSSSS........................',
    '........bbbbbbbbppppppppppbbbbbbbbbbbbbbnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnbbbbbbbbbbbbbbppppppppppbbbbSSSS........................',
    '........bbbbbbbbppppppppppbbbbbbbbbbbbbbnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnbbbbbbbbbbbbbbppppppppppbbbbSSSS........................',
    '........bbbbbbbbpppppppppppbbbbbbbbbbbbbbnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnbbbbbbbbbbbbbbpppppppppppbbbbSSSS........................',
    '........bbbbbbbbpppppppppppppbbbbbbbbbbbbnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnbbbbbbbbbbbbpppppppppppppbbbbSSSS........................',
    '........bbbbbbbbppppppppppppppbbbbbbbbbbbbbnnnnnnnnnnnnnnnnnnnnnnnnnnbbbbbbbbbbbbbppppppppppppppbbbbSSSS........................',
    '........bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS........................',
    '........bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbSSS........................',
    '........bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbSSS........................',
    '........bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbbbbS........................',
    '........bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbbbbb........................',
    '........bbbbbbbbbbbppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppbbbbbbbbbbb........................',
    '........bbbbbbbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbbbbbbbbbb........................',
    '........bbbbbbbbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbbbbbbbbbbb........................',
    '.......dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd.......................',
    '.....ddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddd.....................',
    '...ddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddd...................',
    '..ddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddd..................',
    '..ddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddd..................',
    '.ddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddd.................',
    'dddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddd.................',
    'ddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddd................',
    'ddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddd................',
    'dddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddd.................',
    '.ddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddd.................',
    '..ddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddd..................',
    '..ddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddd..................',
    '...ddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddd...................',
    '...ddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddd...................',
    '....ddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddd....................',
    '....ddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddd....................',
    '.....dddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddddd.....................',
    '.....dddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddddd.....................',
    '.......dddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddd.......................',
    '.........dddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddd.........................',
    '...........dddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddd...........................',
    '.............dddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddd.............................',
    '...............dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd...............................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................................',
    '................Sbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbyyyyyyyyyyyyy...................',
    '.................SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbyyyyyyyyyyyyyyy.................',
    '.................SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbyyyyyyyyyyyyyyy.................',
    '...................Sbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbyyyyyyyyyyyyyyyy................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSyyyyyyyyyyyyyyyy................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSyyyyyyyyyyyyyyy.................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSyyyyyyyyyyyyyyy.................',
    '....................bbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSyyyyyyyyyyyyyy..................',
    '....................SSSSSbbbbbbbbbbbbbbSSSSSSSS..........SSSSSSSSbbbbbbbbbbbbbbSSSSSSSS.........yyyyyyyyyyyyyy..................',
    '.....................SSSSSSbbbbbbbbbbSSSSSSSS..............SSSSSSSSbbbbbbbbbbSSSSSSSS...........yyyyyyyyyyyyy...................',
    '.....................SSSSSSSSbbbbbbSSSSSSSS..................SSSSSSSSbbbbbbSSSSSSSS.............yyyyyyyyyyy.....................',
    '.......................SSSSSSSSbbSSSSSSSS......................SSSSSSSSbbSSSSSSSS...............yyyyyyyyyy......................',
    '.........................SSSSSSSSSSSSSS..........................SSSSSSSSSSSSSS.................yyyyyyyyyy......................',
    '...........................SSSSSSSSSS..............................SSSSSSSSSS....................yyyyyyyy.......................',
    '.............................SSSSSS..................................SSSSSS......................yyyyyy.........................',
    '...............................SS......................................SS..........................yy...........................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'b': 0xFF6DBF6D,
    'd': 0xFF4A9B57,
    'y': 0xFFF2C14E,
    'n': 0xFF9FE0A0,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF599D59,
    'H': 0xFF8DCD8D,
  },
);
