// 电子宠物像素图：鸭子：黄色圆身 + 橙色扁嘴 + 呆毛。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt duckArt = BuddyPixelArt(
  rows: [
    '..........................................................HHSS..................................................................',
    '.........................................................HHHSSS.................................................................',
    '.......................................................HHHHHSSS.................................................................',
    '......................................................HHHHHHSSSS................................................................',
    '......................................................HHHHHbSSSS................................................................',
    '.....................................................HHHHbbbbSSS................................................................',
    '.....................................................HHbbbbbbSSS................................................................',
    '....................................................HbbbbbbbbbbS................................................................',
    '....................................................bbbbbbbbbbbb................................................................',
    '....................................................bbbbbbbbbbbb................................................................',
    '....................................................bbbbbbbbbbbb................................................................',
    '....................................................bbbbbbbbbbbb................................................................',
    '...............................................HHHHHbbbbbbbbbbbbH...............................................................',
    '.............................................HHHHHHbbbbbbbbbbbbbbHH.............................................................',
    '...........................................HHHHHHHHbbbbbbbbbbbbbbHHHH...........................................................',
    '.........................................HHHHHHHHbbbbbbbbbbbbbbbbbHHHHH.........................................................',
    '.......................................HHHHHHHHbbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHH.......................................',
    '.....................................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHH.....................................',
    '...................................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHH...................................',
    '.................................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHH.................................',
    '...............................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHS...............................',
    '.............................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHSSS.............................',
    '.............................HHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHSSS.............................',
    '............................HHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHSSSS............................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '.......................HHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHS.......................',
    '.....................HHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHSSS.....................',
    '.....................HHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHSSS.....................',
    '....................HHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHSSSS....................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....................',
    '...................HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...................',
    '.................HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.................',
    '.................HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.................',
    '................HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppbbbbbbbSSSS................',
    '................bbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbSSSS................',
    '................bbbbbbbbbppppppppbbbbbbbbbbbbbbbbbbbbbbbbbboooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbppppppppbbbbbSSSS................',
    '................bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbboooooooooooooobbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbSSSS................',
    '................bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbboooooooooooooooooobbbbbbbbbbbbbbbbbbbbbppppppppppbbbbSSSS................',
    '................bbbbbbbbpppppppppppbbbbbbbbbbbbbbbbbboooooooooooooooooooooobbbbbbbbbbbbbbbbbbpppppppppppbbbbSSSS................',
    '................bbbbbbbbpppppppppppppbbbbbbbbbbbbbboooooooooooooooooooooooooobbbbbbbbbbbbbbpppppppppppppbbbbSSSS................',
    '................bbbbbbbbppppppppppppppbbbbbbbbbbbbooooooooooooooooooooooooooooobbbbbbbbbbpppppppppppppppbbbbSSSS................',
    '................bbbbbbbbppppppppppppppbbbbbbbbbbbbooooooooooooooooooooooooooooooBBBBBBBBppppppppppppppppbbbbSSSS................',
    '................bbbbbbbbbppppppppppppppbbbbbbbbbboooooooooooooooooooooooooooooooBBBBBBBBpppppppppppppppbbbbbSSSS................',
    '................bbbbbbbbbppppppppppppppbbbbbbbbbboooooooooooooooooooooooooooooooBBBBBBBBpppppppppppppppbbbbbSSSS................',
    '................bbbbbbbbbbppppppppppppppbbbbbbbbooooooooooooooooooooooooooooooooBBBBBBBBppppppppppppppbbbbbbSSSS................',
    '................bbbbbbbbbbppppppppppppppbbbbbbbbooooooooooooooooooooooooooooooooBBBBBBBBppppppppppppppbbbbbbSSSS................',
    '................bbbbbbbbbbbppppppppppppbbbbbbbbbboooooooooooooooooooooooooooooooBBBBBBBBpppppppppppppbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbppppppppppbbbbbbbbbboooooooooooooooooooooooooooooooBBBBBBBBpppppppppppbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbppppppbbbbbbbbbbbbbooooooooooooooooooooooooooooooBBBBBBBBpppppppppbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbooooooooooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................lbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbllll................',
    '.................llbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbllll.................',
    '.................llllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbllll.................',
    '..................llllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbllll..................',
    '..................llllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbllll..................',
    '...................llllbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbllll...................',
    '.....................llbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbll.....................',
    '.......................lbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbl.......................',
    '........................SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS........................',
    '.........................SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.........................',
    '.........................SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.........................',
    '...........................SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..........................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..........................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...........................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...........................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS............................',
    '............................SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS............................',
    '.............................SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.............................',
    '.............................SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.............................',
    '...............................SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..............................',
    '................................bbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbbbbbbSSSS..............................',
    '................................bbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbbbSSSS...............................',
    '................................bbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbbbSSSS...............................',
    '................................bbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbSSSS................................',
    '................................oooooooooooooooo................................oooooooooooooooo................................',
    '.................................oooooooooooooo..................................oooooooooooooo.................................',
    '.................................oooooooooooooo..................................oooooooooooooo.................................',
    '..................................oooooooooooo....................................oooooooooooo..................................',
    '..................................oooooooooooo....................................oooooooooooo..................................',
    '...................................oooooooooo......................................oooooooooo...................................',
    '.....................................oooooo..........................................oooooo.....................................',
    '.......................................oo..............................................oo.......................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'b': 0xFFF7D154,
    'l': 0xFFFBE38A,
    'o': 0xFFF08C2E,
    'B': 0xFFD9741C,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFCBAB45,
    'H': 0xFFF9DB7A,
  },
);
