// 电子宠物像素图：鸭子：黄色圆身 + 橙色扁嘴 + 呆毛。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt duckArt = BuddyPixelArt(
  rows: [
    '.............................HS.................................',
    '...........................HHHSS................................',
    '...........................HHbSS................................',
    '..........................HbbbbS................................',
    '..........................bbbbbb................................',
    '..........................bbbbbb................................',
    '.......................HHHbbbbbbH...............................',
    '.....................HHHHbbbbbbbbHH.............................',
    '...................HHHHbbbbbbbbbbHHHHHHHHHHHH...................',
    '.................HHHHbbbbbbbbbbbbbbHHHHHHHHHHHH.................',
    '...............HHHHbbbbbbbbbbbbbbbbbbbbbbbbbbHHHS...............',
    '..............HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHSS..............',
    '..............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..............',
    '..............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..............',
    '...........HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHS...........',
    '..........HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHSS..........',
    '..........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..........',
    '..........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..........',
    '.........HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS.........',
    '........HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbSS........',
    '........bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS........',
    '........bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS........',
    '........bbbbbbbbEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEbbbbbbSS........',
    '........bbbbbbbbEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEbbbbbbSS........',
    '........bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS........',
    '........bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS........',
    '........bbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbSS........',
    '........bbbbbppbbbbbbbbbbbbbbbboobbbbbbbbbbbbbbbbppbbbSS........',
    '........bbbbpppppbbbbbbbbbbbboooooobbbbbbbbbbbbpppppbbSS........',
    '........bbbbpppppbbbbbbbbbboooooooooobbbbbbbbbbpppppbbSS........',
    '........bbbbpppppppbbbbbboooooooooooooobbbbbbpppppppbbSS........',
    '........bbbbpppppppbbbbbboooooooooooooooBBBBppppppppbbSS........',
    '........bbbbbpppppppbbbbooooooooooooooooBBBBpppppppbbbSS........',
    '........bbbbbpppppppbbbbooooooooooooooooBBBBpppppppbbbSS........',
    '........bbbbbbbppppbbbbbboooooooooooooooBBBBpppppbbbbbSS........',
    '........bbbbbbbbbbbbbbbbboooooooooooooobbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbboooooooooobbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbboooooobbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbboobbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........lbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbll........',
    '.........llbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbll.........',
    '.........llbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbll.........',
    '...........lbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbl...........',
    '............SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS............',
    '.............SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............',
    '..............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............',
    '..............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS..............',
    '..............SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS..............',
    '...............SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS...............',
    '................bbbbbbbbbSSSSSSSSSSSSSSbbbbbbbbSS...............',
    '................bbbbbbbbSSSSSSSSSSSSSSSSbbbbbbSS................',
    '................oooooooo................oooooooo................',
    '.................oooooo..................oooooo.................',
    '.................oooooo..................oooooo.................',
    '...................oo......................oo...................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'b': 0xFFF7D154,
    'l': 0xFFFBE38A,
    'o': 0xFFF08C2E,
    'B': 0xFFD9741C,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFCBAB45,
    'H': 0xFFF9DB7A,
  },
);
