// 电子宠物像素图：鸭子：黄色圆身 + 橙色扁嘴 + 呆毛。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt duckArt = BuddyPixelArt(
  rows: [
    '..............HS................',
    '.............HbS................',
    '.............bbb................',
    '...........HHbbbH...............',
    '.........HHbbbbbbHHHHHH.........',
    '.......HHbbbbbbbbbbbbbbHS.......',
    '.......bbbbbbbbbbbbbbbbbb.......',
    '.....HHbbbbbbbbbbbbbbbbbbHS.....',
    '.....bbbbbbbbbbbbbbbbbbbbbb.....',
    '....HbbbbbbbbbbbbbbbbbbbbbbS....',
    '....bbbbbEEbbbbbbbbbbEEbbbbS....',
    '....bbbbEEEEbbbbbbbbEEEEbbbS....',
    '....bbbbEEEEbbbbbbbbEEEEbbbS....',
    '....bbbbbEEbbbbbbbbbbEEbbbbS....',
    '....bbppbbbbbbboobbbbbbbppbS....',
    '....bbpppbbbboooooobbbbpppbS....',
    '....bbppppbbooooooooBBppppbS....',
    '....bbbpppbbooooooooBBpppbbS....',
    '....bbbbbbbbboooooobbbbbbbbS....',
    '....bbbbbbbbbbboobbbbbbbbbbS....',
    '....bbbbbbbbbbbbbbbbbbbbbbbS....',
    '....bbbbbbbbbbbbbbbbbbbbbbbS....',
    '....lbbbbbbbbbbbbbbbbbbbbbbl....',
    '.....lbbbbbbbbbbbbbbbbbbbbl.....',
    '......SbbbbbbbbbbbbbbbbbbS......',
    '.......bbbbbbbbbbbbbbbbbS.......',
    '.......SbbbbbbbbbbbbbbbbS.......',
    '........bbbbSSSSSSSSbbbS........',
    '........oooo........oooo........',
    '.........oo..........oo.........',
    '................................',
    '................................',
  ],
  palette: {
    'b': 0xFFF7D154,
    'l': 0xFFFBE38A,
    'o': 0xFFF08C2E,
    'B': 0xFFD9741C,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFCBAB45,
    'H': 0xFFF9DB7A,
  },
);
