// 孵化前的蛋：奶白底 + 粉色斑点。

import 'pixel_art.dart';

const BuddyPixelArt kBuddyEggArt = BuddyPixelArt(
  rows: [
    '................................',
    '................................',
    '................................',
    '................................',
    '.............wwwwww.............',
    '...........wwwwwwwwww...........',
    '...........wwwwwwwwww...........',
    '.........wwwwwwwwwwwwww.........',
    '.........wwwwwllwwwwwww.........',
    '........wwwwwlllwwwwwwww........',
    '........wwwwlllwwwmmwwww........',
    '.......wwwwwllwwwwmmwwwww.......',
    '.......wwwwwwwwwwwwwwwwww.......',
    '......wwwwwwwwwwwwwwwwwwww......',
    '......wwwwmmwwwwwwwwllwwww......',
    '......wwwwmmwwwwwwwwllwwww......',
    '......wwwwwwwwwwllwwwwwwww......',
    '......wwwwwwwwwwllwwwwwwww......',
    '......wwwwwwwwwwwwwwmmwwww......',
    '......wwwwwwwwwwwwwwmmwwww......',
    '......wwwwllwwwwwwwwwwwwww......',
    '.......wwwllwwwwwwwwwwwww.......',
    '.......wwwwwwwwwmmwwwwwww.......',
    '........wwwwwwwwmmwwwwww........',
    '........wwwwwwwwwwwwwwww........',
    '.........wwwwwwwwwwwwww.........',
    '.........wwwwwwwwwwwwww.........',
    '...........wwwwwwwwww...........',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  palette: {
    'w': 0xFFF6EFE3,
    'l': 0xFFFFFDF6,
    'm': 0xFFF0A8B8,
  },
);
