// 孵化前的蛋：奶白底 + 粉色斑点。

import 'pixel_art.dart';

const BuddyPixelArt kBuddyEggArt = BuddyPixelArt(
  rows: [
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '...........................wwwwwwwwww...........................',
    '.........................wwwwwwwwwwwwww.........................',
    '.......................wwwwwwwwwwwwwwwwww.......................',
    '......................wwwwwwwwwwwwwwwwwwww......................',
    '......................wwwwwwwwwwwwwwwwwwww......................',
    '.....................wwwwwwwwwwwwwwwwwwwwww.....................',
    '...................wwwwwwwwwwwwwwwwwwwwwwwwww...................',
    '..................wwwwwwwwwwwwwwwwwwwwwwwwwwww..................',
    '..................wwwwwwwwwwwllwwwwwwwwwwwwwww..................',
    '.................wwwwwwwwwwlllllwwwwwwwwwwwwwww.................',
    '.................wwwwwwwwwwlllllwwwwwwwwwwwwwww.................',
    '................wwwwwwwwwllllllwwwwwwwwwwwwwwwww................',
    '................wwwwwwwwwllllllwwwwwwmmwwwwwwwww................',
    '...............wwwwwwwwwlllllwwwwwwwmmmmwwwwwwwww...............',
    '...............wwwwwwwwwlllllwwwwwwwmmmmwwwwwwwww...............',
    '..............wwwwwwwwwwwllwwwwwwwwwwmmwwwwwwwwwww..............',
    '..............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww..............',
    '.............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.............',
    '.............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.............',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............',
    '............wwwwwwwwwmmwwwwwwwwwwwwwwwwwwllwwwwwwwww............',
    '............wwwwwwwwmmmmwwwwwwwwwwwwwwwwllllwwwwwwww............',
    '............wwwwwwwwmmmmwwwwwwwwwwwwwwwwllllwwwwwwww............',
    '............wwwwwwwwwmmwwwwwwwwwwwwwwwwwwllwwwwwwwww............',
    '............wwwwwwwwwwwwwwwwwwwwwllwwwwwwwwwwwwwwwww............',
    '............wwwwwwwwwwwwwwwwwwwwllllwwwwwwwwwwwwwwww............',
    '............wwwwwwwwwwwwwwwwwwwwllllwwwwwwwwwwwwwwww............',
    '............wwwwwwwwwwwwwwwwwwwwwllwwwwwwwwwwwwwwwww............',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmwwwwwwwww............',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmwwwwwwww............',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmwwwwwwww............',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmwwwwwwwww............',
    '............wwwwwwwwwllwwwwwwwwwwwwwwwwwwwwwwwwwwwww............',
    '.............wwwwwwwllllwwwwwwwwwwwwwwwwwwwwwwwwwww.............',
    '.............wwwwwwwllllwwwwwwwwwwwwwwwwwwwwwwwwwww.............',
    '..............wwwwwwwllwwwwwwwwwwwwwwwwwwwwwwwwwww..............',
    '..............wwwwwwwwwwwwwwwwwwwmmwwwwwwwwwwwwwww..............',
    '...............wwwwwwwwwwwwwwwwwmmmmwwwwwwwwwwwww...............',
    '...............wwwwwwwwwwwwwwwwwmmmmwwwwwwwwwwwww...............',
    '................wwwwwwwwwwwwwwwwwmmwwwwwwwwwwwww................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww................',
    '.................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.................',
    '.................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.................',
    '..................wwwwwwwwwwwwwwwwwwwwwwwwwwww..................',
    '..................wwwwwwwwwwwwwwwwwwwwwwwwwwww..................',
    '...................wwwwwwwwwwwwwwwwwwwwwwwwww...................',
    '.....................wwwwwwwwwwwwwwwwwwwwww.....................',
    '.......................wwwwwwwwwwwwwwwwww.......................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'w': 0xFFF6EFE3,
    'l': 0xFFFFFDF6,
    'm': 0xFFF0A8B8,
  },
);
