// 电子宠物像素图：幽灵：白色 + 波浪下摆。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt ghostArt = BuddyPixelArt(
  rows: [
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '.......................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.......................................',
    '.....................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.....................................',
    '...................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...................................',
    '.................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.................................',
    '...............................HHHHHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHHHHS...............................',
    '.............................HHHHHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHHSSS.............................',
    '.............................HHHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHSSS.............................',
    '............................HHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHSSSS............................',
    '............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................',
    '............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................',
    '............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................',
    '............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................',
    '.......................HHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHS.......................',
    '.....................HHHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHSSS.....................',
    '.....................HHHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHSSS.....................',
    '....................HHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHSSSS....................',
    '....................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww....................',
    '....................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww....................',
    '....................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww....................',
    '....................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww....................',
    '...................HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS...................',
    '.................HHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS.................',
    '.................HHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS.................',
    '................HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooowwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppwwwwwwwSSSS................',
    '................wwwwwwwwwppppppwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooowwwwwwwwwwwwwwwwwwwwwwwwwwppppppwwwwwSSSS................',
    '................wwwwwwwwwppppppppwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooowwwwwwwwwwwwwwwwwwwwwwwwppppppppwwwwwSSSS................',
    '................wwwwwwwwppppppppppwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooowwwwwwwwwwwwwwwwwwwwwwppppppppppwwwwSSSS................',
    '................wwwwwwwwppppppppppwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooowwwwwwwwwwwwwwwwwwwwwwppppppppppwwwwSSSS................',
    '................wwwwwwwwpppppppppppwwwwwwwwwwwwwwwwwwwwwwoooooooooooooowwwwwwwwwwwwwwwwwwwwwwpppppppppppwwwwSSSS................',
    '................wwwwwwwwpppppppppppppwwwwwwwwwwwwwwwwwwwwoooooooooooooowwwwwwwwwwwwwwwwwwwwpppppppppppppwwwwSSSS................',
    '................wwwwwwwwppppppppppppppwwwwwwwwwwwwwwwwwwwwwoooooooooowwwwwwwwwwwwwwwwwwwwwppppppppppppppwwwwSSSS................',
    '................wwwwwwwwppppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppppwwwwSSSS................',
    '................wwwwwwwwwppppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppppwwwwwSSSS................',
    '................wwwwwwwwwppppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppppwwwwwSSSS................',
    '................wwwwwwwwwwppppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppppwwwwwwSSSS................',
    '................wwwwwwwwwwppppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppppwwwwwwSSSS................',
    '................wwwwwwwwwwwppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwwwSSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSwwwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwwwSSSSSSwwwwwwwwwwwwwwwwwwwwwwwwwwSSSSSSwwwwwwwwwwwwwwwwwwwwwwwwwwSSSSSSwwwwwSSSS................',
    '................wwwwwwwwwwwwwwwSSSSSSSSSSwwwwwwwwwwwwwwwwwwwwwwSSSSSSSSSSwwwwwwwwwwwwwwwwwwwwwwSSSSSSSSwwwwwSSSS................',
    '................wwwwwwwwwwwwwwSSSSSSSSSSSSwwwwwwwwwwwwwwwwwwwwSSSSSSSSSSSSwwwwwwwwwwwwwwwwwwwwSSSSSSSSSSwwwwSSSS................',
    '................wwwwwwwwwwwwwwSSSSS..SSSSSwwwwwwwwwwwwwwwwwwwwSSSSS..SSSSSwwwwwwwwwwwwwwwwwwwwSSSSS.....wwwwSSSS................',
    '................wwwwwwwwwwwwwSSSS......SSSSwwwwwwwwwwwwwwwwwwSSSS......SSSSwwwwwwwwwwwwwwwwwwSSSS.......wwwSSSSS................',
    '................wwwwwwwwwwwSSSS..........SSwwwwwwwwwwwwwwwwwwSSSS........SSwwwwwwwwwwwwwwwwwwSSSS.......wwwSSSSS................',
    '................wwwwwwwwwwSSSS.............SwwwwwwwwwwwwwwwwSSSS...........SwwwwwwwwwwwwwwwwSSSS........wSSSSSSS................',
    '................wwwwwwwwwwSSSS..............wwwwwwwwwwwwwwwwSSSS............wwwwwwwwwwwwwwwwSSSS........SSSSSSSS................',
    '................wwwwwwwwwSSSS...............wwwwwwwwwwwwwwwwSSSS............wwwwwwwwwwwwwwwwSSSS.........SSSSSS.................',
    '................wwwwwwwwwSSSS...............wwwwwwwwwwwwwwwwSSSS............wwwwwwwwwwwwwwwwSSSS.........SSSSSS.................',
    '................wwwwwwwwSSSS................wwwwwwwwwwwwwwwwSSSS............wwwwwwwwwwwwwwwwSSSS...........SS...................',
    '................wwwwwwwwSSSS................SSSSSwwwwwwwwwwwSSSS............SSSSSwwwwwwwwwwwSSSS................................',
    '................wwwwwwwSSSS..................SSSSSSwwwwwwwwSSSS..............SSSSSSwwwwwwwwSSSS.................................',
    '................wwwwwwwSSSS..................SSSSSSSSwwwwwwSSSS..............SSSSSSSSwwwwwwSSSS.................................',
    '................wwwwwSSSSS.....................SSSSSSSSwwSSSSS.................SSSSSSSSwwSSSSS..................................',
    '................SSSSSSSSSS.......................SSSSSSSSSSSSS...................SSSSSSSSSSSSS..................................',
    '.................SSSSSSSS..........................SSSSSSSSSS......................SSSSSSSSSS...................................',
    '.................SSSSSS..............................SSSSSS..........................SSSSSS.....................................',
    '...................SS..................................SS..............................SS.......................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'w': 0xFFEFF1F6,
    'o': 0xFF9AA3B5,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFC4C6CA,
    'H': 0xFFF3F4F8,
  },
);
