// 电子宠物像素图：幽灵：白色 + 波浪下摆。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt ghostArt = BuddyPixelArt(
  rows: [
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '...................HHHHHHHHHHHHHHHHHHHHHHHHHH...................',
    '.................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.................',
    '...............HHHHwwwwwwwwwwwwwwwwwwwwwwwwwwHHHS...............',
    '..............HHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHSS..............',
    '..............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww..............',
    '..............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww..............',
    '...........HHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHS...........',
    '..........HHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHSS..........',
    '..........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww..........',
    '..........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww..........',
    '.........HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS.........',
    '........HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwEEwwwwwwwwwwwwwwwwwwwwwwEEwwwwwwwwwSS........',
    '........wwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwSS........',
    '........wwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwSS........',
    '........wwwwwwwwEEEEEEEEwwwwwwwwwwwwwwwwEEEEEEEEwwwwwwSS........',
    '........wwwwwwwwEEEEEEEEwwwwwwwwwwwwwwwwEEEEEEEEwwwwwwSS........',
    '........wwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwSS........',
    '........wwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwSS........',
    '........wwwwwwwwwwwEEwwwwwwwwwwwwwwwwwwwwwwEEwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwppwwwwwwwwwwwwwwoooooowwwwwwwwwwwwwwppwwwSS........',
    '........wwwwpppppwwwwwwwwwwwoooooooowwwwwwwwwwwpppppwwSS........',
    '........wwwwpppppwwwwwwwwwwwoooooooowwwwwwwwwwwpppppwwSS........',
    '........wwwwpppppppwwwwwwwwwwoooooowwwwwwwwwwpppppppwwSS........',
    '........wwwwpppppppwwwwwwwwwwwwwwwwwwwwwwwwwwpppppppwwSS........',
    '........wwwwwpppppppwwwwwwwwwwwwwwwwwwwwwwwwpppppppwwwSS........',
    '........wwwwwpppppppwwwwwwwwwwwwwwwwwwwwwwwwpppppppwwwSS........',
    '........wwwwwwwppppwwwwwwwwwwwwwwwwwwwwwwwwwwppppwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '........wwwwwwwwwSSwwwwwwwwwwwwwwSSwwwwwwwwwwwwwwSSwwwSS........',
    '........wwwwwwwSSSSSSwwwwwwwwwwSSSSSSwwwwwwwwwwSSSSSwwSS........',
    '........wwwwwwwSS..SSwwwwwwwwwwSS..SSwwwwwwwwwwSS...wwSS........',
    '........wwwwwSS......SwwwwwwwwSS.....SwwwwwwwwSS....wSSS........',
    '........wwwwwSS.......wwwwwwwwSS......wwwwwwwwSS....SSSS........',
    '........wwwwSS........wwwwwwwwSS......wwwwwwwwSS.....SS.........',
    '........wwwwSS........SSSwwwwwSS......SSSwwwwwSS................',
    '........wwwSS..........SSSSwwSS........SSSSwwSS.................',
    '........SSSSS............SSSSSS..........SSSSSS.................',
    '.........SS................SS..............SS...................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'w': 0xFFEFF1F6,
    'o': 0xFF9AA3B5,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFC4C6CA,
    'H': 0xFFF3F4F8,
  },
);
