// 电子宠物像素图：鹅：白色长脖子 + 橙嘴。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt gooseArt = BuddyPixelArt(
  rows: [
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '.......................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.......................................................',
    '.....................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.....................................................',
    '...................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...................................................',
    '.................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.................................................',
    '...............................HHHHHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHHHHS...............................................',
    '.............................HHHHHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHHSSS.............................................',
    '.............................HHHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHSSS.............................................',
    '............................HHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHSSSS............................................',
    '............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................................',
    '............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................................',
    '............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................................',
    '............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................................',
    '...........................HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS...........................................',
    '.........................HHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS.........................................',
    '.........................HHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS.........................................',
    '........................HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS........................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEE........................................',
    '........................wwwwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEE........................................',
    '........................wwwwwwwwwwwwwwwwwwwEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEE........................................',
    '........................wwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEE........................................',
    '........................wwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEE........................................',
    '........................wwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEE........................................',
    '........................wwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEE........................................',
    '........................wwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEE........................................',
    '........................wwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEE........................................',
    '........................wwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEE.........................................',
    '........................wwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEE.........................................',
    '........................wwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwEEEEEEEEEEEEEE..........................................',
    '........................wwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwEEEEEEEEEEEEEE..........................................',
    '........................wwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEwwwwwwwwwwwwwwwwEEEEEEEEEEEEE...........................................',
    '........................wwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEwwwwwwwwwwwwwwwwEEEEEEEEEEE.............................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEwwwwwwwwwwwwwwwwEEEEEEEEE...............................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooooooooooooooooooo................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooooooooooooooooo.................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooooooooooooooooo.................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooooooooooooooo..................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooooooooooooooo..................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooooooooooooo...................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooooooooooooo...................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooooooooooo....................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooooooooooo....................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooooooooo.....................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooooooooo.....................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwooooooooooooooooooo.......................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwooooooooooooooooo.........................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooo...........................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooo.............................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwooooooooo...............................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS........................................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS........................................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS........................................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS........................................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS........................................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS........................................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS........................................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS........................................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww........................................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww........................................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww........................................................................',
    '........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww........................................................................',
    '.......................HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwH.......................................................................',
    '.....................HHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHH.....................................................................',
    '.....................HHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHH...................................................................',
    '....................HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHH.................................................................',
    '....................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.......................................',
    '....................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.....................................',
    '....................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...................................',
    '....................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.................................',
    '...............HHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHHHHS...............................',
    '.............HHHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHHSSS.............................',
    '.............HHHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHSSS.............................',
    '............HHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHSSSS............................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................',
    '...........HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHS.......................',
    '.........HHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHSSS.....................',
    '.........HHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHSSS.....................',
    '........HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHSSSS....................',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww....................',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww....................',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww....................',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww....................',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS...................',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS.................',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS.................',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '........SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................',
    '.........SSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS.................',
    '.........SSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS.................',
    '...........SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS..................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS..................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS...................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSSSS...................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSSSS....................',
    '............SSSSSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSSSS....................',
    '.............SSSSSSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSSSS.....................',
    '.............SSSSSSSSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSSSSSS.....................',
    '...............SSSSSSSSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSSSSSS.......................',
    '.................SSSSSSSSSSSSwwwwwwwwwwwwwwwwwwwwwwSSSSSSSSSSSSSSSSSSwwwwwwwwwwwwwwwwwwwwwwSSSSSSSSSSSS.........................',
    '...................SSSSSSSSSSSSwwwwwwwwwwwwwwwwwwSSSSSSSSSSSSSSSSSSSSSSwwwwwwwwwwwwwwwwwwSSSSSSSSSSSS...........................',
    '.....................SSSSSSSSSSwwwwwwwwwwwwwwwwwwSSSSSSSSSSSSSSSSSSSSSSwwwwwwwwwwwwwwwwwwSSSSSSSSSS.............................',
    '.......................SSSSSSSSSwwwwwwwwwwwwwwwwSSSSSSSSSSSSSSSSSSSSSSSSwwwwwwwwwwwwwwwwSSSSSSSSS...............................',
    '................................oooooooooooooooo........................oooooooooooooooo........................................',
    '.................................oooooooooooooo..........................oooooooooooooo.........................................',
    '.................................oooooooooooooo..........................oooooooooooooo.........................................',
    '..................................oooooooooooo............................oooooooooooo..........................................',
    '..................................oooooooooooo............................oooooooooooo..........................................',
    '...................................oooooooooo..............................oooooooooo...........................................',
    '.....................................oooooo..................................oooooo.............................................',
    '.......................................oo......................................oo...............................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'w': 0xFFF3F1EA,
    'o': 0xFFF08C2E,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFC7C6C0,
    'H': 0xFFF6F4EF,
  },
);
