// 电子宠物像素图：鹅：白色长脖子 + 橙嘴。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt gooseArt = BuddyPixelArt(
  rows: [
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '...................HHHHHHHHHHHHHHHHHH...........................',
    '.................HHHHHHHHHHHHHHHHHHHHHH.........................',
    '...............HHHHwwwwwwwwwwwwwwwwwwHHHS.......................',
    '..............HHHwwwwwwwwwwwwwwwwwwwwwwHSS......................',
    '..............wwwwwwwwwwwwwwwwwwwwwwwwwwww......................',
    '..............wwwwwwwwwwwwwwwwwwwwwwwwwwww......................',
    '.............HwwwwwwwwwwwwwwwwwwwwwwwwwwwwS.....................',
    '............HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS....................',
    '............wwwwwwwwwwwEEwwwwwwwwwwwwwwEEEEE....................',
    '............wwwwwwwwwEEEEEEwwwwwwwwwwEEEEEEE....................',
    '............wwwwwwwwwEEEEEEwwwwwwwwwwEEEEEEE....................',
    '............wwwwwwwwEEEEEEEEwwwwwwwwEEEEEEEE....................',
    '............wwwwwwwwEEEEEEEEwwwwwwwwEEEEEEEE....................',
    '............wwwwwwwwwEEEEEEEwwwwwwwwEEEEEEE.....................',
    '............wwwwwwwwwEEEEEEEwwwwwwwwEEEEEEE.....................',
    '............wwwwwwwwwwwEEEEEwwwwwwwwEEEEE.......................',
    '............wwwwwwwwwwwwoooooooooooooooo........................',
    '............wwwwwwwwwwwwwoooooooooooooo.........................',
    '............wwwwwwwwwwwwwoooooooooooooo.........................',
    '............wwwwwwwwwwwwwwoooooooooooo..........................',
    '............wwwwwwwwwwwwwwoooooooooooo..........................',
    '............wwwwwwwwwwwwwwwoooooooooo...........................',
    '............wwwwwwwwwwwwwwwoooooooo.............................',
    '............wwwwwwwwwwwwwwwwooooo...............................',
    '............wwwwwwwwwwwwwwwS....................................',
    '............wwwwwwwwwwwwwwSS....................................',
    '............wwwwwwwwwwwwwwSS....................................',
    '............wwwwwwwwwwwwwwwS....................................',
    '............wwwwwwwwwwwwwwww....................................',
    '............wwwwwwwwwwwwwwww....................................',
    '...........HwwwwwwwwwwwwwwwwH...................................',
    '..........HwwwwwwwwwwwwwwwwwwHH.................................',
    '..........wwwwwwwwwwwwwwwwwwwHHHHHHHHHHHHHHHH...................',
    '..........wwwwwwwwwwwwwwwwwwwwwHHHHHHHHHHHHHHHH.................',
    '.......HHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHS...............',
    '......HHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHSS..............',
    '......wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww..............',
    '......wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww..............',
    '.....HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHS...........',
    '....HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHSS..........',
    '....wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww..........',
    '....wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww..........',
    '....wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS.........',
    '....wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '....SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS........',
    '.....SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS.........',
    '......wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS.........',
    '......wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS..........',
    '......SSSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS..........',
    '.......SSSSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS...........',
    '.........SSSSSSwwwwwwwwwwSSSSSSSSSSwwwwwwwwwwSSSSSS.............',
    '...........SSSSSwwwwwwwwSSSSSSSSSSSSwwwwwwwwSSSSS...............',
    '................oooooooo............oooooooo....................',
    '.................oooooo..............oooooo.....................',
    '.................oooooo..............oooooo.....................',
    '...................oo..................oo.......................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'w': 0xFFF3F1EA,
    'o': 0xFFF08C2E,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFC7C6C0,
    'H': 0xFFF6F4EF,
  },
);
