// 帽子像素图（小图，渲染器锚定在头顶第一行非透明像素上方叠加）。

import '../buddy_types.dart';
import 'pixel_art.dart';

const Map<BuddyHat, BuddyPixelArt> kBuddyHatArts = {
  BuddyHat.crown: BuddyPixelArt(
    rows: [
    '..yyyy....................yyyy....................yyyy..',
    '.yyyyyy..................yyyyyy..................yyyyyy.',
    'yyyyyyyyy..............yyyyyyyyyy..............yyyyyyyyy',
    'yyyyyyyyyy............yyyyyyyyyyyy............yyyyyyyyyy',
    'yyyyyyyyyy............yyyyyyyyyyyy............yyyyyyyyyy',
    'yyyyyyyyyyy..........yyyyyyyyyyyyyy..........yyyyyyyyyyy',
    'yyyyyyyyyyyyy......yyyyyyyyyyyyyyyyyy......yyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyy..yyyyyyyyyyyyyyyyyyyyyy..yyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    '.yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.',
    '..yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy..',
    '..yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy..',
    '...yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy...',
    '.....yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.....',
    '......yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy......',
  ],
    palette: {'y': 0xFFF2C14E},
  ),
  BuddyHat.tophat: BuddyPixelArt(
    rows: [
    '..............kkkkkkkkkkkkkkkkkkkkkkkkkkkk..............',
    '.............kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.............',
    '...........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...........',
    '..........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..........',
    '..........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..........',
    '.........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........',
    '.........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........',
    '........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk........',
    '........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk........',
    '.......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......',
    '.......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......',
    '......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......',
    '......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......',
    '.....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....',
    '...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
  ],
    palette: {'k': 0xFF3A3F4A},
  ),
  BuddyHat.propeller: BuddyPixelArt(
    rows: [
    '..rrrr....................yyyy....................bbbb..',
    '.rrrrrr..................yyyyyy..................bbbbbb.',
    'rrrrrrrrr..............yyyyyyyyyy..............bbbbbbbbb',
    'rrrrrrrrrr............yyyyyyyyyyyy............bbbbbbbbbb',
    'rrrrrrrrrr............yyyyyyyyyyyy............bbbbbbbbbb',
    'rrrrrrrrrrr..........yyyyyyyyyyyyyy..........bbbbbbbbbbb',
    '.rrrrrrrrrrrr......yyyyyyyyyyyyyyyyyy......bbbbbbbbbbbb.',
    '..rrrrrrrrrrrrr..yyyyyyyyyyyyyyyyyyyyyy..bbbbbbbbbbbbb..',
    '..rrrrrrrrrrrrrryyyyyyyyyyyyyyyyyyyyyyyybbbbbbbbbbbbbb..',
    '...rrrrrrrrrrrrryyyyyyyyyyyyyyyyyyyyyyyybbbbbbbbbbbbb...',
    '.....rrrrrrrrrrryyyyyyyyyyyyyyyyyyyyyyyybbbbbbbbbbb.....',
    '......rrrrrrrrrryyyyyyyyyyyyyyyyyyyyyyyybbbbbbbbbb......',
    '......rrrrrrrrrryyyyyyyyyyyyyyyyyyyyyyyybbbbbbbbbb......',
    '.......rrrrrrrrryyyyyyyyyyyyyyyyyyyyyyyybbbbbbbbb.......',
    '.........rrrrrrryyyyyyyyyyyyyyyyyyyyyyyybbbbbbb.........',
    '...........rrrrryyyyyyyyyyyyyyyyyyyyyyyybbbbb...........',
    '................yyyyyyyyyyyyyyyyyyyyyyyy................',
    '.................yyyyyyyyyyyyyyyyyyyyyy.................',
    '.................yyyyyyyyyyyyyyyyyyyyyy.................',
    '..................yyyyyyyyyyyyyyyyyyyy..................',
    '..................yyyyyyyyyyyyyyyyyyyy..................',
    '...................yyyyyyyyyyyyyyyyyy...................',
    '.....................yyyyyyyyyyyyyy.....................',
    '......................yyyyyyyyyyyy......................',
  ],
    palette: {'r': 0xFFE0605A, 'y': 0xFFF2C14E, 'b': 0xFF5B8DEF},
  ),
  BuddyHat.halo: BuddyPixelArt(
    rows: [
    '..........yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy..........',
    '.........yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.........',
    '.......yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.......',
    '......yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy......',
    '......yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy......',
    '.....yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.....',
    '...yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy...',
    '..yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy..',
    '..yyyyyyyyy..................................yyyyyyyyy..',
    '.yyyyyyyy......................................yyyyyyyy.',
    'yyyyyyyyy......................................yyyyyyyyy',
    'yyyyyyyy........................................yyyyyyyy',
    'yyyyyyyy........................................yyyyyyyy',
    'yyyyyyyyy......................................yyyyyyyyy',
    '.yyyyyyyy......................................yyyyyyyy.',
    '..yyyyyyyyy..................................yyyyyyyyy..',
    '..yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy..',
    '...yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy...',
    '.....yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.....',
    '......yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy......',
    '......yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy......',
    '.......yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.......',
    '.........yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.........',
    '..........yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy..........',
  ],
    palette: {'y': 0xFFF7DE8B},
  ),
  BuddyHat.wizard: BuddyPixelArt(
    rows: [
    '..........................vvvv..........................',
    '.........................vvvvvv.........................',
    '.......................vvvvvvvvvv.......................',
    '......................vvvvvvvvvvvv......................',
    '......................vvvvvvvvvvvv......................',
    '.....................vvvvvvvvvvvvvv.....................',
    '.....................vvvvvvvvvvvvvv.....................',
    '....................vvvvvvvvvvvvvvvv....................',
    '....................vvvvvvvvvvvvvvvv....................',
    '...................vvvvvvvvvvvvvvvvvv...................',
    '...................vvvvvvvvvvvvvvvvvv...................',
    '.................vvvvvvvvvvvvvvvvvvvvvv.................',
    '...............vvvvvvvvvvvvvvvvvvvvvvvvvv...............',
    '.............vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv.............',
    '.............vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv.............',
    '............vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv............',
    '............vvvvvvvvvvvvvvvyyvvvvvvvvvvvvvvv............',
    '...........vvvvvvvvvvvvvvyyyyyyvvvvvvvvvvvvvv...........',
    '...........vvvvvvvvvvvvvvyyyyyyvvvvvvvvvvvvvv...........',
    '.........vvvvvvvvvvvvvvvyyyyyyyyvvvvvvvvvvvvvvv.........',
    '.......vvvvvvvvvvvvvvvvvyyyyyyyyvvvvvvvvvvvvvvvvv.......',
    '.....vvvvvvvvvvvvvvvvvvvvyyyyyyvvvvvvvvvvvvvvvvvvvv.....',
    '...vvvvvvvvvvvvvvvvvvvvvvyyyyyyvvvvvvvvvvvvvvvvvvvvvv...',
    '..vvvvvvvvvvvvvvvvvvvvvvvvvyyvvvvvvvvvvvvvvvvvvvvvvvvv..',
    '..vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv..',
    '.vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv.',
    'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    '.vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv.',
    '..vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv..',
  ],
    palette: {'v': 0xFF7B5CC7, 'y': 0xFFF2C14E},
  ),
  BuddyHat.beanie: BuddyPixelArt(
    rows: [
    '......................rrrr..............................',
    '.....................rrrrrr.............................',
    '...................rrrrrrrrrr...........................',
    '.................rrrrrrrrrrrrrr.........................',
    '...............rrrrrrrrrrrrrrrrrr.......................',
    '.............rrrrrrrrrrrrrrrrrrrrrr.....................',
    '.............rrrrrrrrrrrrrrrrrrrrrr.....................',
    '............rrrrrrrrrrrrrrrrrrrrrrrr....................',
    '............rrrrrrrrrrrrrrrrrrrrrrrr....................',
    '...........rrrrrrrrrrrrrrrrrrrrrrrrrr...................',
    '...........rrrrrrrrrrrrrrrrrrrrrrrrrr...................',
    '.........rrrrrrrrrrrrrrrrrrrrrrrrrrrrr..................',
    '.......rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..................',
    '.....rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.................',
    '...rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.................',
    '..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr................',
    '..rrrrrrrrrwwrrrrrrrrrrrrrrwwrrrrrrrrrrrwwwwwwwwrrrrr...',
    '.rrrrrrrrwwwwwwrrrrrrrrrrwwwwwwrrrrrrrrrwwwwwwwwrrrrrrr.',
    'rrrrrrrrrwwwwwwrrrrrrrrrrwwwwwwrrrrrrrrrwwwwwwwwrrrrrrrr',
    'rrrrrrrrwwwwwwwwrrrrrrrrwwwwwwwwrrrrrrrrwwwwwwwwrrrrrrrr',
    'rrrrrrrrwwwwwwwwrrrrrrrrwwwwwwwwrrrrrrrrwwwwwwwwrrrrrrrr',
    'rrrrrrrrwwwwwwwwrrrrrrrrwwwwwwwwrrrrrrrrwwwwwwwwrrrrrrrr',
    '.rrrrrrrwwwwwwwwrrrrrrrrwwwwwwwwrrrrrrrrwwwwwwwwrrrrrrr.',
    '..rrrrrrwwwwwwwwrrrrrrrrwwwwwwwwrrrrrrrrwwwwwwwwrrrrrr..',
  ],
    palette: {'r': 0xFFD96A6A, 'w': 0xFFF3EAD9},
  ),
  BuddyHat.tinyduck: BuddyPixelArt(
    rows: [
    '..............yyyy..............',
    '.............yyyyyy.............',
    '...........yyyyyyyyyy...........',
    '..........yyyyyyyyyyyyy.........',
    '..........yyyyyyyyyyyyyyy.......',
    '.........yyyyyyyyyyyyyyyyyy.....',
    '.........yyyyyyyyyyyyyyyyyyyy...',
    '........yyyyyyyyyyyyyyyyyyyyyy..',
    '...oooooyyyyyyyyyyyyyyyyyyyyyy..',
    '.oooooooyyyyyyyyyyyyyyyyyyyyyyy.',
    'ooooooooyyyyyyyyyyyyyyyyyyyyyyyy',
    'ooooooooyyyyyyyyyyyyyyyyyyyyyyyy',
    'ooooooooyyyyyyyyyyyyyyyyyyyyyyyy',
    'ooooooooyyyyyyyyyyyyyyyyyyyyyyyy',
    '.oooooooyyyyyyyyyyyyyyyyyyyyyyy.',
    '...oooooyyyyyyyyyyyyyyyyyyyyyy..',
    '........yyyyyyyyyyyyyyyyyyyyyy..',
    '.........yyyyyyyyyyyyyyyyyyyy...',
    '.........yyyyyyyyyyyyyyyyyy.....',
    '..........yyyyyyyyyyyyyyy.......',
    '..........yyyyyyyyyyyyy.........',
    '...........yyyyyyyyyy...........',
    '.............yyyyyy.............',
    '..............yyyy..............',
  ],
    palette: {'y': 0xFFF7D154, 'o': 0xFFF08C2E},
  ),
};
