// 帽子像素图（小图，渲染器锚定在头顶第一行非透明像素上方叠加）。

import '../buddy_types.dart';
import 'pixel_art.dart';

const Map<BuddyHat, BuddyPixelArt> kBuddyHatArts = {
  BuddyHat.crown: BuddyPixelArt(
    rows: [
    '.yy..........yy..........yy.',
    'yyyyy......yyyyyy......yyyyy',
    'yyyyy......yyyyyy......yyyyy',
    'yyyyyyy..yyyyyyyyyy..yyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    '.yyyyyyyyyyyyyyyyyyyyyyyyyy.',
    '.yyyyyyyyyyyyyyyyyyyyyyyyyy.',
    '...yyyyyyyyyyyyyyyyyyyyyy...',
  ],
    palette: {'y': 0xFFF2C14E},
  ),
  BuddyHat.tophat: BuddyPixelArt(
    rows: [
    '.......kkkkkkkkkkkkkk.......',
    '.....kkkkkkkkkkkkkkkkkk.....',
    '.....kkkkkkkkkkkkkkkkkk.....',
    '....kkkkkkkkkkkkkkkkkkkk....',
    '....kkkkkkkkkkkkkkkkkkkk....',
    '...kkkkkkkkkkkkkkkkkkkkkk...',
    '...kkkkkkkkkkkkkkkkkkkkkk...',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkk.',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkk.',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkk.',
  ],
    palette: {'k': 0xFF3A3F4A},
  ),
  BuddyHat.propeller: BuddyPixelArt(
    rows: [
    '.rr..........yy..........bb.',
    'rrrrr......yyyyyy......bbbbb',
    'rrrrr......yyyyyy......bbbbb',
    '.rrrrrr..yyyyyyyyyy..bbbbbb.',
    '.rrrrrrryyyyyyyyyyyybbbbbbb.',
    '...rrrrryyyyyyyyyyyybbbbb...',
    '...rrrrryyyyyyyyyyyybbbbb...',
    '.....rrryyyyyyyyyyyybbb.....',
    '........yyyyyyyyyyyy........',
    '.........yyyyyyyyyy.........',
    '.........yyyyyyyyyy.........',
    '...........yyyyyy...........',
  ],
    palette: {'r': 0xFFE0605A, 'y': 0xFFF2C14E, 'b': 0xFF5B8DEF},
  ),
  BuddyHat.halo: BuddyPixelArt(
    rows: [
    '.....yyyyyyyyyyyyyyyyyy.....',
    '...yyyyyyyyyyyyyyyyyyyyyy...',
    '...yyyyyyyyyyyyyyyyyyyyyy...',
    '.yyyyyyyyyyyyyyyyyyyyyyyyyy.',
    '.yyyy..................yyyy.',
    'yyyy....................yyyy',
    'yyyy....................yyyy',
    '.yyyy..................yyyy.',
    '.yyyyyyyyyyyyyyyyyyyyyyyyyy.',
    '...yyyyyyyyyyyyyyyyyyyyyy...',
    '...yyyyyyyyyyyyyyyyyyyyyy...',
    '.....yyyyyyyyyyyyyyyyyy.....',
  ],
    palette: {'y': 0xFFF7DE8B},
  ),
  BuddyHat.wizard: BuddyPixelArt(
    rows: [
    '.............vv.............',
    '...........vvvvvv...........',
    '...........vvvvvv...........',
    '..........vvvvvvvv..........',
    '..........vvvvvvvv..........',
    '.........vvvvvvvvvv.........',
    '.......vvvvvvvvvvvvvv.......',
    '......vvvvvvvvvvvvvvvv......',
    '......vvvvvvvyyvvvvvvv......',
    '.....vvvvvvvyyyyvvvvvvv.....',
    '...vvvvvvvvvyyyyvvvvvvvvv...',
    '.vvvvvvvvvvvvyyvvvvvvvvvvvv.',
    '.vvvvvvvvvvvvvvvvvvvvvvvvvv.',
    'vvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    'vvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    '.vvvvvvvvvvvvvvvvvvvvvvvvvv.',
  ],
    palette: {'v': 0xFF7B5CC7, 'y': 0xFFF2C14E},
  ),
  BuddyHat.beanie: BuddyPixelArt(
    rows: [
    '...........rr...............',
    '.........rrrrrr.............',
    '.......rrrrrrrrrr...........',
    '......rrrrrrrrrrrr..........',
    '......rrrrrrrrrrrr..........',
    '.....rrrrrrrrrrrrrr.........',
    '...rrrrrrrrrrrrrrrr.........',
    '.rrrrrrrrrrrrrrrrrrr........',
    '.rrrrwwrrrrrrwwrrrrrwwwwrrr.',
    'rrrrwwwwrrrrwwwwrrrrwwwwrrrr',
    'rrrrwwwwrrrrwwwwrrrrwwwwrrrr',
    '.rrrwwwwrrrrwwwwrrrrwwwwrrr.',
  ],
    palette: {'r': 0xFFD96A6A, 'w': 0xFFF3EAD9},
  ),
  BuddyHat.tinyduck: BuddyPixelArt(
    rows: [
    '.......yy.......',
    '.....yyyyyy.....',
    '.....yyyyyyyy...',
    '....yyyyyyyyyyy.',
    '.oooyyyyyyyyyyy.',
    'ooooyyyyyyyyyyyy',
    'ooooyyyyyyyyyyyy',
    '.oooyyyyyyyyyyy.',
    '....yyyyyyyyyyy.',
    '.....yyyyyyyy...',
    '.....yyyyyy.....',
    '.......yy.......',
  ],
    palette: {'y': 0xFFF7D154, 'o': 0xFFF08C2E},
  ),
};
