// 电子宠物像素图：蘑菇：红伞白点 + 奶油脸。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt mushroomArt = BuddyPixelArt(
  rows: [
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '...............................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...............................................',
    '.............................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.............................................',
    '...........................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...........................................',
    '.........................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.........................................',
    '.......................................HHHHHHHHrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrHHHHHHHS.......................................',
    '.....................................HHHHHHHHrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrHHHHHSSS.....................................',
    '...................................HHHHHHHHrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrHHHSSS.....................................',
    '.................................HHHHHHHHrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrHSSSS....................................',
    '...............................HHHHHHHHrrrrrrrrrrrrrrrrwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr....................................',
    '.............................HHHHHHHHrrrrrrrrrrrrrrrrwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr....................................',
    '...........................HHHHHHHHrrrrrrrrrrrrrrrrwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr....................................',
    '.........................HHHHHHHHrrrrrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr....................................',
    '.......................HHHHHHHHrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrHHHHH...............................',
    '.....................HHHHHHHHrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrHHHHHH.............................',
    '.....................HHHHHHrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrHHHHHHHH...........................',
    '....................HHHHHrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrHHHHHHHH.........................',
    '....................rrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrHHHHHHHH.......................',
    '....................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrHHHHHHHH.....................',
    '....................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrHHHHHH.....................',
    '....................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrHHHHH....................',
    '...............HHHHHrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS...................',
    '.............HHHHHHrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSS.................',
    '.............HHHHHHrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSS.................',
    '............HHHHHrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS................',
    '............rrrrrrrrrrrrrrrrrrrwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwrrrrrrrrrrrSSSS................',
    '............rrrrrrrrrrrrrrrrrwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwrrrrrrrrrSSSS................',
    '............rrrrrrrrrrrrrrrwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwrrrrrrrSSSS................',
    '............rrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrSSSS................',
    '...........HrrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrSSSS................',
    '.........HHrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrSSSS................',
    '.........HHrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrSSSS................',
    '........HrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrrrwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwrrrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrrrrrwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwrrrrrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrrrrrrrwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwrrrrrrrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS................',
    '........rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS................',
    '........SrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS................',
    '.........SSrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS.................',
    '.........SSSSrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS.................',
    '..........SSSSrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS..................',
    '..........SSSSrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrSSSS..................',
    '...........SSSSrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrSSSS...................',
    '.............SSrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrSS.....................',
    '...............SrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrS.......................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbb........................',
    '................bbbbbbbbbbbppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppbbbbbbbbbbb........................',
    '................bbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbbbbb........................',
    '................bbbbbbbbbppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppbbbbbbbbb........................',
    '................bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbbbbb........................',
    '................bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbbbbb........................',
    '................bbbbbbbbpppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpppppppppppbbbbbbbb........................',
    '................bbbbbbbbpppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpppppppppppppbbbbbbbb........................',
    '................bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbbb........................',
    '................bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbbb........................',
    '.................bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbbb.........................',
    '.................bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbbb.........................',
    '..................bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbbb..........................',
    '..................bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbbb..........................',
    '...................bbbbbbbbppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppbbbbbbbb...........................',
    '...................bbbbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbbbbbbb...........................',
    '....................bbbbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbbbbbbb............................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '.....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.............................',
    '.....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.............................',
    '.......................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...............................',
    '.........................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.................................',
    '...........................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...................................',
    '...........................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...................................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....................................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbb..........bbbbbbbbbbbbbbbbbbbbbbbbbbb....................................',
    '.............................bbbbbbbbbbbbbbbbbbbbbbbb..............bbbbbbbbbbbbbbbbbbbbbbbb.....................................',
    '.............................bbbbbbbbbbbbbbbbbbbbbb..................bbbbbbbbbbbbbbbbbbbbbb.....................................',
    '...............................bbbbbbbbbbbbbbbbbb......................bbbbbbbbbbbbbbbbbb.......................................',
    '.................................bbbbbbbbbbbbbb..........................bbbbbbbbbbbbbb.........................................',
    '...................................bbbbbbbbbb..............................bbbbbbbbbb...........................................',
    '.....................................bbbbbb..................................bbbbbb.............................................',
    '.......................................bb......................................bb...............................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'r': 0xFFE0605A,
    'w': 0xFFF6EFE3,
    'b': 0xFFF0DFC0,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFB84F4A,
    'H': 0xFFE7837E,
  },
);
