// 电子宠物像素图：蘑菇：红伞白点 + 奶油脸。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt mushroomArt = BuddyPixelArt(
  rows: [
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '.......................HHHHHHHHHHHHHHHHHH.......................',
    '.....................HHHHHHHHHHHHHHHHHHHHHH.....................',
    '...................HHHHrrrrrrrrrrrrrrrrrrHHHS...................',
    '.................HHHHrrrrrrrrrrrrrrrrrrrrrrHSS..................',
    '...............HHHHrrrrrrrrwwrrrrrrrrrrrrrrrrr..................',
    '.............HHHHrrrrrrrrwwwwwwrrrrrrrrrrrrrrr..................',
    '...........HHHHrrrrrrrrrrwwwwwwrrrrrrrrrrrrrrrHHH...............',
    '..........HHHrrrrrrrrrrrwwwwwwwwrrrrrrrrrrrrrrrHHHH.............',
    '..........rrrrrrrrrrrrrrwwwwwwwwrrrrrrrrrrrrrrrrrHHHH...........',
    '..........rrrrrrrrrrrrrrrwwwwwwrrrrrrrrrrrrrrrrrrrrHHH..........',
    '.......HHHrrrrrrrrrrrrrrrwwwwwwrrrrrrrrrrrrrrrrrrrrrrrS.........',
    '......HHHrrrrrrrrrrrrrrrrrrwwrrrrrrrrrrrrrrrrrrrrrrrrrSS........',
    '......rrrrrrrrrwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwrrrrrSS........',
    '......rrrrrrrwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwrrrSS........',
    '.....HrrrrrrrwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwrrrSS........',
    '....HrrrrrrrwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwrrSS........',
    '....rrrrrrrrwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwrrSS........',
    '....rrrrrrrrrwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwrrrSS........',
    '....rrrrrrrrrwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwrrrSS........',
    '....rrrrrrrrrrrwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwrrrrrSS........',
    '....rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwrrrrrrrrrrrrrrrrrSS........',
    '....rrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwrrrrrrrrrrrrrrrSS........',
    '....rrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwrrrrrrrrrrrrrrrSS........',
    '....rrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwrrrrrrrrrrrrrrSS........',
    '....SrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwrrrrrrrrrrrrrrSS........',
    '.....SSrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwrrrrrrrrrrrrrSS.........',
    '.....SSrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwrrrrrrrrrrrrrSS.........',
    '.......SrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwrrrrrrrrrrrrS...........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '........bbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbb............',
    '........bbbbbbbbbEEEEEEbbbbbbbbbbbbbbEEEEEEbbbbbbbbb............',
    '........bbbbbbbbbEEEEEEbbbbbbbbbbbbbbEEEEEEbbbbbbbbb............',
    '........bbbbbbbbEEEEEEEEbbbbbbbbbbbbEEEEEEEEbbbbbbbb............',
    '........bbbbbbbbEEEEEEEEbbbbbbbbbbbbEEEEEEEEbbbbbbbb............',
    '........bbbbbbbbbEEEEEEbbbbbbbbbbbbbbEEEEEEbbbbbbbbb............',
    '........bbbbbbbbbEEEEEEbbbbbbbbbbbbbbEEEEEEbbbbbbbbb............',
    '........bbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbb............',
    '........bbbbbppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppbbbbb............',
    '........bbbbpppppbbbbbbbbbbbbbbbbbbbbbbbbbbpppppbbbb............',
    '........bbbbpppppbbbbbbbbbbbbbbbbbbbbbbbbbbpppppbbbb............',
    '........bbbbpppppppbbbbbbbbbbbbbbbbbbbbbbpppppppbbbb............',
    '........bbbbpppppppbbbbbbbbbbbbbbbbbbbbbbpppppppbbbb............',
    '.........bbbbpppppppbbbbbbbbbbbbbbbbbbbbpppppppbbbb.............',
    '.........bbbbpppppppbbbbbbbbbbbbbbbbbbbbpppppppbbbb.............',
    '..........bbbbbppppbbbbbbbbbbbbbbbbbbbbbbppppbbbbb..............',
    '..........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..............',
    '...........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...............',
    '.............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.................',
    '..............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..................',
    '..............bbbbbbbbbbbbb......bbbbbbbbbbbbb..................',
    '...............bbbbbbbbbb..........bbbbbbbbbb...................',
    '.................bbbbbb..............bbbbbb.....................',
    '...................bb..................bb.......................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'r': 0xFFE0605A,
    'w': 0xFFF6EFE3,
    'b': 0xFFF0DFC0,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFB84F4A,
    'H': 0xFFE7837E,
  },
);
