// 奶黄包：以 Codex Pets 官方奶黄包精灵图（待机第 1 帧）为参考
// 量化的 128×128 高清像素版——奶黄圆滚滚小包子、棕色酥顶、黑亮眼睛。

import 'pixel_art.dart';

const BuddyPixelArt naihuangbaoArt = BuddyPixelArt(
  rows: [
    '...........................................................nnnnnnn..............................................................',
    '.......................................................nnnnnnnnnnnnnn...........................................................',
    '....................................................nnnnnooooooooooonnn.........................................................',
    '..................................................nnnnooooooorqooooonnnn........................................................',
    '................................................nnnoooorrrqqqqqqqqoooonnnnnnn...................................................',
    '...............................................nnnoorrrrrqqqoooqqqqqqronnooonnnn................................................',
    '..............................................nnoorrrrrqqqooooooooooooqonoooooonnn..............................................',
    '.............................................nnoorrrrrqqqqooooooooooooqrroooonnoonn.............................................',
    '............................................nnorrrrrrrqqqooooonnnnnnooqrrrrrooonnonn............................................',
    '...........................................nnorrrrrrqrqqqooonnnnnnnnnoorrrrqooooonnnn...........................................',
    '..........................................nnorssrrrrqqqqoonnnnhhchhnnnorrrrqoooooonnnn..........................................',
    '.........................................nnorsssrrrqrqqooonnnhbbbhnnnoorrrrooooooooonnn.........................................',
    '........................................nnnrsssrrrrqrqooonnnnhhhnnnnoorrorqonnnoooqronn.........................................',
    '........................................nnrsssrrrrrrrqooonnnnnnnooqrrsssosqnnnnnooorronn........................................',
    '.......................................nnorssssssrrrqrooonnnnoqrssssssssssonhnnnoooqrrnn........................................',
    '.......................................nnrsssssssrrrrrooooooqrsssssssqqttsrnhhnnooqrrronn.......................................',
    '......................................nnorrrsssssrrrrrroorrrssssqqmmlkilqsssonnnoorrrrrnn.......................................',
    '......................................nnrrrrsssssrrrrrrrrrssssqmmkiffdddgmsssroooorrrsrrnn......................................',
    '.....................................nnnrrrssssrrrrrrrrrssssqmljgfdddddddflqsssqrrrrrssrnn......................................',
    '.....................................nnoorsssssssrrrrrssssqmlkiffddddcccddfkqssrrrrrrrsson......................................',
    '....................................nnnnnrsssssssssrrssssqmkjgfffdddccccdddfjmssrrrrrrssrnn.....................................',
    '....................................nnnnnrssssssssrssssqmlkigffffddddccddddffimssrrrrrrssnn.....................................',
    '....................................nnnnnsssssssssssssqmkjigfffffddddddddddfffgmssrsrrssson.....................................',
    '...................................nnnnnossssssssssssqmkjiggffffffdddddddddffffgmssrssssson.....................................',
    '...................................nnnnnrsssssssssssqmkjiigggfffffddddddddffffffimssrssssrn.....................................',
    '...................................nnnnnsssssssssssqmkjjiigggffffffffddffffffffffjqsssssrrn.....................................',
    '...................................nnnnossssssssssqmkkjiiiggggfffffffffffffffffffglssrssrrn.....................................',
    '...................................nnnnrsssssssssqmlkjiiiiggggfffffffffffffffffffgfmtssrrrn.....................................',
    '..................................nnnnnrsssssssssqmmmmmljgiggggffffffffffgillljgfffjqsrrrrn.....................................',
    '..................................nnnnnsssssssstttttsssqoliggggggffffffflmnooqqomgffmssrrrn.....................................',
    '..................................nnnnnssssssssttqomoqqssqkgiggggffffffmrssqoooqqqlfgqsrron.....................................',
    '..................................nnnnossssssssqmlkkkklmoqkiiggggffffffmomljigggimmffmtsron.....................................',
    '..................................nnnnrsssssssqmlllkkkkjjjiiigggggfffffggfggggfffffffkssron.....................................',
    '..................................nnnnssssssssmmlkklkkjkjjiiiggggggfffggggigffffggfffgqsron.....................................',
    '..................................nnnnsssssssqmmmqttsqmkkjjiigggggggggggggjmmqomjfgggfmtrnn.....................................',
    '.................................nnnnnsssssssqmsttrttttslkjjiiigggggggggimtttttttmffgfmtooo.....................................',
    '.................................nnnnossssssssttrnnEEEEEEljjiiiggggggggjqttEEtnmsEmlgflsqmm.....................................',
    '.................................nnnnrssssssqstocntEEEEtEskkjiiggggggggotttEEEraboEofflsmfdd....................................',
    '.................................nnnnrssssrsqmthbrhoEEEnaEmjjiigggfgggltnotEEbnnabtifflsldddd...................................',
    '.................................nnnnrssssssqqobhtanEEEtnEnjjiigggffggmtaatEEnnoaanjfflofgffd...................................',
    '.................................nnonsssssqsqmnbnttEEEEEEEnkjiiggfffggmtrstEEEEraahjffllijigfd..................................',
    '.................................noonsssssqsqmmbhttEEEEEEEhjjiigffffgfhttttEEEEnaacgffiijjigfd..................................',
    '.................................nooossssrqsqmlccttEEEEEtscjiggfffffffhttttEEEEnaadfffjjiiigfd..................................',
    '.................................nooossssqqtqmlhbnstttttsncjgggfffdfffhosttttsshabffffiiiiggfd..................................',
    '.................................nooossssqqtqmkhbcsstttsocgiggffdddddfdhstttsqnaacfffgigggfff...................................',
    '.................................nooossssqqtqmkjhchosqsrhdiggfffddddddfcnsqqqnbacffffgigffffh...................................',
    '.................................nooossssqstqmkkigdcmmmhfggggfffdddddddfdhmnhbccdffffggfffgf....................................',
    '.................................norossssqstqmkkjiigfffgggggggggdddddddddddccddfffffhigfggf.....................................',
    '.................................norossssqqtqmlkkjiiiiggggggggiiigffdddddddddfffffgfhjgggf......................................',
    '..................................nrossssosttmlkkkjjiiiiiiiiiiiiggffffffffffffffggghlmlmm.......................................',
    '..................................nsossssosttmmlkkkjjiiiiiiiiiiiggffffffffffffggggghtttto.......................................',
    '..................................nsorsssosttsmllkkkjjjiiiiijkjjjiiigggfgggggggggjfotttsn.......................................',
    '..................................nsrrsssqqtttqlllkkkjjjjjjijkkkkkkkgggggggggiiijfmttttr........................................',
    '..................................nrrrsssqqttttmlllkkkjjjjjjjjjjjjigiiggggiiiijjfmttttso........................................',
    '..................................nrrrsssqqtttttolllkkkkjjjjjjjiiiiiiiiiiiiijjjgmtttttso........................................',
    '..................................nrsrsssrqttttttslhlkkkkkjjjjjjjiiiiiiijjjjjglottttttrn........................................',
    '...................................osrrssrottttttttoljkkkkkkjjjjjjjjjjjjjjjglmtttttttson........................................',
    '...................................nsrrsssoststttttttomkkkkkkkjjjjjjjjjjjjlmtttttttttso.........................................',
    '....................................orrsssqo...oorsrstsqmmkkkkkjkjjjkkklmqtttsssrrtsso..........................................',
    '......................................nossso..............lmlkkkkkkkklm.rr......................................................',
    '........................................orro..............lmmmmmmlmlmll.........................................................',
    '........................................................mmmmmmmmlllllmmmm.......................................................',
    '.....................................................mmmmmmmmmmlllkkkklkkkkk....................................................',
    '...................................................mmmmmmmmmmllkkkkkkkkkkkjijg..................................................',
    '.................................................lmmmmmmmllkkkkkkkkjjjjiiiiiiggf................................................',
    '................................................llmllllkkkkkkkjjjiiiigggggffffgfd...............................................',
    '...............................................llkkkkkkkkkkjjiiiiggfffffffffddffffd.............................................',
    '..............................................hlkkkkkkkkjjiiigggffffffffffffddddfffd............................................',
    '............................................hhkkkkkkkkkjjiiggggfffffddffffffffddddffd...........................................',
    '...........................................hgkkjjjkkkkjjiiigffddddddddddfffffgffdddffd..........................................',
    '..........................................hhkjjjjjkljjjiigdcbbbaaaabbcdddffffiigfdddffd.........................................',
    '..........................................hkjjjjjkkljjiihcbbbbbaaaaaaabcdffffijigffddffd........................................',
    '.........................................hkjjjjjkklljjicbbbbbbaaaaaaaaaabdfffikjiiffddfdd.......................................',
    '........................................hjjjjjjkkmljjicbbbbbbbaaaaaaaaaaabdffgkkkjigffdfd.......................................',
    '.......................................hgkjjjjkkmmlgjcbbbbbbbaaaaaaaaaaaaabdffkkkkjigffffd......................................',
    '.......................................hjjjjjkkkmmhjhbbbbbbbbaaaaaaaaaaaaaabffilkkkjiifdffd.....................................',
    '......................................hfjiijkkkmmljhbbbbbbbbbaaaaaaaaaaaaaaacfihlkkkkifdffd.....................................',
    '......................................hiiffikkmmblhcbbbbbbbbbbaaaaaaaaaaaaaabdicallkjgfdffd.....................................',
    '......................................hjigffiklackhbbbbbbbbbbbaaaaaaaaaaaaaaacggaalkifddffd.....................................',
    '......................................hjigffgkhallcbbbbbbbbbbbaaaaaaaaaaaaaaabdiabkigfcdffd.....................................',
    '......................................hjjgfdfikhlhccbbbbbbbbbbbaaaaaaaaaaaaabbcicjkifddfffh.....................................',
    '......................................hijigfdikmkhccbbbbbbbbbbbbaaaaaaaaaaaabbcgjkigfddfgfh.....................................',
    '.......................................hkjifdfkllhccbbbbbbbbbbbbaaaaaaaaaaaabbbfkkigddffgh......................................',
    '.......................................hjjiiffkllhccbbbbbbbbbbbbbbbaaaaaaaabbbbfjkifdffgfh......................................',
    '........................................gkjiigkllhccbbbbbbbbbbbbbbbbbbbbbbbbbbbfjjgffffgh.......................................',
    '........................................hjkjjjlllhccbbbbbbbbbbbbbbbbbbbbbbbbbbbfjkgfffifh.......................................',
    '.........................................hkkjklllhccbbbbbbbbbbbbbbbbbbbbbbbbbbcfjkiggigh........................................',
    '..........................................jkklmmkhcccbbbbbbbbbbbbbbbbbbbbbbbbbcgkmkiigh.........................................',
    '..........................................lmmqsmklcccbbbbbbbbbbbbbbbbbbbbbbbbbdglommlj..........................................',
    '...........................................ososmklhccccbbbbbbbbbbbbbbbbbbbbbbcggmqnnon..........................................',
    '..........................................nosotmlkhcccccbbbbbbbbbbbbbbbbbbbbbdggmsnnon..........................................',
    '..........................................nsrrtmllkhcccccbbbbbbbbbbbbbbbbbbbdgggmsqooon.........................................',
    '..........................................nrsstmllkkhccccccbbbbbbbbbbbbbbbbdggggmsrrrn..........................................',
    '...........................................osstmllkkkhcccccccbbbbbbbbbbbbchiggiglssson..........................................',
    '............................................nrslllkkkkjhcccccccccbbbbbbcdgiiiiigkqqnn...........................................',
    '..............................................mllkkkkkkkjhhhcccccccccdhgiiiiiigggl..............................................',
    '...............................................hlkkkkkkkkkkjjjhhhhgiijjjjjjiiiggfh..............................................',
    '...............................................hlkkkkkkkkkkkkkkkkkjjjjjjjjjiigggfh..............................................',
    '...............................................gkkkkkkkkkkkkkkkkkkkkkkkkjjiigggggh..............................................',
    '..............................................hjkkjjkkkkkkkkkkkkkkkkkkkkjjiigggggd..............................................',
    '..............................................hjkjjjjjjkkkkkkkkkkkkkkkkkjiiggggggf..............................................',
    '..............................................hjkjjjjjjjkkklllllllllkkkkjiiggggggf..............................................',
    '..............................................hjkjjjjjjjkkkkl......lkkkkjiiiggggif..............................................',
    '..............................................hkkjjjiijjkkkkl.......kkkkjiiiigggif..............................................',
    '..............................................hkkjjiiiijjkkl........lkkkjjiiigggif..............................................',
    '..............................................lkkjjiiiijjkkl.........kkkjjiiiiggifd.............................................',
    '..............................................hkkjjiiiiijkk..........lkkkjiiiiggifd.............................................',
    '..............................................jkkjjiiiiijkk..........lkkkjiiiiigifd.............................................',
    '..............................................jkkjjiiiiijjk...........kkkjjiiiiiigd.............................................',
    '.............................................hjkkjjiiiiijjl...........kkkjjiiiiiigf.............................................',
    '..............................................jkjjjiiiiijj............lkkkjjigffggf.............................................',
    '.............................................hgiiigfgiiijk............lkkkjigfffffd.............................................',
    '............................................hfggggfffgiijk............lkkkiiggfffffd............................................',
    '............................................figffffffgiiij.............kkjiigffffffd............................................',
    '...........................................hgigfdddffgijig.............kkkjigffddfffd...........................................',
    '...........................................fiigfdddfggijgj.............lkkjiiffdddfff...........................................',
    '...........................................fjiigffffggiig..............lkkkjiggffffffd..........................................',
    '...........................................ijjjiiggggijij..............lkkkkjiigggggf...........................................',
    '...........................................lijjjiiiiiigg................kkkkjjiigggff...........................................',
    '...........................................mllllkkkklll.................mmmllkkkkkll............................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'E': 0xFF2E2C36,
    'a': 0xFFFAE7C7,
    'b': 0xFFF7DEAF,
    'c': 0xFFF8D683,
    'd': 0xFFF7CE66,
    'f': 0xFFFECA3E,
    'g': 0xFFFCC437,
    'h': 0xFFEBBD5E,
    'i': 0xFFF8BF2D,
    'j': 0xFFF1B528,
    'k': 0xFFE9AA22,
    'l': 0xFFD69E31,
    'm': 0xFFAF7E31,
    'n': 0xFF796252,
    'o': 0xFF6B4B30,
    'q': 0xFF664325,
    'r': 0xFF5B3F2B,
    's': 0xFF55371E,
    't': 0xFF38210E,
  },
);
