// 奶龙：黄黄圆圆的小恐龙——蛋形黄身子、奶白圆肚皮、大黑眼睛、
// 宽嘴咧笑、橙色小脸蛋，参考动画原型一比一像素化。

import 'pixel_art.dart';

const BuddyPixelArt nailongArt = BuddyPixelArt(
  rows: [
    '................................',
    '................................',
    '...........HHHHHHHHHH...........',
    '.........HHyyyyyyyyyyHS.........',
    '.........yyyyyyyyyyyyyy.........',
    '.......HHyyyyyyyyyyyyyyHS.......',
    '.......yyyyyyyyyyyyyyyyyy.......',
    '.....HHyyyyyyyyyyyyyyyyyyHS.....',
    '.....yyyyyyyyyyyyyyyyyyyyyy.....',
    '....HyyyyyyyyyyyyyyyyyyyyyyS....',
    '....yyyyyEEyyyyyyyyyyEEyyyyS....',
    '....yyyyEEEEyyyyyyyyEEEEyyyS....',
    '....yyyyEEEEyyyyyyyyEEEEyyyS....',
    '....yyyyyEEyyyyyyyyyyEEyyyyS....',
    '....yyppyyyyyyyyyyyyyyyyppyS....',
    '....yyppyyyyyyyyyyyyyyyyppyS....',
    '....yyyymmyyyyyyyyyyyymmyyyS....',
    '....yyyymmmyyyyyyyyyymmmyyyS....',
    '....yyyyymymmmmmmmmmmymyyyyy....',
    '...HyyyyyymmmmmmmmmmmmyyyyyyS...',
    '...yyyyyyywwwwwwwwwwwwyyyyyyy...',
    '..HyyyyyywwwwwwwwwwwwwwyyyyyyS..',
    '..SyyyyyywwwwwwwwwwwwwwyyyyyyS..',
    '...yyyyywwwwwwwwwwwwwwwwyyyyS...',
    '...SyyyywwwwwwwwwwwwwwwwyyyS....',
    '....yyyyywwwwwwwwwwwwwwyyyyy....',
    '....SyyyywwwwwwwwwwwwwwyyyyyHS..',
    '.....yyyyyywwwwwwwwwwyyyyyySSS..',
    '.....SyyyyyyyyyyyyyyyyyyySS.....',
    '......yyyySSSSSSSSyyyySSS.......',
    '......dddd........dddd..........',
    '.......dd..........dd...........',
  ],
  palette: {
    'y': 0xFFFFC63B,
    'd': 0xFFE59B18,
    'w': 0xFFFFF4D6,
    'm': 0xFF8C5A2B,
    'E': kBuddyEyeColor,
    'p': 0xFFF59E4A,
    'S': 0xFFD1A230,
    'H': 0xFFFFD366,
  },
);
