// 奶龙：以 Codex Pets 官方奶龙精灵图（待机第 1 帧）为参考量化的
// 64×64 高清像素版——圆头黄身、绿眼睛、鼓肚子、小手小脚小尾巴。

import 'pixel_art.dart';

const BuddyPixelArt nailongArt = BuddyPixelArt(
  rows: [
    '...........................aaaaaaaaaa...........................',
    '........................abbccdfgffffhbaa........................',
    '......................abccccggggggigiiihba......................',
    '....................abcccfffgggigggggggggjba....................',
    '...................abkclciggggiiiiiiiiigifhja...................',
    '...................bcicccggiggiiiiiiiiiiiiifja..................',
    '.................abklckcgggggiiiiiiiiiiiigggfja.................',
    '.................bklfccggggiiiiiiiiiiiiiigggifj.................',
    '.................ccfigfgggggiiiiiiiiiiigiggigiha................',
    '................bcfggggggiiiiiiiiiiiigggggggigib................',
    '................clfggggggggiiiiiiiiiiggggggiiggga...............',
    '...............acfgggggggggiiiiiiiiigggggggigggia...............',
    '...............difggiiiiggggiiiiiiiigggiiiigggggja..............',
    '...............dgfgidbbdigggigiiiiiiigifbbjiggggda..............',
    '..............affggbbkbbdigggigiiiiigifbbbbadgggfb..............',
    '..............bifibbkEEEadggiiiiiiigidbbEEkkbigggj..............',
    '..............bgghamEEbaEadigigiiiigijaEEEEmbjlggb..............',
    '..............bggbkEEamaEEjigiiiiiiifaEkbaEEkbigfha.............',
    '.............affibmEEaaaEajigiiiiigidaEaaaEEkbigfha.............',
    '.............agfgamEEaaaEEjgggiiiigidaEaaaEEkjiggfa.............',
    '.............agfgjdmEEEEEbgggggiiiiggbEEEEEkkhiggfa.............',
    '.............agggihckEEEbigggiiiiigiilbEEEbkhggggfa.............',
    '.............agfggghfdjjfggiidbbbdigggijbjcffgggifa.............',
    '.............affgggiggiigggiiaaaaadigggiigfgggggfha.............',
    '.............ajfggggggggggggdaaaaajiiiiggggggggifha.............',
    '..............bfgggggggiiiiiibababdggiiigggggggfhha.............',
    '..............ajhggggggiiiigggbabdggiiiiggggggghhb..............',
    '...............bhfgiggggigiigigdfggiiigiiigiifhhha..............',
    '...............ahjabiggggigiggiiiggggiiiggijaajhja..............',
    '..............abbaaajigggigggggiiigiiiiiighababbhj..............',
    '............ajjbjaabbbfiiggggiiiiigiiiigfbaaabdbbhj.............',
    '...........adjbcidjbaabffgiiigiiigiiigfhjaabjjgcbbfb............',
    '...........jfbcffgibaabhhfffiiiiiigffhhhjaabigffibbgb...........',
    '..........adccffgffijaajhhhhhhhhhhhhhhhhbbjgfggggghhja..........',
    '..........bglgggggggfjajhhhhhhhhhhhhhhhhabgfgggggifhha..........',
    '.........adgfggggggfhbajfgfhhhhhhhhhhhhhabggggggggifha..........',
    '.........aggggggggghhbbfggflcccccccfffgfbbfggggggggfha..........',
    '.........adgggggggfhjajffckkkmmmmmkkclgfjbjfggggggghha..........',
    '..........bggggigfhhbbhfckmmkkkkkkkmmkcfhbbhhfggggfhb...........',
    '..........ajfgfhhhhbbhfcmkkkkkkkkmkkkkmkfhbbhhhhhhhja...........',
    '...........ajhhhhjbbhhcmkkkmmmmmmmmmmkkmkfhbbjhhhhja............',
    '............abbbbbbhhcmkkkkmmmmmmmmmmmmkmchhbabbba..............',
    '..............abbjhhlkmkkkmmmmmmmmmmmmmkmklhhjbba...............',
    '..............bhhhffcmkkkmmmmmmmmmmmmmmmkmcfhhhha...............',
    '.............ajhffgfkmkkmmmmmmmmmmmmmmmmkmkgfhhhj...............',
    '.............ajffffckkkkmmmmmmmmmmmmmmmmmkmcfhhhj...............',
    '.............ajffgfcmkmmmmmmmmmmmmmmmmmmmkmkffhhja..............',
    '.............bfffglkmkkmmmmmmmmmmmmmmmmmmmmkifhhhb..............',
    '.............bffgfckmkkkmmmmmmmmmmmmmmmmkkmklfhhhb..............',
    '.............bfgfflkmkkmmmmmmmmmmmmmmmmmmkmkifhhhb..............',
    '.............bfggfckkkkkkmmmmmmmmmmmmmmkkkmkihhhhb..............',
    '.............bfgggickmkmmmmmmmmmmmmmmmmmkmkcfhhhhb..............',
    '.............jffggfckkmkmmmmmmmmmmmmmmmkmkkchhhhhb..............',
    '.............ahfgggckkkmmmmmmmmmmmmmmmkmkkklhhhhja..............',
    '.............ahhfggfcckkmmmmkmmmmmmmmmkkkkchhhhhj...............',
    '..............jhfgfgfdckkkkkmmmmmmmmkkkkkcfhhhhhj...............',
    '..............bfffffhhdkkkkkkkkkkkkkkkkkchhhhhhhb...............',
    '..............biffffghhddccckkkkkkkkccddhjfgfffha...............',
    '.............alfffggfgjjjhhhccccccccfhjjjgggggghj...............',
    '.............affgggggfhjjjjhhhhhhhhhjjjjfffgfgfhj...............',
    '.............abaddabfbajjjbaaaaaaaaabjjdabgbajbab...............',
    '..............aabaaabaaahb..........abhbaabaaabaa...............',
    '..............aaaaaaaaaaa............aaaaaaaaaaa................',
    '..................a...a.................a...a...................',
  ],
  palette: {
    'E': 0xFF3B661C,
    'a': 0xFF5F3E15,
    'b': 0xFFA9832D,
    'c': 0xFFFDDD53,
    'd': 0xFFF4C93A,
    'f': 0xFFFDD033,
    'g': 0xFFFDD536,
    'h': 0xFFFDBB21,
    'i': 0xFFFDD63C,
    'j': 0xFFE4A31C,
    'k': 0xFFFBECBB,
    'l': 0xFFFCD541,
    'm': 0xFFFCEEBF,
  },
);
