// 奶龙：以 Codex Pets 官方奶龙精灵图（待机第 1 帧）为参考量化的
// 128×128 高清像素版——圆头黄身、绿眼睛、鼓肚子、小手小脚小尾巴。

import 'pixel_art.dart';

const BuddyPixelArt nailongArt = BuddyPixelArt(
  rows: [
    '.......................................................ttttttttttttttttttttt....................................................',
    '.......................................................ssssssssssrssssssssss....................................................',
    '..................................................tssstodddfmhfffffhhkhhhnnqstttt...............................................',
    '...............................................tttoooddddfffklllllllllllloooqqqqrtt.............................................',
    '...............................................ssrdddddddkkklllllllljjljjggjhfhmqsss............................................',
    '............................................tssdddddfmmllggjjjlljjjjjjjjjjlllllfmnnrtt..........................................',
    '..........................................ttrdddddfffmkkklllkijjjjjjjjgijgggjiiilmmqrrttt.......................................',
    '.........................................tsrddddddgkkikkkkkijjjgjgjjggjggggjjjjjiglnnnrss.......................................',
    '........................................ttrddddfkkliikkkkiijjjgggggggggggjjgggjjiklfnnnnrt......................................',
    '.......................................ttrddddgmfddfmikiijjijjgggggggggggggggjgjijgjlmlnqqst....................................',
    '......................................tsrodfffffdddfkgjjgjjjgggggggggggggggggggggggggggmnnrst...................................',
    '.....................................ttrdddmmfddddmmjjjigjjjjggggggggggggggggggggggggjkgmqnqt...................................',
    '....................................ttrddffgdddddgjkkkiijjjgggggggggggggggggggggggggjjjjklnqqtt.................................',
    '...................................tsrdddfkiddddfmjiiiiihijjggggggggggggggggggggggggjjgjigmnnrs.................................',
    '..................................ttsdddmkjkdddfkjjjkiihjgggggggggggggggggggggggggggjjjijlfmqnrt................................',
    '..................................trddfggikifffgikkjjjjjjggggggggggggggggggggggggggggjjjjgjkonrt................................',
    '..................................trddfmkkigkkkikiijjjjjgggggggggggggggggggggggjjggggjjjjgghlmqs................................',
    '.................................ttrdfkkkkkkijgjijjjgggggggggggggggggggggggjggggggjgjggggggikhnnst..............................',
    '.................................soddkkkkkiilkiijjjgjggjgggggfggggggggggggggjjjjjijggjgjjjgikklost..............................',
    '.................................tddfikkkkiiiikiijjggggggggggggggfgggggggggjjjjjjiiijgjijjhiiifjrs..............................',
    '................................tsddmkkkkkiijiikjjjgjjjggggggggggggggggggggjjjjjjjjjghiigjgjihhlmrt.............................',
    '...............................trddfmkkkklkkiikkiijjjgjggggggggggggggggggggjijjjkiggiiggggghjihlfrt.............................',
    '...............................trdfkklllkkkiiiiiiijjjgjjjggggggggggggggggggjijjjiiiikiggggihhhhlfrt.............................',
    '...............................trdfkggggjjijijjjjijjjgggggggggggggggggggggjjikkiiiijijjihhhihhhlfrt.............................',
    '..............................trdfgggiiiiiijjiiiiiiigjjjgggggggggggggggggjijjijiijjjjjiiikhiiiiifqrt............................',
    '..............................todmkkkkkkihhgghhhhjijijijjjgggggggggggggggjjjhijghhhhghhhiiikkkkkgmqs............................',
    '..............................trdmmkkkkijgffgjjjlillljljgggggggggggggggggggghggljfgjgjkllkkiikkklgqs............................',
    '..............................trfmkkljhfffrssssrfokjjjjjgjggjjgggggggggjjjjhgjlfosssssqffhhhiiihlgqt............................',
    '.............................srqkmkkkkhjrrrrrrrrrlgjjjjggjggggjjgjggggjggjjihihqrrrrrrrrrjgjihjhjfors...........................',
    '............................tsmmmmkkkmkostdaaaarsollkjjigijjggjjggggggggjjjhhlfssaaaaartsommkkkkkglnrt..........................',
    '.............................solkkkilfrsbaaaEtEEstqhmkkiggggjgggggggggjgjggjfosdbEEEEaabdsrhmkkkkgonrt..........................',
    '.............................smfligffrrdaadEEttttssrhlkjggggggggggggjggggggfqrrrEEEEEEaaatrflhhjkhmnrt..........................',
    '.............................smllkjlfsraartEEEtttEtsoofggggggggggggggggggggfrtaEEEEEEtraasroffgghhmnrt..........................',
    '.............................smlmmmmhsraaEEEEaarttEEsqflhjjjjjggggggggggggkhrtsbaasttEtraarsfffhhfonrt..........................',
    '.............................smlmmkqsrbaEEEtdaarttEEsqflijjjggjggggggjjgjihrsEtbaastttEEdarsjgjhihlnqrt.........................',
    '............................srmkmmhqtbaaEEEtrbbrttsEtqhlijgggggggggggggggffssEtdbbttttEEsarsokkkkgmnnrt.........................',
    '...........................trhmkhlfqsbaaEEEtttttttsEtqfjhggggggggggggggggghssEttttttttEEsarsjfghhflnnrt.........................',
    '...........................trhmkhlfqtbaatEEtttttttEEtqfjgggggggggggggggjkkhssEttttttttEEsarsffghhhkonrt.........................',
    '...........................trhommmhqtbaasEEtttttttEEtqhkijijjgggggggjjjjljhsEEttttttttEEsarsjjkkkkklnrt.........................',
    '...........................trfokmmhqtbaatEEtttttttEEtqhkkkjggggggggggjjjgffsEEttttttttEEtaonkmkkjihlnrt.........................',
    '...........................trhokkmmoqqdadEEEtttttEssqohjiijggggggggggjjjjkkqrsEttttttEsEdaongkkihihlnrt.........................',
    '...........................trhomkmmkhqoaarEEsttttEErhmkkkijijggggggggggghilfqsEsttttsEsdaaonfkijiihlnrt.........................',
    '...........................trhlkkkkklfnnaabtEEEEEtqfokklijijigggggggggjgggfffotEEEEEEtbaaqmfkjjjiihlnrt.........................',
    '...........................trfokkkiiignnocbEsssssrogjhijgggggjggjjjjgjjjgggffoqrssssEdacommllkljiihlnrt.........................',
    '...........................trfokkkkikijlnnoorrrrrhmkklkggggjhhhhffffjjgjiiiiijfrrrrrrflmmgkkkkkiiihlnrt.........................',
    '...........................trfokkkkkkkkkfjkmhffhhmlkkijgghkfqssssssrfikkkjjkijlfffffhmmllkllkkkjhhhlnrt.........................',
    '...........................trhokkkkkkkkkllllllllljjigjgggfgqrttttttsqohjkkkkllkllllllllllllljiihhhkonrt.........................',
    '...........................trkmmkkkkiikkikkkjkiiijjijjjjjgjssssssssstqfggggjjjjlllllklkkklklkhihihmnnrt.........................',
    '...........................trnnmikiighhhiiiiggijjjjjjjkkkmmstttttttstqfjgggggggijjllkkklkkkiihhhhfmnnrt.........................',
    '............................srnlghhghhhhiiijiiiijigjjjjklkkssssssssstqhkjggggggjjjjiikkkkikiiiihhmnnnrt.........................',
    '.............................snojhijiiiihikiiiigjhjggggggffssrrrrrrrtqflijjgggggjjjjjlkkkikiiihhhnnnnrt.........................',
    '.............................snnmhhkikiiijiiiiigjjggjgggggljrtrrrrssooghjggggggggjjjjkkikiihiihknnnnmrt.........................',
    '.............................srqnmkkkikiihiihiiggggggggjjkkhqrssssrqhlkjjggggggjjjijiihjhjihhihlnnnnrst.........................',
    '..............................trnqmkkihhhhhhhiigjggggggjjjjlfjssssqfmkjjjggggjjjggigijhhhhhhhkklnnnqst..........................',
    '..............................trnqnnhkkjhgiihhiijggjjggjjgggjlooommlijggggggjgggggjjhhjhjljglnnnnnnnst..........................',
    '...............................srnnnmhfhkkiiiijijhjjjjjgjjjjijghhiijjjgggggjgjgjggjgghhkfffmnnnnnnqrt...........................',
    '...............................tsnnnnrrrhhkiikkijjjggjjggjjjggggjljjjjjjjjjgjgggjjgggggfqrrrqnnnnnrt............................',
    '...............................srnqqqsssqofjikkkiihggggjjjgggjggggjjgjijjgjggggjjjhgjglqssstsqnnnnqst...........................',
    '.............................ttrnnqtsrrrtrhmklijigjjgjjjjjjjgjggggggjggggggggggggjjkjfotrrrrstqnnnnnst..........................',
    '..........................ttsrqrssqrtrrrtrmhhhggijjggggijjjjjggggggggjggggggjhhgjgghmmqtsrrsrrsssqnqqrt.........................',
    '..........................ssrhorssortssrsrqqomkkiijgggjgjjggjggggggggjgggggggjhihlmmqqrsssssrfsssqqnmqst........................',
    '.........................tnhmmtrclfrtsssmrttrnkhhijjjjjjjggggggggggggggjgggggghhhnnqstsmstttrffcasrmnnntt.......................',
    '........................sqohqrrofmfoqrrrrrrrsrnlfhghiiiiigggggggggggjgggggghgfinnnqsrrssrqqqqhkffqrrmmoqrt......................',
    '.......................srhmorsdfmglfhnnqtsrrssnnmmmkhhhghjjjggggggggggggjhgkmmmnnmrtrrrtqhhhhkkklfrsqqmmqst.....................',
    '......................trhohsscokgkkkmokotsrrssqqnnnmfggfghjjjiijgjijgggggggknnnnnnrtsrstqkmmkkigglfotrnomqst....................',
    '......................trfomodfmmmkkkklgoqrsstsnnnnnnnnnnnjhhhhhhhhhggfmnnnnnnnnnnnqrstsqohkkkkkkkkkmrqqnlmst....................',
    '......................rqfffddmmkkkkkkkkkfrssssrqnnnnnnnnnmmmmmmmmmmmmmnnnnnnnnnnnqqqrsrhkkiikkkkkkkkmnqnllrs....................',
    '.....................sofmgdfmjkkkkkkkkkkmhlnrssqnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnssrohhmmkkkkihikkkkfmnnmlmrt...................',
    '.....................sokmkffkikkkkkkkhhkhmnnrssrnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnssrommkkkkkkiihhhikhmnnnnnrt...................',
    '.....................sogmkmkkkkkkkiihhhhhnnnrstrnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnssromkklkkkjkiiiihhiglnnnnrt...................',
    '...................tsrfmmmkkkikhhhhiihkkhnnnrstrnnmmkknnnnnnnnnnnnnnnnnnnnnnnnnnnssrqmjijjhhiiihiiiikkllnnnrt...................',
    '...................trffmmkkkkiihihhihhhknnqnssrqnmmkkimmmmmmmmmmmmmmmmmmmmmmnnnnnrrsqlfhiiiiihihhhjjkklhnnnrt...................',
    '...................trhokkkkkkkkkkkkhhhhknnnnssnnmhkkkkhhkmkkkkiggffgggkkkjkkkkhknnrsqmkkkkkiihhhihhhiikinnnrt...................',
    '...................trflhihikkkkkkkkkkkkmnnnmssnnmhkhkmmfdddddddcccccccfmmmmkkkkknnrtqnnhkkkiihhhiihikikfnnnrt...................',
    '...................trflkkkkiihihhkhkhhmnnnqrrqnmlikmfdddcdccccccbbbbccddddfmkkkkmnqrrqnmggihhhhhiihhihkmnnnrt...................',
    '...................trommkkkhhhhhhhhhkhmnnnqtqnnmklghdabbccccccccccccccbabadfffhkknnnsrnnlikkkhhhhhhhhhknnnqrt...................',
    '.....................sohmkigghhhhhhhhnnnnnqtrnqmmmmdbccccccccccccccccccccbccbfmmknqqsrnqnnhkkkkkkkkhhhknnqst....................',
    '.....................sqmmkihghhhhfmnmnnnnrsrqnnmfddcbcbccccccbcccccccccccccccddfmnnqrrrnnnnnmhkhhkhhmmmnnnst....................',
    '.....................tqnmkkhkkmmmlnnnnnnqrsnnnimdbcccccccccccccccccccccbcbcccbacfflnmrsqnnnnnkmmmkkmnnnnqqst....................',
    '......................trmnmhhhnnnnnnnnnqtrnnnnkccccccccccccccccccbbbbbbbbcccccccafmmnnqtqnqnnnnnnnnnnnnnrt......................',
    '.......................srnnnnnnnnnnnnnrsrqnnnldccccccbccbbbbccccbbbbbbbbbbbccccccdfmnnqrrrnnnnnnnnnnnnnrs.......................',
    '.......................tsqqqnnnnnnnqqqrsnnnnldcccccbccbbbbbbbbbbbbbbbbbbbbbbbbbbcadfmnnmrsqqqnnnnnnnqqqs........................',
    '........................tstrmnnnnnmrttrnqnnkdcccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbccbfnnnnqstrnnnnnnqstt.........................',
    '...........................ssssssssrqqqnnmlkcbccccccccccbbbbbbbbbbbbbbbbbbbbbbbcccccmmnnnqrrrssssrss............................',
    '............................ttsssssrnnnnnmffcaccccccbbbcbbbbbbbbbbbbbbbbbbbbbbbbbcccfflnnnnnqssssstt............................',
    '.............................tqnnnnnnnnnmmfacccccccbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcadmknnnnnnnnnrt.............................',
    '.............................tqnnnnnnmmmmfdccccccccbcbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbcadnmmnnnnnnqnst.............................',
    '............................tsqnnnnnnkkkmdccccccccbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbadfkgmnnnnnnnrs.............................',
    '............................sqnnnkkkkkklmdaccccccbbbbbbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbacllllnnnnnnnrt............................',
    '............................sqnmmmmmkkkkmdbcccccbbbbbbbbbbbbbbbbbbbbabbbbaaabbbbbcbbcbcmkllnnnnnnnqt............................',
    '............................sqnmkmklkkkifdccccccbbbbbbbbbbbbbbbbbbbbbbbaaabbabbbbbbbbbcdfllnnnnnnnrt............................',
    '............................sqnmkkkkkkmfbcccbbcbbbbbbbbbbbbbbbbbbbbbbabbabbbabbbbbbcccbafllinnnnnnrt............................',
    '............................tqnmkkkkkjkfcccbcbbbbbbbbbbbbbbbbbbbabbbbbbbbababbbbbbbbbcbcfklknnnnnnrt............................',
    '..........................tsrqnmkkkkkgkfccccccbbbbbbbbbbbbbbbbbbbbbbbbaabbbbbbbbbbbbbcccdmmknnnnnnqrs...........................',
    '..........................trnnhkkkkkkkgfccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcdlmknnnnnnnnst..........................',
    '..........................trnnmmkkkklkfdcccbccccbbbbbbbbbbbbbbbbbbbbbbbbbbabbbbbbbbbbbbbdfmjnnnnnnnqst..........................',
    '..........................trnnkmlkklgkddcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcdfkgnnnnnnnqst..........................',
    '..........................trnnkkkkkklkfdccccbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcdlkgnnnnnnnqst..........................',
    '..........................trnnhkkkkkkmfdcccbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdlkgnnnnnnnnst..........................',
    '..........................trnnhkkkkkkmfdcccbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdlkgnnnnnnnqst..........................',
    '..........................trnnhkkkkkjkfdccccbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbbbbdlkgnnnnnnnqst..........................',
    '..........................trnnkkkkkkikdddcbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcbbbddfknnnnnnnnqst..........................',
    '..........................trnnhkkkiiikfddcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccddfmnnnnnnnnqst..........................',
    '..........................trnnhkkkikhgkfdddbcbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcdddmmnnnnnnnnqst..........................',
    '..........................trnnhkkkkkkkkfdddacbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbdddlmmnnnnnnnnqst..........................',
    '..........................trnnmmkkkkighfdddcbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccdddmmnnnnnnnnnqst..........................',
    '..........................trnnnmkkkkkihfddddccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbccbccccddddmnnnnnnnnnnqst..........................',
    '...........................ssqnmhkkkkkklkdddddabbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccddddmgmnnnnnnnnrs............................',
    '............................sqnnmikkkkkkmfddddcccabcbbbbbbbbbbbbbbbbbbbbbbbbccccdddddddmmnnnnnnnnnrt............................',
    '...........................tsqnnnjkkkkkklmfdddddcaccccbbbbbbbbbbbbbbbbbbbbbcccccddddddfmnnnnnnnnnnrt............................',
    '...........................tsnnnnnmkkklklflndddddddcabbbccccbbbbbbbbbbbbbaaaaddddddddfmnnnnnnnnnnnrt............................',
    '............................trnnnnmkkkkkjmnnofdddddddddcabbbbbbbbbbbbbbabccdddddddddonnnnnnnnnnnnnrt............................',
    '.............................snnnkkkkllkjnnnnoddddddddddcccccccccccccccccdddddddddddnnnnnnnnnnnnnnrt............................',
    '.............................sqmlmkkkkkkmkmnnnnddddddddddddddddddddddddddddddddddonnnnnmmkmnnnnnnrt.............................',
    '.............................sffmmmkmkkkkklmnnoofffddddddddddddddddddddddddddfooooqqnmmkkkkmmmnnnst.............................',
    '............................trdfmmmmkkkkkklfnqnnnnnfdddddddddddddddddddddddddnnnnnqqnkkmmkkkhjnnnrt.............................',
    '...........................trdmmmmmmkkkkkkkkhnqnnnnnnnnnoddddddddddddddddonnnnnnnqqfkkkkkkkkkkimnnrt............................',
    '...........................tsfmmkkmkkkkkkkkkknqqqqqnnnnnnoooooooooooooooonnnqqqqqqnmmkkkkkkikkhmnnrt............................',
    '...........................trhommmmmkkkkkkkkmmnqqqqqnnnnnnnnnnnnnnnnnnnnnnnnqqqqqnmmmkkkkkkihkjmqnrt............................',
    '...........................trkmmmmkkkhfhmmmmmmmmqqqqqqqnnnnnnnnnnnnnnnnnnqqqqqqqghhhmmmmhhhmmmhmnnrt............................',
    '...........................trmrsrhffkrrrmmmmrssnmqqqqqrssrrssssssssrrrsssqqqqqqnhrrrmhlhrsrqhmrrrnrt............................',
    '...........................tsqsssqooqstsqnnqsssronqqqqrttttttttttttttttttrrqqqqmqsssqooqrssroosssqrt............................',
    '...........................tssrrrsqrtrrrtqqtrrrsrmqqqtt..................tsqqqqqtrrrtrmtrrrsrfrrrstt............................',
    '............................ttsrstqrtrrstqqtrrrtrqqrs.....................tsqqqqtsrstrnssrrsrnrrsst.............................',
    '.............................tssstrrtrrssrrtssstsrrst......................trrrrtssstrqtssrssrssst..............................',
    '..............................tttstssrrsssssssssttt.........................tttsssrsttttssstttttt...............................',
    '.....................................sss....tsst.................................sss....tsst....................................',
    '.....................................ttt....ttt..................................ttt.....tt.....................................',
  ],
  palette: {
    'E': 0xFF3B661C,
    'a': 0xFFFCEFC3,
    'b': 0xFFFBEDBF,
    'c': 0xFFFCEDB9,
    'd': 0xFFFBDE90,
    'f': 0xFFFDD83D,
    'g': 0xFFFDD63A,
    'h': 0xFFFDD737,
    'i': 0xFFFDD537,
    'j': 0xFFFCD538,
    'k': 0xFFFDD436,
    'l': 0xFFFDD238,
    'm': 0xFFFDCF2D,
    'n': 0xFFFDB921,
    'o': 0xFFF4C639,
    'q': 0xFFE9A419,
    'r': 0xFF906C22,
    's': 0xFF5A3311,
    't': 0xFF211116,
  },
);
