// 电子宠物像素图：章鱼：紫色圆头 + 波浪触手。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt octopusArt = BuddyPixelArt(
  rows: [
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '...................HHHHHHHHHHHHHHHHHHHHHHHHHH...................',
    '.................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.................',
    '...............HHHHbbbbbbbbbbbbbbbbbbbbbbbbbbHHHS...............',
    '..............HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHSS..............',
    '..............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..............',
    '..............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..............',
    '...........HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHS...........',
    '..........HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHSS..........',
    '..........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..........',
    '..........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..........',
    '.........HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS.........',
    '........HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbSS........',
    '........bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS........',
    '........bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS........',
    '........bbbbbbbbEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEbbbbbbSS........',
    '........bbbbbbbbEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEbbbbbbSS........',
    '........bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS........',
    '........bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS........',
    '........bbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbppbbbbbbbbbbbbbbmmmmmmbbbbbbbbbbbbbbppbbbSS........',
    '........bbbbpppppbbbbbbbbbbbmmmmmmmmbbbbbbbbbbbpppppbbSS........',
    '........bbbbpppppbbbbbbbbbbbmmmmmmmmbbbbbbbbbbbpppppbbSS........',
    '........bbbbpppppppbbbbbbbbbbmmmmmmbbbbbbbbbbpppppppbbSS........',
    '........bbbbpppppppbbbbbbbbbbbbbbbbbbbbbbbbbbpppppppbbSS........',
    '........bbbbbpppppppbbbbbbbbbbbbbbbbbbbbbbbbpppppppbbbSS........',
    '........bbbbbpppppppbbbbbbbbbbbbbbbbbbbbbbbbpppppppbbbSS........',
    '........bbbbbbbppppbbbbbbbbbbbbbbbbbbbbbbbbbbppppbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS........',
    '........bbbbbSSbbbbbbbbbbSSbbbbbbbbbbSSbbbbbbbbbbSSbbbSS........',
    '........bbbSSSSSbbbbbbbSSSSSbbbbbbbSSSSSbbbbbbbSSSSSbbSS........',
    '........bbbSS...bbbbbbbSS...bbbbbbbSS...bbbbbbbSS...bbSS........',
    '........bbSS....bbbbbbSS....bbbbbbSS....bbbbbbSS....bbSS........',
    '........bbSS....bbbbbbSS....bbbbbbSS....bbbbbbSS....bbSS........',
    '........bbSS....bbbbbbSS....bbbbbbSS....bbbbbbSS....bbSS........',
    '........bbSS....bbbbbbSS....bbbbbbSS....bbbbbbSS....bbSS........',
    '........bbSS....bbbbbbSS....bbbbbbSS....bbbbbbSS....bbSS........',
    '........bbSS....bbbbbbSS....bbbbbbSS....bbbbbbSS....bbSS........',
    '........bbSS....bbbbbbSS....bbbbbbSS....bbbbbbSS....bbSS........',
    '.....dddbbSS....dbbbbbSS....dbbbbbSS....dbbbbbSS....dddd........',
    '....ddddbSS......ddbbSS......ddbbSS......ddbbSS.....dddd........',
    '....ddddSSS......dddSSS......dddSSS......dddSSS.....dddd........',
    '.....dddS..........dS..........dS..........dS........dd.........',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'b': 0xFFB08AD9,
    'd': 0xFF8A63B8,
    'm': 0xFF6E4C99,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF9071B2,
    'H': 0xFFC1A4E1,
  },
);
