// 电子宠物像素图：章鱼：紫色圆头 + 波浪触手。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt octopusArt = BuddyPixelArt(
  rows: [
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '.......................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.......................................',
    '.....................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.....................................',
    '...................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...................................',
    '.................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.................................',
    '...............................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHHS...............................',
    '.............................HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHSSS.............................',
    '.............................HHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHSSS.............................',
    '............................HHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHSSSS............................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '.......................HHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHS.......................',
    '.....................HHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHSSS.....................',
    '.....................HHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHSSS.....................',
    '....................HHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHSSSS....................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....................',
    '....................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....................',
    '...................HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...................',
    '.................HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.................',
    '.................HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.................',
    '................HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppbbbbbbbSSSS................',
    '................bbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbSSSS................',
    '................bbbbbbbbbppppppppbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbppppppppbbbbbSSSS................',
    '................bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbSSSS................',
    '................bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbSSSS................',
    '................bbbbbbbbpppppppppppbbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbpppppppppppbbbbSSSS................',
    '................bbbbbbbbpppppppppppppbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbpppppppppppppbbbbSSSS................',
    '................bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS................',
    '................bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS................',
    '................bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbSSSS................',
    '................bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbSSSS................',
    '................bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbSSSS................',
    '................bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbbbSSSS................',
    '................bbbbbbbbbbbppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................',
    '................bbbbbbbbbbbSSbbbbbbbbbbbbbbbbbbbbbbSSbbbbbbbbbbbbbbbbbbbbbbSSbbbbbbbbbbbbbbbbbbbbbbSSbbbbbbbSSSS................',
    '................bbbbbbbbbSSSSSSbbbbbbbbbbbbbbbbbbSSSSSSbbbbbbbbbbbbbbbbbbSSSSSSbbbbbbbbbbbbbbbbbbSSSSSSbbbbbSSSS................',
    '................bbbbbbbSSSSSSSSbbbbbbbbbbbbbbbbSSSSSSSSbbbbbbbbbbbbbbbbSSSSSSSSbbbbbbbbbbbbbbbbSSSSSSSSbbbbbSSSS................',
    '................bbbbbbSSSSSSSSSSbbbbbbbbbbbbbbSSSSSSSSSSbbbbbbbbbbbbbbSSSSSSSSSSbbbbbbbbbbbbbbSSSSSSSSSSbbbbSSSS................',
    '................bbbbbbSSSSS.....bbbbbbbbbbbbbbSSSSS.....bbbbbbbbbbbbbbSSSSS.....bbbbbbbbbbbbbbSSSSS.....bbbbSSSS................',
    '................bbbbbSSSS.......bbbbbbbbbbbbbSSSS.......bbbbbbbbbbbbbSSSS.......bbbbbbbbbbbbbSSSS.......bbbbSSSS................',
    '................bbbbbSSSS.......bbbbbbbbbbbbbSSSS.......bbbbbbbbbbbbbSSSS.......bbbbbbbbbbbbbSSSS.......bbbbSSSS................',
    '................bbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbSSSS................',
    '................bbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbSSSS................',
    '................bbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbSSSS................',
    '................bbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbSSSS................',
    '................bbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbSSSS................',
    '................bbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbSSSS................',
    '................bbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbSSSS................',
    '................bbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbSSSS................',
    '................bbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbSSSS................',
    '................bbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbSSSS................',
    '................bbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbSSSS................',
    '................bbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbSSSS................',
    '................bbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbbbbbbbbbSSSS........bbbbSSSS................',
    '...........dddddbbbbSSSS........dbbbbbbbbbbbSSSS........dbbbbbbbbbbbSSSS........dbbbbbbbbbbbSSSS........dddddddd................',
    '.........dddddddbbbSSSS..........ddbbbbbbbbSSSS..........ddbbbbbbbbSSSS..........ddbbbbbbbbSSSS.........dddddddd................',
    '.........dddddddbbbSSSS..........ddddbbbbbbSSSS..........ddddbbbbbbSSSS..........ddddbbbbbbSSSS.........dddddddd................',
    '........ddddddddbSSSSS............dddddbbSSSSS............dddddbbSSSSS............dddddbbSSSSS..........dddddddd................',
    '........ddddddddSSSSSS............ddddddSSSSSS............ddddddSSSSSS............ddddddSSSSSS..........dddddddd................',
    '.........dddddddSSSSS..............dddddSSSSS..............dddddSSSSS..............dddddSSSSS............dddddd.................',
    '.........dddddddSSS..................dddSSS..................dddSSS..................dddSSS..............dddddd.................',
    '...........dddddS......................dS......................dS......................dS..................dd...................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'b': 0xFFB08AD9,
    'd': 0xFF8A63B8,
    'm': 0xFF6E4C99,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF9071B2,
    'H': 0xFFC1A4E1,
  },
);
