// 电子宠物像素图：章鱼：紫色圆头 + 波浪触手。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt octopusArt = BuddyPixelArt(
  rows: [
    '................................',
    '................................',
    '................................',
    '................................',
    '.........HHHHHHHHHHHHHH.........',
    '.......HHbbbbbbbbbbbbbbHS.......',
    '.......bbbbbbbbbbbbbbbbbb.......',
    '.....HHbbbbbbbbbbbbbbbbbbHS.....',
    '.....bbbbbbbbbbbbbbbbbbbbbb.....',
    '....HbbbbbbbbbbbbbbbbbbbbbbS....',
    '....bbbbbEEbbbbbbbbbbEEbbbbS....',
    '....bbbbEEEEbbbbbbbbEEEEbbbS....',
    '....bbbbEEEEbbbbbbbbEEEEbbbS....',
    '....bbbbbEEbbbbbbbbbbEEbbbbS....',
    '....bbbbbbbbbbbbbbbbbbbbbbbS....',
    '....bbbbbbbbbbbbbbbbbbbbbbbS....',
    '....bbppbbbbbbmmmmbbbbbbppbS....',
    '....bbpppbbbbbmmmmbbbbbpppbS....',
    '....bbppppbbbbbbbbbbbbppppbS....',
    '....bbbpppbbbbbbbbbbbbpppbbS....',
    '....bbbbbbbbbbbbbbbbbbbbbbbS....',
    '....bbbbbbbbbbbbbbbbbbbbbbbS....',
    '....bbbbbbbbbbbbbbbbbbbbbbbS....',
    '....bbSSbbbbSSbbbbSSbbbbSSbS....',
    '....bS..bbbS..bbbS..bbbS..bS....',
    '....bS..bbbS..bbbS..bbbS..bS....',
    '....bS..bbbS..bbbS..bbbS..bS....',
    '....bS..bbbS..bbbS..bbbS..bS....',
    '..ddbS..dbbS..dbbS..dbbS..dd....',
    '..ddS....dS....dS....dS...dd....',
    '................................',
    '................................',
  ],
  palette: {
    'b': 0xFFB08AD9,
    'd': 0xFF8A63B8,
    'm': 0xFF6E4C99,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF9071B2,
    'H': 0xFFC1A4E1,
  },
);
