// 电子宠物像素图：猫头鹰：棕色 + 大眼圈 + 耳羽。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt owlArt = BuddyPixelArt(
  rows: [
    '..................HHHH....................................................................HHSS..................................',
    '.................HHHHHH..................................................................HHHSSS.................................',
    '.................HHHHHH................................................................HHHHHSSS.................................',
    '................HHHHHHHH..............................................................HHHHHHSSSS................................',
    '................bbbbbbbbS.............................................................HHHHHbSSSS................................',
    '................bbbbbbbbbSS..........................................................HHHHbbbSSSS................................',
    '................bbbbbbbbbSS..........................................................HHbbbbbSSSS................................',
    '................bbbbbbbbbbbS........................................................HbbbbbbbSSSS................................',
    '................bbbbbbbbbbbb........................................................bbbbbbbbSSSS................................',
    '................bbbbbbbbbbbb........................................................bbbbbbbbSSSS................................',
    '................bbbbbbbbbbbb........................................................bbbbbbbbSSSS................................',
    '................bbbbbbbbbbbb........................................................bbbbbbbbSSSS................................',
    '................bbbbbbbbbbbbHHHHH..............................................HHHHHbbbbbbbbSSSS................................',
    '................bbbbbbbbbbbbbHHHHHH..........................................HHHHHHbbbbbbbbbbSSS................................',
    '................bbbbbbbbbbbbbHHHHHHHH......................................HHHHHHHHbbbbbbbbbbSSS................................',
    '................bbbbbbbbbbbbbbbHHHHHHHH..................................HHHHHHHHbbbbbbbbbbbbbbS................................',
    '................bbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbbbbbbbb................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbbbbbbbbbb................................',
    '...............HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...............................',
    '.............HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............................',
    '.............HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............................',
    '............HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS............................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............................',
    '...........HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...........................',
    '.........HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.........................',
    '.........HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.........................',
    '........HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbwwwwwwwwwwwwwwwwwwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbwwwwwwwwwwwwwwwwwwbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwbbbbbbbbbbbbbbbbbbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbbbbbbbbbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbbSSSS........................',
    '........bbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbbbbbbbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbSSSS........................',
    '........bbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbbbbbbbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbSSSS........................',
    '........bbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbbbbbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbSSSS........................',
    '........bbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbbbbbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwwwwwwwEEwwwwwwwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwwwwwwwEEwwwwwwwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwwwwwEEEEEEwwwwwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwwwwwEEEEEEwwwwwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwwwEEEEEEEEEEwwwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwwwEEEEEEEEEEwwwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwwwEEEEEEEEEEwwwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwwwEEEEEEEEEEwwwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwwwwwEEEEEEwwwwwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwwwwwEEEEEEwwwwwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwwwwwwwEEwwwwwwwwwwwwwwwbbbbbbbbbbbbbbbbwwwwwwwwwwwwwwwEEwwwwwwwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooowwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbSSSS........................',
    '........bbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooowwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbSSSS........................',
    '........bbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooowwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbSSSS........................',
    '........bbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooowwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbSSSS........................',
    '........bbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooowwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbSSSS........................',
    '........bbbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooowwwwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooowwwwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbwwwwwwwwwwwwwwwwwwwwwwwwwoooooooooooooooowwwwwwwwwwwwwwwwwwwwwwwwwbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboobbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '........bbbbbbbbbbbppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppbbbbbbbSSSS........................',
    '........bbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbSSSS........................',
    '........bbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbSSSS........................',
    '........bbbbbbbbppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppbbbbSSSS........................',
    '........bbbbbbbbppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppbbbbSSSS........................',
    '........bbbbbbbbppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppbbbbSSSS........................',
    '........bbbbbbbbppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppbbbbSSSS........................',
    '........bbbbbbbbppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppbbbbSSSS........................',
    '........bbbbbbbbpppppppplbbbbbbbbbbbbbbbbbbllbbbbbbbbbbbbbbllbbbbbbbbbbbbbbllbbbbbbbbbbbppppppppbbbbSSSS........................',
    '........bbbbbbbbbppppppplllbbbbbbbbbbbbbbllllllbbbbbbbbbbllllllbbbbbbbbbbllllllbbbbbbbbbppppppppbbbbSSSS........................',
    '........bbbbbbbbbppppppplllllbbbbbbbbbbbbllllllbbbbbbbbbbllllllbbbbbbbbbbllllllbbbbbbbbbppppppppbbbbSSSS........................',
    '........bbbbbbbbbbppppppllllllbbbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbppppppppbbbbSSSS........................',
    '........bbbbbbbbbbppppppllllllbbbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbppppppppbbbbSSSS........................',
    '........bbbbbbbbbbbppppplllllllbbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbbppppppbbbbbSSSS........................',
    '........bbbbbbbbbbbbbppplllllllbbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbbppppppbbbbbSSSS........................',
    '........bbbbbbbbbbbbbbbpllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbbbbppbbbbbbbSSSS........................',
    '........SbbbbbbbbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbbbbbbbbbbbbbSSSS........................',
    '.........SSbbbbbbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbbbbbbbbbbbbSSSS.........................',
    '.........SSbbbbbbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbbbbbbbbbbbbSSSS.........................',
    '...........SbbbbbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbbbbbbbbbbbSSSS..........................',
    '............bbbbbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbllllllllbbbbbbbbbbbbbbbbbbSSSS..........................',
    '............bbbbbbbbbbbbbllllllbbbbbbbbbbllllllbbbbbbbbbbllllllbbbbbbbbbbllllllbbbbbbbbbbbbbbbbbbSSSS...........................',
    '............bbbbbbbbbbbbbllllllbbbbbbbbbbllllllbbbbbbbbbbllllllbbbbbbbbbbllllllbbbbbbbbbbbbbbbbbbSSSS...........................',
    '............bbbbbbbbbbbbbbbllbbbbbbbbbbbbbbllbbbbbbbbbbbbbbllbbbbbbbbbbbbbbllbbbbbbbbbbbbbbbbbbbSSSS............................',
    '............SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS............................',
    '.............SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.............................',
    '.............SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.............................',
    '...............SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..............................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..............................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...............................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...............................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................',
    '................SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS................................',
    '.................SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.................................',
    '.................SSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.................................',
    '..................SSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS..................................',
    '..................SSSSSSSSSSSbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbbbbbbbbbbSSSS..................................',
    '...................SSSSSSSSSSSSbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbbbbbbbSSSS...................................',
    '.....................SSSSSSSSSSbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbbbbbbbSS.....................................',
    '.......................SSSSSSSSSbbbbbbbbbbbbbbbbSSSSSSSSSSSSSSSSSSSSSSSSbbbbbbbbbbbbbbbbS.......................................',
    '................................oooooooooooooooo........................oooooooooooooooo........................................',
    '.................................oooooooooooooo..........................oooooooooooooo.........................................',
    '.................................oooooooooooooo..........................oooooooooooooo.........................................',
    '..................................oooooooooooo............................oooooooooooo..........................................',
    '..................................oooooooooooo............................oooooooooooo..........................................',
    '...................................oooooooooo..............................oooooooooo...........................................',
    '.....................................oooooo..................................oooooo.............................................',
    '.......................................oo......................................oo...............................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'b': 0xFFA9825F,
    'l': 0xFFC7A37E,
    'w': 0xFFF3EAD9,
    'o': 0xFFE8A13C,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF8B6B4E,
    'H': 0xFFBC9E82,
  },
);
