// 电子宠物像素图：猫头鹰：棕色 + 大眼圈 + 耳羽。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt owlArt = BuddyPixelArt(
  rows: [
    '.........HH..................................HS.................',
    '........HHHH...............................HHHSS................',
    '........bbbbS..............................HHbSS................',
    '........bbbbbS............................HbbbSS................',
    '........bbbbbb............................bbbbSS................',
    '........bbbbbb............................bbbbSS................',
    '........bbbbbbHHH......................HHHbbbbSS................',
    '........bbbbbbbHHHH..................HHHHbbbbbbS................',
    '........bbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbb................',
    '........bbbbbbbbbbbHHHHHHHHHHHHHHHHHHbbbbbbbbbbb................',
    '.......HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...............',
    '......HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS..............',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..............',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..............',
    '.....HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS.............',
    '....HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS............',
    '....bbbbbbbwwwwwwwwwwbbbbbbbbbbbbbbwwwwwwwwwwbbbbbSS............',
    '....bbbbbwwwwwwwwwwwwwwbbbbbbbbbbwwwwwwwwwwwwwwbbbSS............',
    '....bbbbbwwwwwwwwwwwwwwbbbbbbbbbbwwwwwwwwwwwwwwbbbSS............',
    '....bbbbwwwwwwwwwwwwwwwwbbbbbbbbwwwwwwwwwwwwwwwwbbSS............',
    '....bbbbwwwwwwwEEwwwwwwwbbbbbbbbwwwwwwwEEwwwwwwwbbSS............',
    '....bbbbwwwwwEEEEEEwwwwwbbbbbbbbwwwwwEEEEEEwwwwwbbSS............',
    '....bbbbwwwwwEEEEEEwwwwwbbbbbbbbwwwwwEEEEEEwwwwwbbSS............',
    '....bbbbwwwwEEEEEEEEwwwwbbbbbbbbwwwwEEEEEEEEwwwwbbSS............',
    '....bbbbwwwwEEEEEEEEwwwwbbbbbbbbwwwwEEEEEEEEwwwwbbSS............',
    '....bbbbwwwwwEEEEEEwwwwwbbbbbbbbwwwwwEEEEEEwwwwwbbSS............',
    '....bbbbwwwwwEEEEEEwwwwwbbbbbbbbwwwwwEEEEEEwwwwwbbSS............',
    '....bbbbwwwwwwwEEwwwwwwwbbbbbbbbwwwwwwwEEwwwwwwwbbSS............',
    '....bbbbwwwwwwwwwwwwwwwwoooooooowwwwwwwwwwwwwwwwbbSS............',
    '....bbbbbwwwwwwwwwwwwwwwoooooooowwwwwwwwwwwwwwwbbbSS............',
    '....bbbbbwwwwwwwwwwwwwwwoooooooowwwwwwwwwwwwwwwbbbSS............',
    '....bbbbbbbwwwwwwwwwwwwwoooooooowwwwwwwwwwwwwbbbbbSS............',
    '....bbbbbbbbbbbbbbbbbbbboooooooobbbbbbbbbbbbbbbbbbSS............',
    '....bbbbbbbbbbbbbbbbbbbbboooooobbbbbbbbbbbbbbbbbbbSS............',
    '....bbbbbbbbbbbbbbbbbbbbboooooobbbbbbbbbbbbbbbbbbbSS............',
    '....bbbbbbbbbbbbbbbbbbbbbbboobbbbbbbbbbbbbbbbbbbbbSS............',
    '....bbbbbppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppbbbSS............',
    '....bbbbppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppbbSS............',
    '....bbbbppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppbbSS............',
    '....bbbbppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppbbSS............',
    '....bbbbpppplbbbbbbbbllbbbbbbllbbbbbbllbbbbbppppbbSS............',
    '....bbbbbppplllbbbbbllllbbbbllllbbbbllllbbbbppppbbSS............',
    '....bbbbbppplllbbbbbllllbbbbllllbbbbllllbbbbppppbbSS............',
    '....bbbbbbbpllllbbbbllllbbbbllllbbbbllllbbbbbppbbbSS............',
    '....SbbbbbbbllllbbbbllllbbbbllllbbbbllllbbbbbbbbbbSS............',
    '.....SbbbbbbllllbbbbllllbbbbllllbbbbllllbbbbbbbbbSS.............',
    '......bbbbbbllllbbbbllllbbbbllllbbbbllllbbbbbbbbbSS.............',
    '......bbbbbbbllbbbbbbllbbbbbbllbbbbbbllbbbbbbbbbSS..............',
    '......SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS..............',
    '.......SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS...............',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS...............',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS................',
    '........SbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS................',
    '.........SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.................',
    '.........SSSSSSbbbbbbbbbbSSSSSSSSSSbbbbbbbbbbSS.................',
    '...........SSSSSbbbbbbbbSSSSSSSSSSSSbbbbbbbbS...................',
    '................oooooooo............oooooooo....................',
    '.................oooooo..............oooooo.....................',
    '.................oooooo..............oooooo.....................',
    '...................oo..................oo.......................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'b': 0xFFA9825F,
    'l': 0xFFC7A37E,
    'w': 0xFFF3EAD9,
    'o': 0xFFE8A13C,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF8B6B4E,
    'H': 0xFFBC9E82,
  },
);
