// 电子宠物像素图：企鹅：黑背白肚 + 橙脚。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt penguinArt = BuddyPixelArt(
  rows: [
    '................................',
    '................................',
    '.........HHHHHHHHHHHHHH.........',
    '.......HHkkkkkkkkkkkkkkHS.......',
    '.......kkkkkkkkkkkkkkkkkk.......',
    '.....HHkkkkkkkkkkkkkkkkkkHS.....',
    '.....kkkkkkkkkkkkkkkkkkkkkk.....',
    '....HkkkkkkkkkkkkkkkkkkkkkkS....',
    '....kkkkkEEkkkkkkkkkkEEkkkkS....',
    '....kkkkEEEEkkkkkkkkEEEEkkkS....',
    '....kkkkEEEEkkkkkkkkEEEEkkkS....',
    '....kkkkkEEkkkkkkkkkkEEkkkkS....',
    '....kkkkkkkkkkkooookkkkkkkkS....',
    '....kkkkkkkkkkooooookkkkkkkS....',
    '....kkppkkkwwwwwwwwwwkkkppkS....',
    '....kkpppkwwwwwwwwwwwwkpppkS....',
    '....kkppppwwwwwwwwwwwwppppkS....',
    '....kkkppwwwwwwwwwwwwwwppkkS....',
    '....kkkkwwwwwwwwwwwwwwwwkkkS....',
    '....kkkkwwwwwwwwwwwwwwwwkkkS....',
    '....kkkkwwwwwwwwwwwwwwwwkkkS....',
    '....kkkkwwwwwwwwwwwwwwwwkkkS....',
    '....kkkkwwwwwwwwwwwwwwwwkkkS....',
    '....kkkkkwwwwwwwwwwwwwwkkkkS....',
    '....SkkkkwwwwwwwwwwwwwwkkkkS....',
    '.....kkkkkkwwwwwwwwwwkkkkkS.....',
    '.....SSkkkkkkkkkkkkkkkkkkSS.....',
    '.......SkkkkSSSSSSSSkkkkS.......',
    '........oooo........oooo........',
    '.........oo..........oo.........',
    '................................',
    '................................',
  ],
  palette: {
    'k': 0xFF3A4454,
    'w': 0xFFF2F4F5,
    'o': 0xFFF08C2E,
    'E': 0xFFF2F4F5,
    'p': kBuddyBlushColor,
    'S': 0xFF303845,
    'H': 0xFF656D7A,
  },
);
