// 电子宠物像素图：企鹅：黑背白肚 + 橙脚。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt penguinArt = BuddyPixelArt(
  rows: [
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '...................HHHHHHHHHHHHHHHHHHHHHHHHHH...................',
    '.................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.................',
    '...............HHHHkkkkkkkkkkkkkkkkkkkkkkkkkkHHHS...............',
    '..............HHHkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkHSS..............',
    '..............kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..............',
    '..............kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..............',
    '...........HHHkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkHHS...........',
    '..........HHHkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkHSS..........',
    '..........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..........',
    '..........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..........',
    '.........HkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkS.........',
    '........HkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSS........',
    '........kkkkkkkkkkkEEkkkkkkkkkkkkkkkkkkkkkkEEkkkkkkkkkSS........',
    '........kkkkkkkkkEEEEEEkkkkkkkkkkkkkkkkkkEEEEEEkkkkkkkSS........',
    '........kkkkkkkkkEEEEEEkkkkkkkkkkkkkkkkkkEEEEEEkkkkkkkSS........',
    '........kkkkkkkkEEEEEEEEkkkkkkkkkkkkkkkkEEEEEEEEkkkkkkSS........',
    '........kkkkkkkkEEEEEEEEkkkkkkkkkkkkkkkkEEEEEEEEkkkkkkSS........',
    '........kkkkkkkkkEEEEEEkkkkkkkkkkkkkkkkkkEEEEEEkkkkkkkSS........',
    '........kkkkkkkkkEEEEEEkkkkkkkkkkkkkkkkkkEEEEEEkkkkkkkSS........',
    '........kkkkkkkkkkkEEkkkkkkkkkkkkkkkkkkkkkkEEkkkkkkkkkSS........',
    '........kkkkkkkkkkkkkkkkkkkkkkkooooookkkkkkkkkkkkkkkkkSS........',
    '........kkkkkkkkkkkkkkkkkkkkkooooooooookkkkkkkkkkkkkkkSS........',
    '........kkkkkkkkkkkkkkkkkkkkkooooooooookkkkkkkkkkkkkkkSS........',
    '........kkkkkkkkkkkkkkkkkkkkooooooooooookkkkkkkkkkkkkkSS........',
    '........kkkkkppkkkkkkkkwwwwwwwwwwwwwwwwwwkkkkkkkkppkkkSS........',
    '........kkkkpppppkkkkwwwwwwwwwwwwwwwwwwwwwwkkkkpppppkkSS........',
    '........kkkkpppppkkkkwwwwwwwwwwwwwwwwwwwwwwkkkkpppppkkSS........',
    '........kkkkpppppppkwwwwwwwwwwwwwwwwwwwwwwwwkpppppppkkSS........',
    '........kkkkppppppppwwwwwwwwwwwwwwwwwwwwwwwwppppppppkkSS........',
    '........kkkkkppppppwwwwwwwwwwwwwwwwwwwwwwwwwwppppppkkkSS........',
    '........kkkkkppppppwwwwwwwwwwwwwwwwwwwwwwwwwwppppppkkkSS........',
    '........kkkkkkkppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppkkkkkSS........',
    '........kkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkSS........',
    '........kkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkSS........',
    '........kkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkSS........',
    '........kkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkSS........',
    '........kkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkSS........',
    '........kkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkSS........',
    '........kkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkSS........',
    '........kkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkSS........',
    '........kkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkSS........',
    '........kkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkSS........',
    '........kkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkSS........',
    '........kkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkSS........',
    '........SkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkSS........',
    '.........SkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkSS.........',
    '..........kkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkSS.........',
    '..........kkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwkkkkkkkkkkSSS..........',
    '..........SSSkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSS..........',
    '...........SSSSkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSS...........',
    '.............SSkkkkkkkkkkSSSSSSSSSSSSSSkkkkkkkkkkSS.............',
    '...............SkkkkkkkkSSSSSSSSSSSSSSSSkkkkkkkkS...............',
    '................oooooooo................oooooooo................',
    '.................oooooo..................oooooo.................',
    '.................oooooo..................oooooo.................',
    '...................oo......................oo...................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'k': 0xFF3A4454,
    'w': 0xFFF2F4F5,
    'o': 0xFFF08C2E,
    'E': 0xFFF2F4F5,
    'p': kBuddyBlushColor,
    'S': 0xFF303845,
    'H': 0xFF656D7A,
  },
);
