// 电子宠物像素图：企鹅：黑背白肚 + 橙脚。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt penguinArt = BuddyPixelArt(
  rows: [
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '.......................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.......................................',
    '.....................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.....................................',
    '...................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...................................',
    '.................................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.................................',
    '...............................HHHHHHHHkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkHHHHHHHS...............................',
    '.............................HHHHHHHHkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkHHHHHSSS.............................',
    '.............................HHHHHHkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkHHHSSS.............................',
    '............................HHHHHkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkHSSSS............................',
    '............................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk............................',
    '............................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk............................',
    '............................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk............................',
    '............................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk............................',
    '.......................HHHHHkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkHHHHS.......................',
    '.....................HHHHHHkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkHHHSSS.....................',
    '.....................HHHHHHkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkHHHSSS.....................',
    '....................HHHHHkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkHSSSS....................',
    '....................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....................',
    '....................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....................',
    '....................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....................',
    '....................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....................',
    '...................HkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkS...................',
    '.................HHkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSS.................',
    '.................HHkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSS.................',
    '................HkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkkkkkEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEkkkkkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkkkEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEkkkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkEEEEEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEEEEEkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkEEEEEEEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEEEEEEEkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkEEEEEEEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEEEEEEEkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkEEEEEEEEEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEEEEEEEEEkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkEEEEEEEEEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEEEEEEEEEkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkEEEEEEEEEEEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEEEEEEEEEEEkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkEEEEEEEEEEEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEEEEEEEEEEEkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkEEEEEEEEEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEEEEEEEEEkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkEEEEEEEEEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEEEEEEEEEkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkEEEEEEEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEEEEEEEkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkEEEEEEEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEEEEEEEkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkEEEEEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEEEEEkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkkkEEEEEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEEEEEkkkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkkkkkEEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEEkkkkkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkooooooooookkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkooooooooooooookkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkooooooooooooooooookkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkooooooooooooooooooookkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkooooooooooooooooooookkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkooooooooooooooooooooookkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkooooooooooooooooooooookkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkooooooooooooooooooooooookkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkppkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkkkkkppkkkkkkkSSSS................',
    '................kkkkkkkkkppppppkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkppppppkkkkkSSSS................',
    '................kkkkkkkkkppppppppkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkppppppppkkkkkSSSS................',
    '................kkkkkkkkppppppppppkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkppppppppppkkkkSSSS................',
    '................kkkkkkkkppppppppppkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkppppppppppkkkkSSSS................',
    '................kkkkkkkkpppppppppppkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkpppppppppppkkkkSSSS................',
    '................kkkkkkkkpppppppppppppkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkpppppppppppppkkkkSSSS................',
    '................kkkkkkkkpppppppppppppppkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkpppppppppppppppkkkkSSSS................',
    '................kkkkkkkkppppppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppppppkkkkSSSS................',
    '................kkkkkkkkkppppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppppkkkkkSSSS................',
    '................kkkkkkkkkppppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppppkkkkkSSSS................',
    '................kkkkkkkkkkppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppkkkkkkSSSS................',
    '................kkkkkkkkkkppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppkkkkkkSSSS................',
    '................kkkkkkkkkkkppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkkSSSS................',
    '................kkkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkkkSSSS................',
    '................SkkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkkkSSSS................',
    '.................SSkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkkkSSSS.................',
    '.................SSkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkkkSSSS.................',
    '...................SkkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkkkkSSSS..................',
    '....................kkkkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkkkkkkSSSS..................',
    '....................kkkkkkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkkkkkkkSSSS...................',
    '....................kkkkkkkkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkkkkkkkSSSSSS...................',
    '....................kkkkkkkkkkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkkkkkkkkSSSSSS....................',
    '....................SSSSSkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSSSS....................',
    '.....................SSSSSSkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSSSS.....................',
    '.....................SSSSSSSSkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSSSSSS.....................',
    '.......................SSSSSSSkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSSSSS.......................',
    '.........................SSSSSkkkkkkkkkkkkkkkkkkkkkSSSSSSSSSSSSSSSSSSSSSSSSSSkkkkkkkkkkkkkkkkkkkkkSSSSS.........................',
    '...........................SSSSkkkkkkkkkkkkkkkkkkSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSkkkkkkkkkkkkkkkkkkSSSS...........................',
    '.............................SSkkkkkkkkkkkkkkkkkkSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSkkkkkkkkkkkkkkkkkkSS.............................',
    '...............................SkkkkkkkkkkkkkkkkSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSkkkkkkkkkkkkkkkkS...............................',
    '................................oooooooooooooooo................................oooooooooooooooo................................',
    '.................................oooooooooooooo..................................oooooooooooooo.................................',
    '.................................oooooooooooooo..................................oooooooooooooo.................................',
    '..................................oooooooooooo....................................oooooooooooo..................................',
    '..................................oooooooooooo....................................oooooooooooo..................................',
    '...................................oooooooooo......................................oooooooooo...................................',
    '.....................................oooooo..........................................oooooo.....................................',
    '.......................................oo..............................................oo.......................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'k': 0xFF3A4454,
    'w': 0xFFF2F4F5,
    'o': 0xFFF08C2E,
    'E': 0xFFF2F4F5,
    'p': kBuddyBlushColor,
    'S': 0xFF303845,
    'H': 0xFF656D7A,
  },
);
