// 电子宠物像素图：兔子：白色长耳 + 粉耳芯。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt rabbitArt = BuddyPixelArt(
  rows: [
    '..............................HHHH............................................HHHH..............................................',
    '.............................HHHHHH..........................................HHHHHH.............................................',
    '...........................HHHHHHHHHH......................................HHHHHHHHHH...........................................',
    '.........................HHHHHHHHHHHHHH..................................HHHHHHHHHHHHHH.........................................',
    '.......................HHHHHHHHwwHHHHHHHS..............................HHHHHHHHwwHHHHHHHS.......................................',
    '.....................HHHHHHHHwwwwwwHHHHHSSS..........................HHHHHHHHwwwwwwHHHHHSSS.....................................',
    '.....................HHHHHHwwwwwwwwwwHHHSSS..........................HHHHHHwwwwwwwwwwHHHSSS.....................................',
    '....................HHHHHwwwwwwwwwwwwwwHSSSS........................HHHHHwwwwwwwwwwwwwwHSSSS....................................',
    '....................wwwwwwwwwwwmmwwwwwwwwwww........................wwwwwwwwwwwmmwwwwwwwwwww....................................',
    '....................wwwwwwwwwmmmmmmwwwwwwwww........................wwwwwwwwwmmmmmmwwwwwwwww....................................',
    '....................wwwwwwwmmmmmmmmmmwwwwwww........................wwwwwwwmmmmmmmmmmwwwwwww....................................',
    '....................wwwwwwmmmmmmmmmmmmwwwwww........................wwwwwwmmmmmmmmmmmmwwwwww....................................',
    '...................HwwwwwwmmmmmmmmmmmmwwwwwwS......................HwwwwwwmmmmmmmmmmmmwwwwwwS...................................',
    '.................HHwwwwwwmmmmmmmmmmmmmmwwwwwSSS..................HHwwwwwwmmmmmmmmmmmmmmwwwwwSSS.................................',
    '.................HHwwwwwwmmmmmmmmmmmmmmwwwwwSSS..................HHwwwwwwmmmmmmmmmmmmmmwwwwwSSS.................................',
    '................HwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................HwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................................',
    '................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................................',
    '................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................................',
    '................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................................',
    '................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................................',
    '................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................................',
    '................wwwwwwwwmmmmmmmmmmmmmmmmwwwwwSSS................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................................',
    '................wwwwwwwwmmmmmmmmmmmmmmmmwwwwwSSS................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................................',
    '................wwwwwwwwmmmmmmmmmmmmmmmmwwwwwwwS................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................................',
    '................wwwwwwwwmmmmmmmmmmmmmmmmwwwwwwww................wwwwwwwwmmmmmmmmmmmmmmmmwwwwSSSS................................',
    '................wwwwwwwwwmmmmmmmmmmmmmmwwwwwwwww................wwwwwwwwwmmmmmmmmmmmmmmwwwwwSSSS................................',
    '................wwwwwwwwwmmmmmmmmmmmmmmwwwwwwwww................wwwwwwwwwmmmmmmmmmmmmmmwwwwwSSSS................................',
    '................wwwwwwwwwwmmmmmmmmmmmmwwwwwwwwww................wwwwwwwwwwmmmmmmmmmmmmwwwwwwSSSS................................',
    '................wwwwwwwwwwmmmmmmmmmmmmwwwwwwwwwwH..............HwwwwwwwwwwmmmmmmmmmmmmwwwwwwSSSS................................',
    '................wwwwwwwwwwwmmmmmmmmmmwwwwwwwwwwwwHH..........HHwwwwwwwwwwwwmmmmmmmmmmwwwwwwwwSSS................................',
    '................wwwwwwwwwwwwwmmmmmmwwwwwwwwwwwwwwHHHH......HHHHwwwwwwwwwwwwwwmmmmmmwwwwwwwwwwSSS................................',
    '................wwwwwwwwwwwwwwwmmwwwwwwwwwwwwwwwwwHHHHH..HHHHHwwwwwwwwwwwwwwwwwmmwwwwwwwwwwwwwwS................................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHHHHHHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww................................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHHHHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww................................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHHHHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww................................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww................................',
    '...............HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS...............................',
    '.............HHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS.............................',
    '.............HHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS.............................',
    '............HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS............................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................',
    '...........HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS...........................',
    '.........HHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS.........................',
    '.........HHwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSS.........................',
    '........HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwwwwwwwEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEwwwwwwwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwwwEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEwwwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEEEwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEEEwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEEEwwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwwwEEEEEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEEEEEwwwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwwwwwwwwwEEwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwEEwwwwwwwwwwwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppwwwwwwwSSSS........................',
    '........wwwwwwwwwppppppwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmmmmwwwwwwwwwwwwwwwwwwwwwwwwwwppppppwwwwwSSSS........................',
    '........wwwwwwwwwppppppppwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmmmmwwwwwwwwwwwwwwwwwwwwwwwwppppppppwwwwwSSSS........................',
    '........wwwwwwwwppppppppppwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmmmmmmwwwwwwwwwwwwwwwwwwwwwwppppppppppwwwwSSSS........................',
    '........wwwwwwwwppppppppppwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmmmmmmwwwwwwwwwwwwwwwwwwwwwwppppppppppwwwwSSSS........................',
    '........wwwwwwwwpppppppppppwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmmmmwwwwwwwwwwwwwwwwwwwwwwpppppppppppwwwwSSSS........................',
    '........wwwwwwwwpppppppppppppwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmmmmwwwwwwwwwwwwwwwwwwwwpppppppppppppwwwwSSSS........................',
    '........wwwwwwwwppppppppppppppwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmwwwwwwwwwwwwwwwwwwwwwppppppppppppppwwwwSSSS........................',
    '........wwwwwwwwppppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppppwwwwSSSS........................',
    '........wwwwwwwwwppppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppppwwwwwSSSS........................',
    '........wwwwwwwwwppppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppppwwwwwSSSS........................',
    '........wwwwwwwwwwppppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppppwwwwwwSSSS........................',
    '........wwwwwwwwwwppppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppppwwwwwwSSSS........................',
    '........wwwwwwwwwwwppppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppppwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwppppppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppppppwwwwwwwwwSSSS........................',
    '........wwwwwwwwwwwwwwwppppppwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppppppwwwwwwwwwwwSSSS........................',
    '........SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS........................',
    '.........SSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS.........................',
    '.........SSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS.........................',
    '...........SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS..........................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS..........................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS...........................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS...........................',
    '............wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS............................',
    '............SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS............................',
    '.............SSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS.............................',
    '.............SSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS.............................',
    '...............SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS..............................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS..............................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS...............................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS...............................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................................',
    '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................................',
    '................SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS................................',
    '.................SSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS.................................',
    '.................SSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS.................................',
    '...................SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSSSS..................................',
    '....................wwwwwwwwwwwwwwwwwwwwwwwwwwwSSSSSSSSSSSSSSSSSSwwwwwwwwwwwwwwwwwwwwwwwwwSSSS..................................',
    '....................wwwwwwwwwwwwwwwwwwwwwwwwwSSSSSSSSSSSSSSSSSSSSSSwwwwwwwwwwwwwwwwwwwwwwSSSS...................................',
    '....................wwwwwwwwwwwwwwwwwwwwwwwSSSSSSSSSSSSSSSSSSSSSSSSSSwwwwwwwwwwwwwwwwwwSSSSSS...................................',
    '....................wwwwwwwwwwwwwwwwwwwwwSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSwwwwwwwwwwwwwwwSSSSSS....................................',
    '....................SSSSSwwwwwwwwwwwwwwSSSSSSSS..................SSSSSSSSwwwwwwwwwwwwwSSSSSS....................................',
    '.....................SSSSSSwwwwwwwwwwSSSSSSSS......................SSSSSSSSwwwwwwwwwwSSSSSS.....................................',
    '.....................SSSSSSSSwwwwwwSSSSSSSS..........................SSSSSSSSwwwwwwSSSSSSSS.....................................',
    '.......................SSSSSSSSwwSSSSSSSS..............................SSSSSSSSwwSSSSSSSS.......................................',
    '.........................SSSSSSSSSSSSSS..................................SSSSSSSSSSSSSS.........................................',
    '...........................SSSSSSSSSS......................................SSSSSSSSSS...........................................',
    '.............................SSSSSS..........................................SSSSSS.............................................',
    '...............................SS..............................................SS...............................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'w': 0xFFF6F3EE,
    'm': 0xFFF0A8B8,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFCAC7C3,
    'H': 0xFFF8F6F2,
  },
);
