// 电子宠物像素图：兔子：白色长耳 + 粉耳芯。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt rabbitArt = BuddyPixelArt(
  rows: [
    '...............HH......................HH.......................',
    '.............HHHHHH..................HHHHHH.....................',
    '...........HHHHwwHHHS..............HHHHwwHHHS...................',
    '..........HHHwwwwwwHSS............HHHwwwwwwHSS..................',
    '..........wwwwwmmwwwww............wwwwwmmwwwww..................',
    '..........wwwmmmmmmwww............wwwmmmmmmwww..................',
    '.........HwwwmmmmmmwwwS..........HwwwmmmmmmwwwS.................',
    '........HwwwmmmmmmmmwwSS........HwwwmmmmmmmmwwSS................',
    '........wwwwmmmmmmmmwwSS........wwwwmmmmmmmmwwSS................',
    '........wwwwmmmmmmmmwwSS........wwwwmmmmmmmmwwSS................',
    '........wwwwmmmmmmmmwwSS........wwwwmmmmmmmmwwSS................',
    '........wwwwmmmmmmmmwwwS........wwwwmmmmmmmmwwSS................',
    '........wwwwmmmmmmmmwwww........wwwwmmmmmmmmwwSS................',
    '........wwwwwmmmmmmwwwww........wwwwwmmmmmmwwwSS................',
    '........wwwwwmmmmmmwwwwwH......HwwwwwmmmmmmwwwSS................',
    '........wwwwwwwmmwwwwwwwwHH..HHwwwwwwwwmmwwwwwwS................',
    '........wwwwwwwwwwwwwwwwwHHHHHHwwwwwwwwwwwwwwwww................',
    '........wwwwwwwwwwwwwwwwwwwHHwwwwwwwwwwwwwwwwwww................',
    '.......HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS...............',
    '......HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS..............',
    '......wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww..............',
    '......wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww..............',
    '.....HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS.............',
    '....HwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS............',
    '....wwwwwwwwwwwEEwwwwwwwwwwwwwwwwwwwwwwEEwwwwwwwwwSS............',
    '....wwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwSS............',
    '....wwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwSS............',
    '....wwwwwwwwEEEEEEEEwwwwwwwwwwwwwwwwEEEEEEEEwwwwwwSS............',
    '....wwwwwwwwEEEEEEEEwwwwwwwwwwwwwwwwEEEEEEEEwwwwwwSS............',
    '....wwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwSS............',
    '....wwwwwwwwwEEEEEEwwwwwwwwwwwwwwwwwwEEEEEEwwwwwwwSS............',
    '....wwwwwwwwwwwEEwwwwwwwwwwwwwwwwwwwwwwEEwwwwwwwwwSS............',
    '....wwwwwppwwwwwwwwwwwwwwmmmmmmwwwwwwwwwwwwwwppwwwSS............',
    '....wwwwpppppwwwwwwwwwwwmmmmmmmmwwwwwwwwwwwpppppwwSS............',
    '....wwwwpppppwwwwwwwwwwwmmmmmmmmwwwwwwwwwwwpppppwwSS............',
    '....wwwwpppppppwwwwwwwwwwmmmmmmwwwwwwwwwwpppppppwwSS............',
    '....wwwwpppppppwwwwwwwwwwwwwwwwwwwwwwwwwwpppppppwwSS............',
    '....wwwwwpppppppwwwwwwwwwwwwwwwwwwwwwwwwpppppppwwwSS............',
    '....wwwwwpppppppwwwwwwwwwwwwwwwwwwwwwwwwpppppppwwwSS............',
    '....wwwwwwwppppwwwwwwwwwwwwwwwwwwwwwwwwwwppppwwwwwSS............',
    '....SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS............',
    '.....SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS.............',
    '......wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS.............',
    '......wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS..............',
    '......SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS..............',
    '.......SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS...............',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS...............',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS................',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS................',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS................',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS................',
    '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS................',
    '........SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS................',
    '.........SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwSS.................',
    '..........wwwwwwwwwwwwwSSSSSSSSSSwwwwwwwwwwwwSS.................',
    '..........wwwwwwwwwwwSSSSSSSSSSSSSSwwwwwwwwSSS..................',
    '..........SSSwwwwwwSSSS..........SSSSwwwwwwSSS..................',
    '...........SSSSwwSSSS..............SSSSwwSSSS...................',
    '.............SSSSSS..................SSSSSS.....................',
    '...............SS......................SS.......................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'w': 0xFFF6F3EE,
    'm': 0xFFF0A8B8,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFCAC7C3,
    'H': 0xFFF8F6F2,
  },
);
