// 电子宠物像素图：机器人：灰蓝 + 天线 + 指示灯。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt robotArt = BuddyPixelArt(
  rows: [
    '..........................................................yyyy..................................................................',
    '.........................................................yyyyyy.................................................................',
    '.........................................................yyyyyy.................................................................',
    '........................................................yyyyyyyy................................................................',
    '........................................................yyyyyyyy................................................................',
    '........................................................yyyyyyyy................................................................',
    '........................................................yyyyyyyy................................................................',
    '........................................................yyyyyyyy................................................................',
    '........................................................kkkkkkkk................................................................',
    '.......................................................kkkkkkkkkk...............................................................',
    '.......................................................kkkkkkkkkk...............................................................',
    '......................................................kkkkkkkkkkkk..............................................................',
    '......................................................kkkkkkkkkkkk..............................................................',
    '.....................................................kkkkkkkkkkkkkk.............................................................',
    '...................................................kkkkkkkkkkkkkkkkkk...........................................................',
    '.................................................kkkkkkkkkkkkkkkkkkkkkk.........................................................',
    '...............................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...............................',
    '.............................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.............................',
    '...........................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...........................',
    '.........................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........................',
    '.......................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......................',
    '.....................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....................',
    '.....................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....................',
    '....................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....................',
    '....................kkkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkkk....................',
    '...................kkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkk...................',
    '...................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk...................',
    '..................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk..................',
    '..................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk..................',
    '.................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk.................',
    '.................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk.................',
    '................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbggggggggggggggggggggggggggggggggggbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk................',
    '................kkkkkkkkkbbbbbbbbbbbbbbbbbbbbggggggggggggggggggggggggggggggggggggggbbbbbbbbbbbbbbbbbbbbkkkkkkkkk................',
    '................kkkkkkkkkbbbbbbbbbbbbbbbbbbggggggggggggggggggggggggggggggggggggggggggbbbbbbbbbbbbbbbbbbkkkkkkkkk................',
    '................kkkkkkkkkkbbbbbbbbbbbbbbbbggggggggggggggggggggggggggggggggggggggggggggbbbbbbbbbbbbbbbbkkkkkkkkkk................',
    '................kkkkkkkkkkbbbbbbbbbbbbbbbbggggggggggggggggggggggggggggggggggggggggggggbbbbbbbbbbbbbbbbkkkkkkkkkk................',
    '................kkkkkkkkkkkbbbbbbbbbbbbbbggggggggggggggggggggggggggggggggggggggggggggggbbbbbbbbbbbbbbkkkkkkkkkkk................',
    '................kkkkkkkkkkkkkbbbbbbbbbbbbggggggggggggggggggggggggggggggggggggggggggggggbbbbbbbbbbbbkkkkkkkkkkkkk................',
    '................kkkkkkkkkkkkkkkbbbbbbbbbggggggggggggggggggggggggggggggggggggggggggggggggbbbbbbbbbkkkkkkkkkkkkkkk................',
    '................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk................',
    '.................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.................',
    '.................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.................',
    '..................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..................',
    '..................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..................',
    '...................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...................',
    '...................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...................',
    '....................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....................',
    '....................kkkkkkkkkkkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkkkkkkkkkkk....................',
    '.....................kkkkkkkkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkkkkkkkk.....................',
    '.....................kkkkkkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkkkkkk.....................',
    '......................kkkkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkkkk......................',
    '......................kkkkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkkkk......................',
    '.......................kkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkk.......................',
    '.......................kkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkk.......................',
    '........................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk........................',
    '.......................ykkkkkkkkbbbbbbbbbbbbbbbbbbbyyyyyyyyyybbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkky.......................',
    '.....................yyykkkkkkkkbbbbbbbbbbbbbbbbbyyyyyyyyyyyyyybbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyy.....................',
    '...................yyyyykkkkkkkkbbbbbbbbbbbbbbbbbyyyyyyyyyyyyyybbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyyyy...................',
    '..................yyyyyykkkkkkkkbbbbbbbbbbbbbbbbyyyyyyyyyyyyyyyybbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyyyyy..................',
    '..................yyyyyykkkkkkkkbbbbbbbbbbbbbbbbyyyyyyyyyyyyyyyybbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyyyyy..................',
    '.................yyyyyyykkkkkkkkbbbbbbbbbbbbbbbbbyyyyyyyyyyyyyybbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyyyyyy.................',
    '.................yyyyyyykkkkkkkkbbbbbbbbbbbbbbbbbyyyyyyyyyyyyyybbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyyyyyy.................',
    '................yyyyyyyykkkkkkkkbbbbbbbbbbbbbbbbbbbyyyyyyyyyybbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyyyyyyy................',
    '................yyyyyyyykkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyyyyyyy................',
    '.................yyyyyyykkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyyyyyy.................',
    '.................yyyyyyykkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyyyyyy.................',
    '..................yyyyyykkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyyyyy..................',
    '..................yyyyyykkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyyyyy..................',
    '...................yyyyykkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyyyy...................',
    '.....................yyykkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkyyy.....................',
    '.......................ykkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkky.......................',
    '........................kkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkk........................',
    '........................kkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkk........................',
    '........................kkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkk........................',
    '........................kkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkk........................',
    '........................kkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkk........................',
    '........................kkkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkkk........................',
    '........................kkkkkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkkkkk........................',
    '........................kkkkkkkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkkkkkkk........................',
    '........................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk........................',
    '.........................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........................',
    '.........................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........................',
    '..........................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..........................',
    '..........................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..........................',
    '...........................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...........................',
    '...........................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...........................',
    '............................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk............................',
    '............................kkkkkkkkkkkkkkkkkkkkkkkkkkk..................kkkkkkkkkkkkkkkkkkkkkkkkkkk............................',
    '.............................kkkkkkkkkkkkkkkkkkkkkkkk......................kkkkkkkkkkkkkkkkkkkkkkkk.............................',
    '.............................kkkkkkkkkkkkkkkkkkkkkk..........................kkkkkkkkkkkkkkkkkkkkkk.............................',
    '...............................kkkkkkkkkkkkkkkkkk..............................kkkkkkkkkkkkkkkkkk...............................',
    '.................................kkkkkkkkkkkkkk..................................kkkkkkkkkkkkkk.................................',
    '...................................kkkkkkkkkk......................................kkkkkkkkkk...................................',
    '.....................................kkkkkk..........................................kkkkkk.....................................',
    '.......................................kk..............................................kk.......................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'b': 0xFFC3CDD9,
    'k': 0xFF5B6B7E,
    'y': 0xFFF2C14E,
    'g': 0xFF69D2C8,
    'E': 0xFF3ACCE1,
    'p': kBuddyBlushColor,
    'S': 0xFFA0A8B2,
    'H': 0xFFD0D8E1,
  },
);
