// 电子宠物像素图：机器人：灰蓝 + 天线 + 指示灯。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt robotArt = BuddyPixelArt(
  rows: [
    '.............................yy.................................',
    '............................yyyy................................',
    '............................yyyy................................',
    '............................yyyy................................',
    '............................kkkk................................',
    '...........................kkkkkk...............................',
    '...........................kkkkkk...............................',
    '.........................kkkkkkkkkk.............................',
    '...............kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...............',
    '.............kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.............',
    '...........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...........',
    '..........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..........',
    '..........kkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkk..........',
    '.........kkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkk.........',
    '.........kkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkk.........',
    '........kkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkk........',
    '........kkkkbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbkkkk........',
    '........kkkkbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbkkkk........',
    '........kkkkbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbkkkk........',
    '........kkkkbbbbEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEbbbbkkkk........',
    '........kkkkbbbbEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEbbbbkkkk........',
    '........kkkkbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbkkkk........',
    '........kkkkbbbbbEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEbbbbbkkkk........',
    '........kkkkbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbkkkk........',
    '........kkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkk........',
    '........kkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkk........',
    '........kkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkk........',
    '........kkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkk........',
    '........kkkkbbbbbbbbbbbggggggggggggggggggbbbbbbbbbbbkkkk........',
    '........kkkkkbbbbbbbbggggggggggggggggggggggbbbbbbbbkkkkk........',
    '........kkkkkbbbbbbbbggggggggggggggggggggggbbbbbbbbkkkkk........',
    '........kkkkkkkbbbbbggggggggggggggggggggggggbbbbbkkkkkkk........',
    '........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk........',
    '.........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........',
    '.........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........',
    '..........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..........',
    '..........kkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkk..........',
    '...........kkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkk...........',
    '...........kkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkk...........',
    '............kkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkk............',
    '...........ykkkkbbbbbbbbbyyyyyybbbbbbbbbbbbbbbbbkkkky...........',
    '.........yyykkkkbbbbbbbbyyyyyyyybbbbbbbbbbbbbbbbkkkkyyy.........',
    '.........yyykkkkbbbbbbbbyyyyyyyybbbbbbbbbbbbbbbbkkkkyyy.........',
    '........yyyykkkkbbbbbbbbbyyyyyybbbbbbbbbbbbbbbbbkkkkyyyy........',
    '........yyyykkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkyyyy........',
    '.........yyykkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkyyy.........',
    '.........yyykkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkyyy.........',
    '...........ykkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkky...........',
    '............kkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkk............',
    '............kkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkk............',
    '............kkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkk............',
    '............kkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkkk............',
    '............kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk............',
    '.............kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.............',
    '.............kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.............',
    '..............kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..............',
    '..............kkkkkkkkkkkkk..........kkkkkkkkkkkkk..............',
    '...............kkkkkkkkkk..............kkkkkkkkkk...............',
    '.................kkkkkk..................kkkkkk.................',
    '...................kk......................kk...................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'b': 0xFFC3CDD9,
    'k': 0xFF5B6B7E,
    'y': 0xFFF2C14E,
    'g': 0xFF69D2C8,
    'E': 0xFF3ACCE1,
    'p': kBuddyBlushColor,
    'S': 0xFFA0A8B2,
    'H': 0xFFD0D8E1,
  },
);
