// 腼腆奶龙：以 Codex Pets 官方腼腆奶龙精灵图（待机第 1 帧）为参考
// 量化的 64×64 高清像素版——圆滚黄身、奶白大肚皮、绿眼睛、抱肚小手。

import 'pixel_art.dart';

const BuddyPixelArt shyNailongArt = BuddyPixelArt(
  rows: [
    '............................aaaahaa.............................',
    '..........................aabbbbbbbaa...........................',
    '.........................abbbbbdbbbbba..........................',
    '........................abdbbbdddddddbh.........................',
    '.......................hbddddbbbbdddddbh........................',
    '.......................bdfffddbbbddgfddb........................',
    '......................hbblcbfddbbbgkhhbbh.......................',
    '......................hbEEElgddddfdEEElfk.......................',
    '......................hkEEEEfgfdgfkEEEEfd.......................',
    '.....................lbiEEEngfddffiEEEEgbl......................',
    '.....................hbfnEEifddddfgnEEiidk......................',
    '.....................hdgiigffdddddfggiiifk......................',
    '.....................kdggggigfggfggggggigk......................',
    '.....................bfgiiijnnnnnnmiiiiigb......................',
    '.....................bfiijjjjjmmmjjjjiiigdk.....................',
    '....................hbgiijjjjjjjjjjjjjiiifk.....................',
    '....................hdiijjjjjjjjjjjjjjjiigbl....................',
    '...................hbfgiiijjjjjjjjjjjjiigfdh....................',
    '...................addfgggiiiijjjiigggggggfbh...................',
    '..................hbddfgggggggggggggggggffddbh..................',
    '.................hbdffffffffggggggggffggffffdbh.................',
    '................hbdffffffffffffffffffffffffffdbh................',
    '...............hbddggfggffffdfffffffffffffggfddbh...............',
    '..............hbddfggffffffffdbbbdffffffffgigdddbh..............',
    '.............hbdbdgjfffffdbhaaccccaabfffffgjgddddb..............',
    '............hbdbdfjjffffbacccccccccccahffffjjgdddbh.............',
    '............hbbdfgmjdfbacccccccccccccccabgfmmgfdbdbh............',
    '...........hbbbdgjmifbcccccccccccccccccccbfimjgdbbbh............',
    '...........hbbdfgmnfhccccccccccccccccccccchgnmgfdbdbh...........',
    '..........hbbbdgjnmbcccccccccccccccccccccccbnnifbbbbk...........',
    '..........hbbbbbfnjacccccccccccccccccccccccamnbbbbddk...........',
    '..........kddbbbbdkcccccccccccccccccccccccchkbbbbdffd...........',
    '..........kdfdbbbbbhcllllcccccccccccccllllhkbbbbdfggk...........',
    '..........kfgfdbbbbkoooqocccccccccccccoqooonbbbdfgigk...........',
    '..........kdigfdbbkooooqlcccccccccccccoqoooondfggiii............',
    '...........kgiggffooooooolcccccccccccooooooooggiijgn............',
    '............iiiignooooqqqohccccccccclqqqooooqmgjjin.............',
    '.............ijjgnqqqooqqohccccccccclqqqooqqqnjjjn..............',
    '.............kjmjnqqqqoooohcccccccccloooqqqqqnmnmk..............',
    '.............bimnnqqqqqqqohcccccccccloqqqqqqqnnmmk..............',
    '.............bimnnooqqqqolhccccccccchloqqqqonlnmid..............',
    '............lbiiklllooqqlhcccccccccchhlqqonlllkjid..............',
    '............hbiiillllllllhcccccccccchhlllllllliiid..............',
    '............lbiiiklllllhhhccccccccchhhhllllllkjiid..............',
    '.............biiiihhlhhhhhcccchhhhhhhhhhllllljjiik..............',
    '.............kiiijklhhhhhhhhhhhhhhhhhhhhhlllijjjik..............',
    '.............kiiiijkhhhhhhhhhhhhhhhhhhhllllijjjjgk..............',
    '.............kfiijjjilhllhlhlhhhhhlllllllkjjjjjji...............',
    '..............kijjjjjjklllllllllllllllllkjjjjjjin...............',
    '...............fjjjjjjjjkklllllllllllkijmjmmmmji................',
    '...............kimmmmjjjjmjikkkkkkkjjmmmmmmmmmi.................',
    '................kjmmmmmmmmmmmmmmmmmmmmmmmmmmmjn.................',
    '................kimmmmmmmmmmmmmmmmmmmmmmmmmmmi..................',
    '................kfjjmmmmmmmmmmmmmmmmmmmmmmmmji..................',
    '.................djjjmmmmmmmmmmmmmmmmmmmmmjjjk..................',
    '.................kjjjjmmmnnnnnnnnnnnnnmmmjjjin..................',
    '.................kijjjmmmno.........nmmmmjjmi...................',
    '.................kgjjjmmmn..........nmmmmmmmm...................',
    '.................lmmmmmmmn...........mmmmmnno...................',
    '.................oooooonoq...........qqqqqqqoo..................',
    '...............ooooqqqqqqq...........qqqqqqooqo.................',
    '...............oqooqqoqqqq...........qqqoqqooqoo................',
    '...............oqooqooqqq.............qqooqooqq.................',
    '.................qqqqqq................qqqqqq...................',
  ],
  palette: {
    'E': 0xFF2F5A1E,
    'a': 0xFFF8DF86,
    'b': 0xFFFDDD37,
    'c': 0xFFF4D799,
    'd': 0xFFFDD730,
    'f': 0xFFFED124,
    'g': 0xFFFDC91A,
    'h': 0xFFEECA75,
    'i': 0xFFF6BD17,
    'j': 0xFFF0B20A,
    'k': 0xFFE6B74F,
    'l': 0xFFDCB771,
    'm': 0xFFE4A406,
    'n': 0xFFC6932D,
    'o': 0xFF816F4F,
    'q': 0xFF5A5045,
  },
);
