// 腼腆奶龙：以 Codex Pets 官方腼腆奶龙精灵图（待机第 1 帧）为参考
// 量化的 128×128 高清像素版——圆滚黄身、奶白大肚皮、绿眼睛、抱肚小手。

import 'pixel_art.dart';

const BuddyPixelArt shyNailongArt = BuddyPixelArt(
  rows: [
    '...........................................................ggiifiiii............................................................',
    '.......................................................ngfffffhaffffffgi........................................................',
    '......................................................gffaaaaaaaaaaaaaffgi......................................................',
    '....................................................gffaaaaaaabbaaaaaaaaffg.....................................................',
    '...................................................ffaaaaaaabbbbbbbaaaaaaaff....................................................',
    '..................................................ffaaaaabbbbbbcbbbbbbbaaaahf...................................................',
    '.................................................faaabbbbbbbbbbbbbcbbbbbbbbaaf..................................................',
    '................................................faaabbbcbbbbbbbbbbcccccccbbbaaf.................................................',
    '...............................................ifaabccccccbbbbbbbbbbcccccccbbaan................................................',
    '...............................................faabcccccccbbbbbbbbbbccccccccbaaf................................................',
    '..............................................ifabcccccccccbbbbbbbbbccccccbbbbaah...............................................',
    '..............................................faabjkmkjccccbbbbbbbbbcccjkkkcbbbah...............................................',
    '.............................................nfaajbgdiojcccbbbbbbbbbccjmoiihjbbbah..............................................',
    '.............................................ihajhgnnddokccccbcbbbbbcjqgdggdgkcbah..............................................',
    '.............................................fhbaEEEEEEdqjccccccbccccmnEEEEEEfkcbh..............................................',
    '............................................nfhbfEEnEnEEhkccccccccccjoEEnEEEEEbjcan.............................................',
    '............................................nhbcEEEEEEEEnmjjjccccjcjkoEEEEEEEEhkjbh.............................................',
    '............................................fhbcEEEEEEEEnmjlljccjljckoEEEEEEEEokjbh.............................................',
    '............................................fhcjEEEEEEEEokjjjcbcjkjjjlEEEEEEEEokjch.............................................',
    '............................................fbcjoEEEEEErmjjcccbccccjjkEEEEEEEnlkjchn............................................',
    '...........................................nabcjlrEEEEEqkjjcccbbcccjjjlEEEEErrkkkcan............................................',
    '...........................................iabcjjlEEEEmkjjccccbbcccjjjklEEEErmkkkjah............................................',
    '...........................................iabjjkkmmmkjjjcccccccccccjjjjklqmkkkkkjbh............................................',
    '...........................................hbcjjkkkkjjjjjjccccccccccjjjjjjkkkkkkkjch............................................',
    '...........................................fbcjjjkkkkjjkjjjjjjjjjjjjjjkkkkkkkkkkkjchn...........................................',
    '...........................................fbcjjkkkkkkkmkjjjkkkkkkkkkkkkkkkkkkkkkjcan...........................................',
    '..........................................nabcjlkkkkkkkmrrqqqqqqqqqqqrmkkkkkkkkkljjbh...........................................',
    '..........................................iacclllkkkkkmkqrrsttttttsrrqkkkmmkmkkkkjcch...........................................',
    '..........................................hbccllkkklmmmmkkkmmmllmmmkkkmmmmmmmlkkkkjca...........................................',
    '..........................................hbcjllllmmmmmmmmmmmmmmmmmmmmmmmmmmkkkkkkjcan..........................................',
    '.........................................nhbcjllllmmmmmmmmmmmmmmmmmmmmmmmmmmmkkkkkkcbh..........................................',
    '.........................................nabcjlllmmmmmmmmmmmmmmmmmmmmmmmmmmmmmkkkkkjcan.........................................',
    '.........................................fbcjlllmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmkkkjjcan.........................................',
    '........................................nfbcjkklmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmkkkkjcban........................................',
    '........................................fabcjkkkmkmmmmmmmmmmmmmmmmmmmmmmmmmmmmmkkkkjjcaf........................................',
    '.......................................ifabcjkkkkkkkmmmmmmmmmmmmmmmmmmmmmmkmmkkkkkkjjcafn.......................................',
    '......................................nfhabcjjkkkkkkkkkmmmmmmmmmmmmmmmmkkkkkkkkkkkkjjcbhf.......................................',
    '......................................fhabbcjjjkkkkkkkkkkkmmmmmmmmmkkkkkkkkkkkkkkkkjjcbaaf......................................',
    '.....................................faaabcccjjjjkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkjjccccbaaf.....................................',
    '....................................gaabbcccjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkjjkkkjjcccccbbaai....................................',
    '...................................iaabcccccjjjjjjjjjjjjkkkkkkkjjkkjkkkkjjjjjjjjjjjjjjjccbaai...................................',
    '..................................iaabccccjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjcbbaaf..................................',
    '.................................iaabccjjjjjjjjjjcjjjjjjjjjjjjjjjjjjjjjjcjjjjjjjjjjjjjjjjccbaaf.................................',
    '................................iaabbcjjjjjjjjjjjjjcjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjcccbbaf................................',
    '...............................faabccccjjjjjjjjjjjjjcccccccccccccjcccccjjjjjjjjjjjjjjjkjjcccbbaaf...............................',
    '..............................iaabccccjkkkkjjkjjjjjjjjjjccccccccccccccccjjjcjjjccjjjjkkkjccccbbaaf..............................',
    '.............................nfabccccjkkkkjjjjjjjjcjjjccccccccccccccccccccccjjccjjjjjkkkkjccccbbaan.............................',
    '............................nfabbccccjkmkkjjjjjjjjjccccjjjjcbbaaaabccjcccccjcccjjjjjjkmmkjcbbbcbbaan............................',
    '............................faabbbbccjmmkkjjjjjjjcccjjcbahffggddddggfhhacjjccjjjjjjjjkmmmjjcbbbbcbaf............................',
    '...........................faabbbbbcjkmmkjcjjjjjjcjcahfdddddddddddddddddghbjjjjjjjjjjjkmmkjccbbcccbaf...........................',
    '..........................iabbbbbbccjkmmkjjjjjjjjjafgdddddddddddddddddddddgfajjjjjjjjjkqmkkjccccccbban..........................',
    '.........................nfabbbbbccjkmqqjcjjjcjjafggddddddddddddddddddddddddgfacccjjjjkqqmkjccccbccbaf..........................',
    '.........................fabbbbbccjkmmqmjccccjbfddddddddddddddddddddddddddddddgfbjjjjkkqqmmkjccbbbcbbaf.........................',
    '........................iaabbbbbcjjkmqrmccccchgddddddddddddddddddddddddddddddggdibjjjkkqrqmkjccbbbbbbafn........................',
    '........................fabbbbbccjkmmqrkcccchgdgddddddddddddddddddddddddddddgggggghjjjkmrqmkkjccbbbbbaah........................',
    '.......................iaabbbbccjjkmmrqjccchggggdddddddddddddddddddddddddddgggggggghcjjkrqmmkkjccbbbbbaan.......................',
    '.......................fabbbbbccjkkmqrqjccfggdggdggggdddddddddddddddddddddddgggggggghcjkqrqmmkjccbbbbbbah.......................',
    '......................ifabbbbbcjkkmqqrmccfgggggggddggddddddddddddddddddddddgggggggggghjjqtqqmkkjcbbbbbbah.......................',
    '......................fabbbbbcjkkmmqrrkjhgggggggggddggddddddddddddddddddddgggggggggggghkksrmmmkjcbbbbbbban......................',
    '......................fabbbbbbcckmqqtrkbiggggggggggggggddddddddddddddgddggdgggggggggggicmrtqqkcbbbbbbbbban......................',
    '.....................nfabbbaaabbckqrtqjfgggggggggggggdgdddddddddddddddddddggggggggggggifkqtrjbbbbbbbbbccbh......................',
    '.....................habbbbbbaaabbbrtmhgggggggggggggggdddddggdddddddddgdddgggggggggggifihqrcbbbbbbbbccccbh......................',
    '.....................nabbbbbbaaaaaaaqqfiggggggggggggggggdgdddgdddddddgdgggdggggigigigiiinocbbbbbbbbccjjjch......................',
    '.....................habbccbbaaaaabbboigggggggggggggggggggddddddddddggggggggggggggiiiiiihabbbbbbbbccjjjjch......................',
    '.....................habcccbbbbbbbbbaahiiiggginnngggggggggdddddddgggggggggggginnniggiinhbbbbbbbbbccjjkkjch......................',
    '.....................nabjjccbbbbbbbbbbbhfiinnssssnggggggdddddgdgddggggggggggnssssssnnnhbbbbbbbbbccjjkkkkco......................',
    '.....................hacjjjcccbbbbaabaachnssssssssigggggddddggggggggggggggggstssssssssrobbbbbbbccjjkkkklcr......................',
    '.....................nackkjjjccbbbaaaabssssssstttsngggggggdggdggggdgggggggggsttttsssssssoabbbccjjjkkkkllo.......................',
    '......................hclkkkjjccbbbbabsssssssttttsniggggggggggggggdgggggggiinttttsssssssscbbccjjkkkkkmljo.......................',
    '......................hclkkkkjjjccbbbrssssssssstsnniigggggggggggggggggggggginsstsssssssssrbcjjjkkkkmmllo........................',
    '.......................blllkkkkjjjccjssssssssssssssngggggggggggggggggggggginssssssssssssssjjkkkkkkmmmlkr........................',
    '.......................njlllkkkkkjjjrsssssssssssssssnggggggggggggggggggggissssssssssssssssokkkkkmmmmllo.........................',
    '........................ollllmkkkkkjrsssssssssssssstsigggggggggggggggggggnssssssssssssssssrkkmmmmmmqlo..........................',
    '.........................olllmmmkkkkssssssssstttttttsigggggggggggggggggggntttttttsssssssstsmmmmmmmqlo...........................',
    '..........................ollmmmmmkmssssssssssttttttnnigggggggggggggggiiinsttttttsssssssttsmmmmmmqqo............................',
    '...........................oolmmmmkqttttttsssssssttsnnigggggggggggggggiiinrtttsssssssstttttqmmmqqqon............................',
    '...........................noolmmmmrtttttttsssssssssniiggggggggggggggggiinsssssssttttttttttqmqqqrroh............................',
    '...........................hoooqqqmrtttttttttstsssstniiggggggggggggggggiinstsstttttttttttttqqqrrrroo............................',
    '..........................nhooqqqqqqttttttttttttttttnniiiigggiggggiggiiiinstttttttttttttttsqrrrqqooh............................',
    '..........................nhoooqqrrrrttttttttttttttsnniigggggggggiggiiiiinrttttttttttttttsrrsrqqqooh............................',
    '..........................nhooooqrrsssttttttsstttsrnniiiiggggggggggigiiiinnrsstttsttttttsssrrrqqlooan...........................',
    '..........................hhoollqonrrrrsstttttsttrnnniiiiiigiggiggiiiiiiiinnnsttstttttssrrnnnoqqlloan...........................',
    '..........................haollllonnnnnrrssttttttrnniiiiigiiigigiigiiiiiiinnnstttttsssrrnnnnnllllloah...........................',
    '..........................haolllllnnnnnnnrrsstttsnnniiiiigggiiiiiiiiiiiiiinnnnsttssrrnnnnnnnoqllllobh...........................',
    '..........................haoollllhnnnnnnnnrrrrrnnnniiiggggiiiiiiiiiiiiiiiinnnnrrrrnnnnnnnnnomllllobh...........................',
    '..........................haoollllonnnnnnnnnnnnnnniiiiiiiiiiiiiiiiiiiiiiiiinnnnnnnnnnnnnnnnnllllllobh...........................',
    '..........................haoclllllnnnnnnnnnnnnnniiiiiiiiiiiiiiiiiiiiiiiiiiiinnnnnnnnnnnnnnomlllllobh...........................',
    '..........................hboolllllonnnnnnnnnnnniiiiiiiiiiiiiiiiiiiiiiiiiiiiinnnnnnnnnnnnnhlmllllllbn...........................',
    '..........................hholllllllhnnnnnnnnnnniiiiiiiiiiiiiiiiiiiiiiiiiiiiiinnnnnnnnnnnnommmllllobo...........................',
    '..........................naolllllllonnnnnnnnniiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiinnnnnnnnnnnommmmllllob............................',
    '..........................naollllllllonnnnnnniiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiinnnnnnnnnhlmmmmlllloo............................',
    '...........................hollllllllmonnnnniiiiiiiiiiiiiiiiiiiiiiiiiinniiiinnnnnnnnnnnnlmmmmmmllljo............................',
    '...........................hclllllllllmonnnnnnniiininiiiiiiiiiiiiiininniiinnnnnnnnnnnnnlmmmmmmllllcr............................',
    '...........................hcollllllmmmlonnnnnnnnnnnnniiniiiinniiinnnnnnnnnnnnnnnnnnnhlmmmmmmmllllo.............................',
    '............................blllllllmmmmmonnnnnnnnnnnnnnnnnnninniininnnnnnnnnnnnnnnnommmmmmmmmmlllo.............................',
    '............................ololllllmmmmmmlhnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnommmmmmmmmmllol..............................',
    '.............................bolllmmmmmmmmmmonnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnolmmmmmmmmmmmlllo..............................',
    '.............................olollmmmmmmmmmmmlonnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnhommmmmmmqmqmqlllo...............................',
    '..............................olollqqmmmmmmmmmmlonnnnnnnnnnnnnnnnnnnnnnnnnnnnolqqqmmqqqqqqqqqqqlr...............................',
    '..............................rlollqqmmmmmmmmmmmmmoohnnnnnnnnnnnnnnnnnnnnhoommmqqqqqqqqqqqqqqqlr................................',
    '...............................roolqqqqqqqqqqqqqmmmqqqooohnnnnnnnnnnnooolmqmqqqqqqqqqqqqqqqqqoo.................................',
    '................................oloqqqqqqqqqqqqqqqqqqqqqqqqqqoooooqqqqqqqqqqqqqqqqqqqqqqqqqqqo..................................',
    '.................................oooqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqor..................................',
    '.................................oloqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqo...................................',
    '.................................oclqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqlr...................................',
    '.................................nblmqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqlr...................................',
    '..................................bllmmqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqll....................................',
    '..................................hllmmmmqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqmmmmlo....................................',
    '..................................nclmmmmmqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqmmmmqlo....................................',
    '..................................nclmmmmmmqqqqqqqrqqqqqqqqqqqqqqqqqqqqqqqrrrqqqqqqqmmmmmqlr....................................',
    '...................................blmmmmmmmqqqqqqrrrrrrrrrrrrrrrrrrrrrrrrrrqqqqqqqmmmmmmql.....................................',
    '...................................ollmmmmmmmqqqqqrrrst................srrrqqqqqqqmmmmmmqlo.....................................',
    '...................................hjlmmmmmmmqqqqqrrrrt................srrrqqqqqqqmmmmmmqlo.....................................',
    '...................................hclmmmmmmqqqqqqqrrr..................rrrqqqqqqqqmmmmqqlr.....................................',
    '...................................ncmmmmmmmqqqqqqqrrs..................srrqqqqqqqqqqqqqql......................................',
    '....................................cmmmmmmmqqqqqqqrr....................rqqqqqqqqqqqqqqqo......................................',
    '....................................ommmmqqqqqqqqqrrs....................rqrqqqqqqqqqqqqqr......................................',
    '....................................rrqqqqqqqqqqqqrr......................rqqqqqqqqqrrrssss.....................................',
    '...................................sssssssrrrrqqqqrt......................trrrrrstttttttssss....................................',
    '.................................ssssssssttttttttttt......................tttttttttttttssssss...................................',
    '................................sssssssssssstttttttt.....................ttttttttttttttssstsss..................................',
    '...............................ssssssssttssstttttttt.....................tttttttttttttssssttsss.................................',
    '..............................ssssssssstttsstttttttt......................tttttttsstttssssstsss.................................',
    '..............................ssstsssssttsssstttttt........................tttttssssttssssstsss.................................',
    '..............................ssstsssssttssssttttt..........................ttttssssttsssstttss.................................',
    '..............................ssttsssssttsssstttt............................tttssstttssssttttt.................................',
    '...............................ttttssstttsssttt...............................tttsstttttss......................................',
    '...................................ttttt.ttttt...................................tt.............................................',
  ],
  palette: {
    'E': 0xFF2F5A1E,
    'a': 0xFFFEE145,
    'b': 0xFFFDDB35,
    'c': 0xFFFDD72D,
    'd': 0xFFF8DCA3,
    'f': 0xFFF9DA72,
    'g': 0xFFF2D89A,
    'h': 0xFFF6CE64,
    'i': 0xFFE9C88A,
    'j': 0xFFFDD020,
    'k': 0xFFFCC817,
    'l': 0xFFF3BA1B,
    'm': 0xFFF3B605,
    'n': 0xFFE1BD82,
    'o': 0xFFE5B031,
    'q': 0xFFE4A306,
    'r': 0xFFC7932C,
    's': 0xFF7D6D53,
    't': 0xFF5A4F41,
  },
);
