// 电子宠物像素图：蜗牛：奶油身体 + 螺旋壳。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt snailArt = BuddyPixelArt(
  rows: [
    '....kk..........kk..............',
    '....kk..........kk..............',
    '....kk..........kk..............',
    '....kk..........kk..............',
    '....bbH........HbS..............',
    '....bbbHH....HHbbS..............',
    '....bbbbbHHHHbbbbS..............',
    '....bbbbbbbbbbbbbS..............',
    '....bbbEEbbbbbbEEE...ssssss.....',
    '....bbEEEEbbbbEEEE.ssssssssss...',
    '....bbEEEEbbbbEEEEssssssssssss..',
    '....bbbEEbbbbbbEEsssssssssssss..',
    '....bbbbbbbbbbbbsssddddsssss....',
    '....bbbbbbbbbbbbssddddddssss....',
    '....bbppbbbbbbbbssddssddsssss...',
    '....bbpppbbbbbbbssddssdddsssss..',
    '....bbppppbbbbbbssddddddddssss..',
    '....bbbpppbbbbbbsssdddddddsss...',
    '....bbbbbbbbbbbbsssssssssssss...',
    '....bbbbbbbbbbbbbsssssssssss....',
    '....bbbbbbbbbbbbbsssssssssss....',
    '....bbbbbbbbbbbbbbbsssssssss....',
    '....bbbbbbbbbbbbbbbbbbbbbbbb....',
    '...HbbbbbbbbbbbbbbbbbbbbbbbbS...',
    '...bbbbbbbbbbbbbbbbbbbbbbbbbb...',
    '..HbbbbbbbbbbbbbbbbbbbbbbbbbbS..',
    '..SbbbbbbbbbbbbbbbbbbbbbbbbbbS..',
    '...SSSSSSSSSSSSSSSSSSSSSSSSSS...',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  palette: {
    'b': 0xFFEFD9A7,
    's': 0xFFC98A5B,
    'd': 0xFFA96A3E,
    'k': 0xFF8A6A4A,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFC4B289,
    'H': 0xFFF3E1BA,
  },
);
