// 电子宠物像素图：蜗牛：奶油身体 + 螺旋壳。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt snailArt = BuddyPixelArt(
  rows: [
    '..................kkkk............................................kkkk..........................................................',
    '.................kkkkkk..........................................kkkkkk.........................................................',
    '.................kkkkkk..........................................kkkkkk.........................................................',
    '................kkkkkkkk........................................kkkkkkkk........................................................',
    '................kkkkkkkk........................................kkkkkkkk........................................................',
    '................kkkkkkkk........................................kkkkkkkk........................................................',
    '................kkkkkkkk........................................kkkkkkkk........................................................',
    '................kkkkkkkk........................................kkkkkkkk........................................................',
    '................kkkkkkkk........................................kkkkkkkk........................................................',
    '................kkkkkkkk........................................kkkkkkkk........................................................',
    '................kkkkkkkk........................................kkkkkkkk........................................................',
    '................kkkkkkkk........................................kkkkkkkk........................................................',
    '................kkkkkkkk........................................kkkkkkkk........................................................',
    '................kkkkkkkk........................................kkkkkkkk........................................................',
    '................kkkkkkkk........................................kkkkkkkk........................................................',
    '................kkkkkkkk........................................kkkkkkkk........................................................',
    '................bbbbbbbbH......................................HbbbbSSSS........................................................',
    '................bbbbbbbbbHH..................................HHbbbbbSSSS........................................................',
    '................bbbbbbbbbHHHH..............................HHHHbbbbbSSSS........................................................',
    '................bbbbbbbbbbHHHHH..........................HHHHHbbbbbbSSSS........................................................',
    '................bbbbbbbbbbHHHHHHH......................HHHHHHHbbbbbbSSSS........................................................',
    '................bbbbbbbbbbbHHHHHHHH..................HHHHHHHHbbbbbbbSSSS........................................................',
    '................bbbbbbbbbbbbbHHHHHHHH..............HHHHHHHHbbbbbbbbbSSSS........................................................',
    '................bbbbbbbbbbbbbbbHHHHHHHH..........HHHHHHHHbbbbbbbbbbbSSSS........................................................',
    '................bbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbSSSS........................................................',
    '................bbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHHbbbbbbbbbbbbbbbSSSS........................................................',
    '................bbbbbbbbbbbbbbbbbbbbbHHHHHHHHHHHHHHbbbbbbbbbbbbbbbbbSSSS........................................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbHHHHHHHHHHbbbbbbbbbbbbbbbbbbbSSSS........................................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................................................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........................................................',
    '................bbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEE...............ssssssssssssssssss.......................',
    '................bbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEE.............ssssssssssssssssssssss.....................',
    '................bbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEE...........ssssssssssssssssssssssssss...................',
    '................bbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEE.........ssssssssssssssssssssssssssssss.................',
    '................bbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEE.......ssssssssssssssssssssssssssssssssss...............',
    '................bbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEE.....ssssssssssssssssssssssssssssssssssssss.............',
    '................bbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEE...ssssssssssssssssssssssssssssssssssssssssss...........',
    '................bbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEE.sssssssssssssssssssssssssssssssssssssssssssss..........',
    '................bbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEssssssssssssssssssssssssssssssssssssssssssssss..........',
    '................bbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEssssssssssssssssssssssssssssssssssssssssssssssss.........',
    '................bbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEssssssssssssssssssssssssssssssssssssssssssssssss.........',
    '................bbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEssssssssssssssssssssssssssssssssssssssssssssssssss........',
    '................bbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEssssssssssssssssssssssssssssssssssssssssssssssssss........',
    '................bbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEssssssssssssssssssssssssssssssssssssssssssssssssss.........',
    '................bbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEssssssssssssssssssssssssssssssssssssssssssssssssssss.........',
    '................bbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEssssssssssssssssssssssssssssssssssssssssssssssssssss...........',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssssddddddddddssssssssssssssssssssssssss.............',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssddddddddddddddssssssssssssssssssssss...............',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssddddddddddddddddddssssssssssssssssssss...............',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssssddddddddddddddddddddssssssssssssssssss................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssssddddddddddddddddddddssssssssssssssssss................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssddddddddddddddddddddddssssssssssssssssss...............',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssddddddddddddddddddddddssssssssssssssssss...............',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssddddddddddddddddddddddddssssssssssssssssss..............',
    '................bbbbbbbbbbbppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssdddddddddddssdddddddddddssssssssssssssssss..............',
    '................bbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssdddddddddssssssddddddddddssssssssssssssssss.............',
    '................bbbbbbbbbppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssdddddddddssssssddddddddddssssssssssssssssssss...........',
    '................bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssddddddddssssssssddddddddddssssssssssssssssssss..........',
    '................bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssddddddddssssssssddddddddddssssssssssssssssssss..........',
    '................bbbbbbbbpppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssdddddddddssssssddddddddddddssssssssssssssssssss.........',
    '................bbbbbbbbpppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssdddddddddssssssddddddddddddddssssssssssssssssss.........',
    '................bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssdddddddddddssdddddddddddddddddssssssssssssssssss........',
    '................bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssddddddddddddddddddddddddddddddssssssssssssssssss........',
    '................bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssddddddddddddddddddddddddddddddssssssssssssssss.........',
    '................bbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssddddddddddddddddddddddddddddddssssssssssssssss.........',
    '................bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbssssssssssddddddddddddddddddddddddddddddssssssssssssss..........',
    '................bbbbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbssssssssssddddddddddddddddddddddddddddddssssssssssssss..........',
    '................bbbbbbbbbbbppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssddddddddddddddddddddddddddddssssssssssssss...........',
    '................bbbbbbbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssddddddddddddddddddddddddddssssssssssssss...........',
    '................bbbbbbbbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssssddddddddddddddddddddddsssssssssssssss............',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssssssssssssssssssssssssssssssssss............',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssssssssssssssssssssssssssssssss.............',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssssssssssssssssssssssssssssssss.............',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssssssssssssssssssssssssssssss..............',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssssssssssssssssssssssssssssss..............',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssssssssssssssssssssssssssss...............',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssssssssssssssssssssssssssss...............',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssssssssssssssssssssssssss................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssssssssssssssssssssssssss................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssssssssssssssssssssssssssssssss................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssssssssssssssssssssssssssssssss................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssssssssssssssssssssssssssssss................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssssssssssssssssssssssssssss................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssssssssssssssssssssssssss................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssssssssssssssssssssssss................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssssssssssssssssssssss................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '................bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb................',
    '...............HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...............',
    '.............HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............',
    '.............HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.............',
    '............HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS............',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb............',
    '...........HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS...........',
    '.........HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.........',
    '.........HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS.........',
    '........HHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........',
    '........SSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS........',
    '.........SSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.........',
    '.........SSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS.........',
    '..........SSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSS..........',
    '..........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..........',
    '...........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........',
    '.............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.............',
    '...............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...............',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    'b': 0xFFEFD9A7,
    's': 0xFFC98A5B,
    'd': 0xFFA96A3E,
    'k': 0xFF8A6A4A,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFC4B289,
    'H': 0xFFF3E1BA,
  },
);
