// 电子宠物像素图：蜗牛：奶油身体 + 螺旋壳。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt snailArt = BuddyPixelArt(
  rows: [
    '.........kk......................kk.............................',
    '........kkkk....................kkkk............................',
    '........kkkk....................kkkk............................',
    '........kkkk....................kkkk............................',
    '........kkkk....................kkkk............................',
    '........kkkk....................kkkk............................',
    '........kkkk....................kkkk............................',
    '........kkkk....................kkkk............................',
    '........bbbbH..................HbbSS............................',
    '........bbbbbHH..............HHbbbSS............................',
    '........bbbbbHHHH..........HHHHbbbSS............................',
    '........bbbbbbbHHHH......HHHHbbbbbSS............................',
    '........bbbbbbbbbHHHHHHHHHHbbbbbbbSS............................',
    '........bbbbbbbbbbbHHHHHHbbbbbbbbbSS............................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbSS............................',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbSS............................',
    '........bbbbbbbEEbbbbbbbbbbbbbbEEEEE.......ssssssssss...........',
    '........bbbbbEEEEEEbbbbbbbbbbEEEEEEE.....ssssssssssssss.........',
    '........bbbbbEEEEEEbbbbbbbbbbEEEEEEE...ssssssssssssssssss.......',
    '........bbbbEEEEEEEEbbbbbbbbEEEEEEEE.ssssssssssssssssssssss.....',
    '........bbbbEEEEEEEEbbbbbbbbEEEEEEEEsssssssssssssssssssssss.....',
    '........bbbbbEEEEEEbbbbbbbbbbEEEEEEsssssssssssssssssssssssss....',
    '........bbbbbEEEEEEbbbbbbbbbbEEEEEEsssssssssssssssssssssssss....',
    '........bbbbbbbEEbbbbbbbbbbbbbbEEssssssssssssssssssssssssss.....',
    '........bbbbbbbbbbbbbbbbbbbbbbbbsssssssddddddssssssssssss.......',
    '........bbbbbbbbbbbbbbbbbbbbbbbbsssssddddddddddsssssssss........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbsssssddddddddddsssssssss........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbssssddddddddddddsssssssss.......',
    '........bbbbbppbbbbbbbbbbbbbbbbbssssdddddssdddddsssssssss.......',
    '........bbbbpppppbbbbbbbbbbbbbbbssssddddssssdddddssssssssss.....',
    '........bbbbpppppbbbbbbbbbbbbbbbssssddddssssdddddssssssssss.....',
    '........bbbbpppppppbbbbbbbbbbbbbssssdddddssddddddddsssssssss....',
    '........bbbbpppppppbbbbbbbbbbbbbssssdddddddddddddddsssssssss....',
    '........bbbbbpppppppbbbbbbbbbbbbsssssdddddddddddddddsssssss.....',
    '........bbbbbpppppppbbbbbbbbbbbbsssssdddddddddddddddsssssss.....',
    '........bbbbbbbppppbbbbbbbbbbbbbsssssssddddddddddddsssssss......',
    '........bbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssssssss......',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssssss.......',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssssss.......',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssss........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbssssssssssssssssssssss........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssssssssss........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssssssss........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssssss........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........',
    '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb........',
    '.......HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS.......',
    '......HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS......',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb......',
    '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb......',
    '.....HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbS.....',
    '....HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS....',
    '....SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS....',
    '.....SSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSS.....',
    '.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.....',
    '.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    'b': 0xFFEFD9A7,
    's': 0xFFC98A5B,
    'd': 0xFFA96A3E,
    'k': 0xFF8A6A4A,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFFC4B289,
    'H': 0xFFF3E1BA,
  },
);
