// 电子宠物像素图：乌龟：绿色 + 格纹壳。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt turtleArt = BuddyPixelArt(
  rows: [
    '................................',
    '................................',
    '................................',
    '................................',
    '.........ssssssssssssss.........',
    '.......ssssssssssssssssss.......',
    '.......sssddssssddssssdds.......',
    '.....ssssdddsssdddsssdddsss.....',
    '.....sssdddsssdddsssdddssss.....',
    '....sssdddsssdddsssdddssssss....',
    '....ssdddsssdddsssdddsssddss....',
    '....ssddssssddssssddssssddss....',
    '....ssssssssssssssssssssssss....',
    '....ssssssssssssssssssssssss....',
    '...HbbbbbbbbbbbbbbbbbbbbbbbbH...',
    '.HHbbbbbbbbbbbbbbbbbbbbbbbbbbHS.',
    '.bbbbEEbbbbbbbbbbbbbbbbbbEEbbbb.',
    'HbbbEEEEbbbbbbbbbbbbbbbbEEEEbbbS',
    'bbbbEEEEbbbbbbbbbbbbbbbbEEEEbbbS',
    'bbbbbEEbbbbbbbbbbbbbbbbbbEEbbbbS',
    'bbppbbbbbbbbbbbbbbbbbbbbbbbbppbS',
    'bbpppbbbbbbbbbbbbbbbbbbbbbbpppbS',
    'SbppppbbbbbbbbbbbbbbbbbbbbppppbS',
    '.bbpppbbbbbbbbbbbbbbbbbbbbpppbS.',
    '.SSbbbbbbbbbbbbbbbbbbbbbbbbbbSS.',
    '...bbbbbbSSbbbbbbbbbbSSbbbbbS...',
    '...SbbbbS..SSbbbbbbSS..SbbbbS...',
    '....bbbS.....bbbbbS.....bbbS....',
    '....SbbS.....SSbbSS.....SbbS....',
    '.....SS........SS........SS.....',
    '................................',
    '................................',
  ],
  palette: {
    's': 0xFF7FB069,
    'd': 0xFF5E8A4C,
    'b': 0xFFB6D89A,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF95B17E,
    'H': 0xFFC6E1B0,
  },
);
