// 电子宠物像素图：乌龟：绿色 + 格纹壳。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt turtleArt = BuddyPixelArt(
  rows: [
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '.......................................ssssssssssssssssssssssssssssssssssssssssssssssssss.......................................',
    '.....................................ssssssssssssssssssssssssssssssssssssssssssssssssssssss.....................................',
    '...................................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssss...................................',
    '.................................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.................................',
    '...............................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss...............................',
    '.............................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.............................',
    '.............................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.............................',
    '............................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss............................',
    '............................sssssssssssssssddssssssssssssssssssssssddssssssssssssssssssssssddsssssss............................',
    '...........................ssssssssssssssddddddssssssssssssssssssddddddssssssssssssssssssddddddssssss...........................',
    '...........................ssssssssssssddddddddssssssssssssssssddddddddssssssssssssssssddddddddssssss...........................',
    '.........................sssssssssssssddddddddddssssssssssssssddddddddddssssssssssssssddddddddddsssssss.........................',
    '.......................sssssssssssssssddddddddddssssssssssssssddddddddddssssssssssssssddddddddddsssssssss.......................',
    '.....................ssssssssssssssssddddddddddssssssssssssssddddddddddssssssssssssssddddddddddssssssssssss.....................',
    '.....................ssssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssddddddddddddssssssssssss.....................',
    '....................ssssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssss....................',
    '....................ssssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssss....................',
    '...................ssssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssssss...................',
    '...................ssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssssssss...................',
    '..................ssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssssssssss..................',
    '..................ssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssssssssss..................',
    '.................ssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssssssssssss.................',
    '.................ssssssssssddddddddddddssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssssssssssssss.................',
    '................ssssssssssddddddddddddssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssssssssssssssss................',
    '................ssssssssssddddddddddddssssssssssssddddddddddddssssssssssssddddddddddddsssssssssssssddsssssssssss................',
    '................sssssssssddddddddddddssssssssssssddddddddddddssssssssssssddddddddddddssssssssssssddddddsssssssss................',
    '................sssssssssddddddddddssssssssssssssddddddddddssssssssssssssddddddddddssssssssssssssddddddsssssssss................',
    '................ssssssssddddddddddssssssssssssssddddddddddssssssssssssssddddddddddssssssssssssssddddddddssssssss................',
    '................ssssssssddddddddddssssssssssssssddddddddddssssssssssssssddddddddddssssssssssssssddddddddssssssss................',
    '................sssssssssddddddddssssssssssssssssddddddddssssssssssssssssddddddddssssssssssssssssddddddsssssssss................',
    '................sssssssssddddddssssssssssssssssssddddddssssssssssssssssssddddddssssssssssssssssssddddddsssssssss................',
    '................sssssssssssddssssssssssssssssssssssddssssssssssssssssssssssddssssssssssssssssssssssddsssssssssss................',
    '................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss................',
    '................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss................',
    '................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss................',
    '................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss................',
    '................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss................',
    '................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss................',
    '................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss................',
    '................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss................',
    '...............HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbH...............',
    '.............HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHH.............',
    '...........HHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHH...........',
    '.........HHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHH.........',
    '.......HHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHHS.......',
    '.....HHHHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHHHSSS.....',
    '.....HHHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHSSS.....',
    '....HHHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHSSSS....',
    '....bbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbb....',
    '....bbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbb....',
    '....bbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbb....',
    '....bbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbb....',
    '...HbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbS...',
    '.HHbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSS.',
    'HHHbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS',
    'HbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEEEbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEEEbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEEEbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEEEbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbSSSS',
    'bbbbbbbbbbbppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppbbbbbbbSSSS',
    'bbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbSSSS',
    'bbbbbbbbbppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppbbbbbSSSS',
    'bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbSSSS',
    'bbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbSSSS',
    'bbbbbbbbpppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpppppppppppbbbbSSSS',
    'bbbbbbbbpppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpppppppppppppbbbbSSSS',
    'bbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS',
    'SbbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS',
    'SSSbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSSS',
    '.SSbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS.',
    '...SbbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS..',
    '....bbbbbbppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppppbbbbSSSS..',
    '....bbbbbbbppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppppbbbbSSSS...',
    '....bbbbbbbbbppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppppppbbbbSSSSSS...',
    '....bbbbbbbbbbbppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppppbbbbbSSSSSS....',
    '....SSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSS....',
    '.....SSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSS.....',
    '.....SSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSS.....',
    '.......SSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSS.......',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbbbSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSbbbbbbbbbbbbbbbbbbbbbbbbbSSSSS.........',
    '............bbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSbbbbbbbbbbbbbbbbbbbbbbSSSS...........',
    '............bbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSbbbbbbbbbbbbbbbbbbbbSSSS...........',
    '............bbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSSSSSSSbbbbbbbbbbbbbbbbbbSSSS............',
    '............SbbbbbbbbbbbbbbbbbbbbbSSSSS..SSSSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSS..SSSSSbbbbbbbbbbbbbbbbbbSSSS............',
    '.............SSbbbbbbbbbbbbbbbbbbSSSS......SSSSSSSSbbbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSS......SSSSbbbbbbbbbbbbbbbbSSSS.............',
    '.............SSbbbbbbbbbbbbbbbbSSSS..........SSSSSSbbbbbbbbbbbbbbbbbbbbbbbbSSSSSSSS..........SSbbbbbbbbbbbbbbbbSSSS.............',
    '...............SbbbbbbbbbbbbbbSSSS.............SSSSSbbbbbbbbbbbbbbbbbbbbbbSSSSSSS..............SbbbbbbbbbbbbbbSSSS..............',
    '................bbbbbbbbbbbbbbSSSS..................bbbbbbbbbbbbbbbbbbbbbbSSSSS.................bbbbbbbbbbbbbbSSSS..............',
    '................bbbbbbbbbbbbbSSSS...................bbbbbbbbbbbbbbbbbbbbbSSSS...................bbbbbbbbbbbbbSSSS...............',
    '................bbbbbbbbbbbbbSSSS...................bbbbbbbbbbbbbbbbbbbSSSSSS...................bbbbbbbbbbbbbSSSS...............',
    '................bbbbbbbbbbbbSSSS....................bbbbbbbbbbbbbbbbbbSSSSSS....................bbbbbbbbbbbbSSSS................',
    '................SbbbbbbbbbbbSSSS....................SSSSSbbbbbbbbbbbbbSSSSSS....................SbbbbbbbbbbbSSSS................',
    '.................SSbbbbbbbbSSSS......................SSSSSSbbbbbbbbbbSSSSSS......................SSbbbbbbbbSSSS.................',
    '.................SSSSbbbbbbSSSS......................SSSSSSSSbbbbbbSSSSSSSS......................SSSSbbbbbbSSSS.................',
    '..................SSSSSbbSSSSS.........................SSSSSSSSbbSSSSSSSS.........................SSSSSbbSSSSS..................',
    '..................SSSSSSSSSSSS...........................SSSSSSSSSSSSSS...........................SSSSSSSSSSSS..................',
    '...................SSSSSSSSSS..............................SSSSSSSSSS..............................SSSSSSSSSS...................',
    '.....................SSSSSS..................................SSSSSS..................................SSSSSS.....................',
    '.......................SS......................................SS......................................SS.......................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
    '................................................................................................................................',
  ],
  palette: {
    's': 0xFF7FB069,
    'd': 0xFF5E8A4C,
    'b': 0xFFB6D89A,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF95B17E,
    'H': 0xFFC6E1B0,
  },
);
