// 电子宠物像素图：乌龟：绿色 + 格纹壳。32×32，字符 → 调色板；`.` 透明，
// `E` 眼睛（渲染器负责眨眼/高光），`p` 腮红。

import 'pixel_art.dart';

const BuddyPixelArt turtleArt = BuddyPixelArt(
  rows: [
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
    '...................ssssssssssssssssssssssssss...................',
    '.................ssssssssssssssssssssssssssssss.................',
    '...............ssssssssssssssssssssssssssssssssss...............',
    '..............ssssssssssssssssssssssssssssssssssss..............',
    '..............sssssssddssssssssssddssssssssssddsss..............',
    '.............ssssssdddddsssssssdddddsssssssdddddsss.............',
    '...........ssssssssdddddsssssssdddddsssssssdddddsssss...........',
    '..........sssssssddddddssssssddddddssssssddddddsssssss..........',
    '..........sssssssddddddssssssddddddssssssddddddsssssss..........',
    '.........ssssssddddddssssssddddddssssssddddddssssssssss.........',
    '.........ssssssddddddssssssddddddssssssddddddssssssssss.........',
    '........sssssddddddssssssddddddssssssddddddsssssssssssss........',
    '........sssssddddddssssssddddddssssssddddddssssssddsssss........',
    '........ssssdddddsssssssdddddsssssssdddddsssssssddddssss........',
    '........ssssdddddsssssssdddddsssssssdddddsssssssddddssss........',
    '........sssssddssssssssssddssssssssssddssssssssssddsssss........',
    '........ssssssssssssssssssssssssssssssssssssssssssssssss........',
    '........ssssssssssssssssssssssssssssssssssssssssssssssss........',
    '........ssssssssssssssssssssssssssssssssssssssssssssssss........',
    '........ssssssssssssssssssssssssssssssssssssssssssssssss........',
    '.......HbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbH.......',
    '.....HHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHH.....',
    '...HHHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHHHS...',
    '..HHHbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbHSS..',
    '..bbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbb..',
    '..bbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbb..',
    '.HbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbS.',
    'HbbbbbbbEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEbbbbbbSS',
    'bbbbbbbbEEEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEEEbbbbbbSS',
    'bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS',
    'bbbbbbbbbEEEEEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEEEEEbbbbbbbSS',
    'bbbbbbbbbbbEEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbEEbbbbbbbbbSS',
    'bbbbbppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppbbbSS',
    'bbbbpppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpppppbbSS',
    'bbbbpppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpppppbbSS',
    'bbbbpppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpppppppbbSS',
    'SbbbpppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpppppppbbSS',
    '.SbbbpppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpppppppbbSS.',
    '..bbbpppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpppppppbbSS.',
    '..bbbbbppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppppbbSSS..',
    '..SSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSS..',
    '...SSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbSSSS...',
    '......bbbbbbbbbbbbbSSbbbbbbbbbbbbbbbbbbbbbbSSbbbbbbbbbbbbSS.....',
    '......bbbbbbbbbbbSSSSSSbbbbbbbbbbbbbbbbbbSSSSSSbbbbbbbbbSS......',
    '......SbbbbbbbbbbSS..SSSSbbbbbbbbbbbbbbSSSS..SSbbbbbbbbbSS......',
    '.......SbbbbbbbSS......SSSbbbbbbbbbbbSSSS......SbbbbbbbSS.......',
    '........bbbbbbbSS.........bbbbbbbbbbbSS.........bbbbbbbSS.......',
    '........bbbbbbSS..........bbbbbbbbbSSS..........bbbbbbSS........',
    '........SbbbbbSS..........SSSbbbbbbSSS..........SbbbbbSS........',
    '.........SSbbSS............SSSSbbSSSS............SSbbSS.........',
    '.........SSSSSS..............SSSSSS..............SSSSSS.........',
    '...........SS..................SS..................SS...........',
    '................................................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
  palette: {
    's': 0xFF7FB069,
    'd': 0xFF5E8A4C,
    'b': 0xFFB6D89A,
    'E': kBuddyEyeColor,
    'p': kBuddyBlushColor,
    'S': 0xFF95B17E,
    'H': 0xFFC6E1B0,
  },
);
