// 月薪喵：以 Codex Pets 官方月薪喵精灵图（待机第 1 帧）为参考
// 量化的 128×128 高清像素版——白灰办公室小猫、圆眼黑瞳、呆耳竖尾。

import 'pixel_art.dart';

const BuddyPixelArt yuexinmiaoArt = BuddyPixelArt(
  rows: [
    '................................ssss.........................................................ssss...............................',
    '..............................ssrrrrss.....................................................ssrrrrs..............................',
    '..............................rtrrrrrrss.................................................srtrrrrrts.............................',
    '.............................srrtttttttrs...............................................srttttttttrs............................',
    '............................srrtrqqsttrrrs............................................ssrrrtrqoqtrrs............................',
    '............................stttqmmmqrtrrrr..........................................srtrttqolllstrrs...........................',
    '............................sttrononlostrrtr........................................srrrtrolmnolqtrrs...........................',
    '............................rrtqlnmnommqttttr......................................srrrtsoloooonotrrs...........................',
    '...........................srrtqloooooomqttttr....................................rttttqnoooooooorrrs...........................',
    '...........................srrtomooooooomqtrrrr.................................srtrttqmoooooooomstrr...........................',
    '...........................srrtomoooooooolorrrrrssssssssssssssssssssssssssssssssrttttqlonnnonooomqttr...........................',
    '...........................srtromoooooonmolortrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrtrttqlonmmmnnnoomqttrs..........................',
    '...........................sttronnnnnnnnnnomotttttttttttrrrtttttttttttttttttrrrrrtromooooonnnnnomqtrrs..........................',
    '...........................srtrmonnnnnmnnnoomosrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrsolonoooonmnnnomqtrts..........................',
    '...........................srtsmonooooooooooommoooooooooooooooooooooooooooooooooonmonnooonoonooomotrrs..........................',
    '...........................rrtslnmnooooooooonoommmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnonnooooooonooomotrrs..........................',
    '..........................srrtqlnmmmmnnnnnnnnooooonnnoooooooonnmmmnnnnnnnnnoooooonnnnnnnooooonnomorrrs..........................',
    '..........................srrtqlomnnnnmnnmmnnnnnnnnnnoooooonmmooooommnnnmmmmmnnnnnnnnnnnnnnnnnnnmorrrr..........................',
    '..........................srrtqlonnnnnmnnmmnmmmmmnmnnnnnnoooomllllmoomnnnnnnnmmnnnnnnnnnnnnmnnnnmorttr..........................',
    '.........................srrrtqlomnmmmnmmnnnmmmmmmmmmmmmmmnmlkkiifkklommmmmmmmmmnmmnnnnnnnnnnnnnnmrtrtr.........................',
    '........................srtrtromnmmmmmmmmnnnnnnnmmmmmmmmmmlkaajkkjgailnmmmmmmmmmmnnnmnnnnnnnnnnnomotrrrs........................',
    '........................strtrolnmmmmmmmnnnmmnnmmmmmnnnnmolkajdfjiijkkalonnmmmmmmmnnnnnnnnnnmmnoooomqtrrrs.......................',
    '.......................srrrrolommmmmnnnnnnnmmmmnnnnnoooolkaicaaaabccdjalommmmmnnnonnoonnnnnnnoooooolqtrrrs......................',
    '......................srrrtolonnmnnnnnnmmmmmmnmmmmmmmmomkakccbcbcgaacikalomnnmmmmmnmnnooooonnnnnnnmmmstrtr......................',
    '.....................srrrtqmoononnnmmmmmmmmmnnoqqqommmmkakbcciicigddcijjklooooqqqommmnnnnoonnnnmmnmnmortrts.....................',
    '....................srrrtqlonnnmnnnmmmmmmmmmmmqqqqqomolakicgccggijiicccfbklomqqqqqomonnnnonmmmmnmmnnomotrrrs....................',
    '...................srtrtqlommmmmnnnnnnnnnmmmmoqqqqqqmljjjijjjgjiiiijjjjciakloqqqqqqmonnnnnmmmmmmmmmmmolqtrtrs...................',
    '..................srrrtqlommmnnnnnnnnnnnonnomqqqqqqqlkajdjgggdfjdjiiddjjjkckoqqqqqqmonnnnnnnmmmmmnmmmmnmstrtr...................',
    '.................srrrtsnoonnnnmmmnmnnnnnnnoomqqqqqqqkgkcddiccgigdgbadiiijkkfoqqqqqqmmmmnnnnnnnnnmmmmmmnmortrts..................',
    '................srrrtromononnnnnmmmnnmnnnnnomqqqqqqqakjfgjdddccccaaaabdjdikalqqqqqqmmmmmmnnnnnnnnmmmmmmomotrrrs.................',
    '................strtromooononnnnmmnmmmmnnnnomqqqqqqqakjbciiiiddgcdicccgcbakalqqqqqqmnnmmnmmmnmnnnnnmmnnmolqtrtrs................',
    '...............srrtromooooononnnmnnmmmmmnnnomqqqqqqqakjiigjjjggciiccccjcbakalqqqqqqmnnnnnnnnmmnnnnmmmmmmmolstrtr................',
    '..............srrrtolonnnnnnnnnnnnnnnmnonnnomqqqqqqqakjiihbddjiccijjigjccbkalqqqqqqmonooooonnnnmmmmmmmmmmonortrrs...............',
    '.............srrrtqlonnnnnnmnnnnnnnnnnnnnnnnmqqqqqqqakjiibabbbbjkjcdiijgiikalqqqqqqmnnooooonnmmnnmmmmmmmnoomotrrrs..............',
    '............srtrtqloonnnnnnnnnmnnnnnnnnnnmmomqqqqqqqakjdjjjcajkaaikjjkkkjckalqqqqqqmnnnnnnnnnnnmnnnmmmmmmnmolqtrtt..............',
    '...........srtrtsmooonnnnnonnnmnmnnmnmnmnnmomqqqqqqqajjaaaajkaaklkajkaaaaakalqqqqqqmmmmmnnmmnnnnnnnnmmnnmmmnnmstttr.............',
    '..........ssrrtsnooooooonnnnnnnnmmmmmmmmnnnomqqqqqqqajkaoqojakqrEqlaakqokdkalqqqqqqmmmmmmmmmmmmmmnmnnnnnnnnnomortrrs............',
    '..........srrtromoooooooonnmmnmmmmmmmmmmnnnomqqqqqqqakalEEEqqrtErErqqsEEoakalqqqqqqmmmnnonnmnmmmmmmmmmmnnnoooomqtrrs............',
    '.........srrtromoooooooonnnnmmnmnmmnnmmnnnnomqqqqqqqakalErrttrrrErrEEErEqakalqqqqqqlmmnnnnnnnmmmmmnmmmmnnoooooomqtrrs...........',
    '.........sttromoooooonnnmmmmmmmnmnnnnnnnnnnollqqqqqqakkkqEErrrtrsEErrEEElckalqqqqqqknmmmnnnnnnmmmmmnnmnnmnnnooomortrrs..........',
    '..........ss.lmoonooonnnnmmmnnnnnnnnnnnmmmmmklqqqqqqakkkkqrtrsqlkorEEEslajkalqqqqqqklomnnonnnnnmmnnnnnononmmmmmnlottts..........',
    '.............lloooooooononnnnmnnnnmmmmmmmmnkakqqqqqqakkkkakllkaaaaklllkajakckqqqqqqakmnmmmmmmmmnnmnoooonnnnnmmnnomssr...........',
    '.............llmmmoooonnnoonnnmmnmmmmmmmmolkkbqqqqqkjjabikaaaajijkcaaajkijkkaqqqqqkkgknmmmmmmmmmmmnnonnnnmnnnonoon..............',
    '.............mloqqmoonmnnnnnmmmmnnnnnnnmnmkjkkclqokajcaaacjkkjiijikkkkjcahbijalqokajialononnnnmnnnnnonmnnnnoonoooo..............',
    '..............otttqlommnnmmmnmmnnnnmmnnmmkajaccaaaajaabccjdjgjjjiiiidbcaaaabccaaaajikikmonnnnmmnmmmnnonnnnoonqrsom..............',
    '..............strtqlonnmmnnmmnnmmmmnnmmnlajcahjkkkjcddgjjccgdijibadcddcbcbcdjikkkjjjjkakommmmmmmmmnnnnnnnnomorrtqm..............',
    '.............srrrromonnnnnnnmnnmmmmmmmmlkiicijijdididhbhidchdcdbccdcddiiicijjjjihdcidijalnmmmmmmmnnoooonnnomorrrrs..............',
    '............srrrtolomnnnnnnnnnnmmnmmmmokakgdcdjjggicjjdccigiiijhhijjiiidihidcbcccichdgjiklnmmmnnnmnnnmnnnnoomqtrrr..............',
    '...........srtttqlonnnnmnnnnmmmmmmmnmolajciigjgcjdhbbidjibdfddjdgdddiihdffhdgiicgidjigfkakommmnnnmnmnmmmmnnnnmstrrs.............',
    '...........rtttqmonmmmmmmmmnnnmmmmmmmlkijiiddiggdjiddjiccigiiddcdiicbgddcjiicjiidcbdidjiialommmnnnmnnmmmnnnnonortrts............',
    '..........srrtsmmoooononmnnnonnnnmmmmkajjddigjdjdddgijgiiiididddifggjggciiddcjdcchbhijccjiklnmmmmmmnmmmnnnoooomorrrrs...........',
    '..........ssss.llomlmoooonnmnnnnnmmolakjgciidijgiijiidciiddgidddiigidgdbddjjjddjjihigggjijaknmmmmmmnnnnnnnomnoolqtrrs...........',
    '................mooqomnnoonnnnmmmmmlkdigjgccjiciijdbiiidcijdddjjfdccgihcccciigiddjgibccccdkalommmnooooooommommmm.srs............',
    '................morttqlonoononnmmmmkakigjgdgigijcdigjigdddjgggddjdddjgidccdjiciggicifjddcbicklmmmnnooonnonqrqol.................',
    '.................qtrtsmonnnnmmmmmnlaidggiddhddiicccijjijgjdccciicjggddgggiiiigiiidcdiiccjidkakoonnnnnmmnlotrtql.................',
    '.................stttqmonnmmmmmmnlkijigiiiiijicdddhcjjggcibccgiicjddiiddiidddidddijdccdcddcijalonoonnnnnlorrts..................',
    '.................srtrooooooonnmmokakjjjdiijjddjcddibhiiiiidiidddddddfdicdcdiijgjjidddicddbcadiklnnooooonmmsrrs..................',
    '................srrtqlmlmmmmmmlolckjjiiicijgijjgdgdijjdccjjiidddbbdddbjcbcchigjcbidiidiiddaacjakommmmmmmmlqttts.................',
    '................srrrqqqqqqooooonkkkjjiiciddddigiccdcddiiiijddiddddidiiddjjdddiccjjjicicccigijikaloooooooooorrrs.................',
    '...............srrrrtttttttttttrljkcjjgiiddfdbhdddifijcdiicddiddidacgccccddddgggjjccdhccabdjcjjksrrrrrrrrrrrrrs.................',
    '...............srrrtrrrrrrrrrtrtqakacjijjjjdccjgciijgjdddihdddiicdgddcjidddggjjdijddiddcbcgadkaqtrrrrrrrrrrrrrs.................',
    '................srrssrrrrrtrrrrtoakcbbaadjcddcidiigjgfigggjjjdcdcciididdjgdddbdddijbcdjjcbccjkaqtrrrrrrrrrrrrrs.................',
    '.....................ssssssrrrtqkjkdiiidcjgddgddbbdidfiddgjgddbdijidddggjggddddddijdicicijiiijjkrtrrrsssssssss..................',
    '..........................srrtskkkcjjijidffibdjgiijiidjddcigciccdfbbiidiccdjjiijijgcjijjjifdcakalrttts..........................',
    '.........................srrrrlakjjjjigjifdigdiciidbiigiicbdjiibidiiicidiiiddicddiicbhccbhbbgjikaotrrr..........................',
    '........................srrrtlakkjijjdgiiddiddidddiidddbdiddddgicbggjjcibddijdcccdddidiiidggjjikkiqtrrs.........................',
    '........................strtqakbccijiggidiiicciiiidccddddicbbdddiiggdcigcdiiccijiggdigjjiiccidbbkilrrrrs........................',
    '.......................srrtskkkaacbcddhdijggjggiggjgiiidbiddddcciggcijciggjddbidgjjddiddiddcacccckaotrts........................',
    '......................srtrtlckdhdicijccciddiggfiiiijiidggibddiiiddcigjddjjididdiiggjigiicbciiddccjjksttts.......................',
    '......................strtqakbcjcijcciiijjggibcdjjjdabicccgdddccchbbigjdbddijcdjjjjcbbjjdbjgciijgakantttr.......................',
    '.....................srrtskkkggjgiciiihjjjgjddgiccbiddiiidbiidhccbddihicdddddbiddddjdbjicabiddcddikkkqtrrs......................',
    '.....................srrtlakdiihjiciiddidddficjiiidcgdccccjjccdgjdbdiiddijdccdcccijhicgddddciidiigikaltrrs......................',
    '....................srrtqakjddgjjjiddggidccdjjiciicdjjgddcijjciicbidciddciicjicdddjjdidddibbbccdccbjkjqtrrs.....................',
    '....................srrrkjkcddgjiijggicidcbbccdiiicdiigddcjjjgjjcbddddjjiiicdcccccgjjdcddddddijdcccjkaltrrr.....................',
    '...................srrtqakjaiiiiccciiijdddidbiccdcbjgggiicbccciiiiicccdcbdggjijjjdiigiicdgdbgddihccbckjqtrrs....................',
    '...................sttrlcjcacciiiidiibcddbbdjiidaajjiddddijjjcddiiggdgddccbggjiiidfidjigcicbddbcbccbbkaltrrs....................',
    '..................srrtqckacccgjcbcdiigjcddddcgjddbigdgiccgcccdjidbjjiiccddcjiidbbdddbiddicjjiiibbbaaakjksttr....................',
    '..................strtlakjjcccaabciccgjcgjjgddfiiicifcdiiidbbciiddjjccjdcijddicdccbdicbcidddijjdfdaaaakaqtrts...................',
    '..................rttskkkkjcababjjijijgidgfgjjidddjgiiiiidgjibdggcjjjfgibbccddidiigchdijggibbjjjgjjidbkjltrtr...................',
    '.................srrtoakijcdijcjcacjijgiiccbifgcbgijgcgciigdiciciccgjhgjiddidijdidgiidjiiijcjaacjgjjijkkkstrr...................',
    '.................srrtlckcijjjkkakkgajdjbcdibcgidciiddgjidiidddiidjjgigdgdcddbcigjcidbiddcbdialljjkjjjijkaqtrrs..................',
    '.................srtrkkkjjjjkkalsrqkjkcccidjjigddidjiddiiciihidjdijiggjidiiiigiggibhdibdcjkaortqkjkababkaltrrs..................',
    '.................srtqkkkajjkcaortrtoakddddgjiicdgjiiggciidcjidijccccccjjjfccidgidbbdjcabajkkstrtqkjkbbckalrrrs..................',
    '.................srtqakjckkakqttrrtoakiijdcbdijjddciiidjjciddibhcjiiiiccjidgbbdjiidjiijjcjkjqtrrtqkakkkkakrrrs..................',
    '.................srtqakkaaklstrttrtlakadjccccdiiddfdiidijdcjgjdjdiiiggibaacjjdgidihjdcddaikaqtrrrtslakkkikrtrs..................',
    '.................srtrkacknqttrrrrrtlakjciggjidijgggiigcbciiididiciijdbddbdiiiicjigdbdjjicjkaqtrrrrtrokaaakttts..................',
    '.................stttsqqrttrrrsrrrrlckhciiijjjfiggdiidgiiiccdigjdbddjiiijgddcidcdjjdddbgcikaqtrrrrrrtsolkqtrrs..................',
    '.................ssrrttttrrtrsssrrrkjkccdiidgiidiiiidddddjidbccidiiijjdccjdciiddgjjicgiidikaotrrssrtrttrrtrtr...................',
    '..................srrrrrrrrss..sttskjkidfiiigiicdbcdddciijiiidiidijigddddcfdfiiiidjiccddcgkaottts.srrrrrrrrrs...................',
    '...................sssssss.....sttskkkijjijiciidddjjiidddjcdddgjdcijiigcciijjcbiidicbbiicgkaltrrs..ssrrrrrrs....................',
    '...............................srtqakkijijijidjiciihbacjjdigdcciggjcbbciiccdihbccddcddbcdjkaltrrs.....ssss......................',
    '...............................rrtqakfdcidggidiciiijiciiibdjgdcdcgdibbccciiiidcddgibijddbbkalrrrs...............................',
    '.................ss............rrtqakdabijjcgjjddidjdjfiidhbbcjiidbdiiiiigddddiggiibcdgcbbkakrtrr...............................',
    '................srrs..........srrtqakjjddjggcddjiiciciidigiiigcjdihiibgijjiiidciigjjdciicijakrtrr...............................',
    '................srrrs.........srrtoakjjbdjjfjjjjddcigdjjgicgiigccigdiiidiigcdfdigiidjgggdfjakstrs...............................',
    '.................srrtrs.......srrtoakijdfgggidddggcjgfigiicibdcgjdbcdggjggjdjjgicbaibcccdadbkstrs...............................',
    '................lqttttrs......srrtnakdccdjjigjbdjjdcdjjgdgjdbccccgjihhjgijdbcdijjcbdabhhjgfikstrr...............................',
    '...............lmmqttttrss....ssrtlakiiiijgiijdbdgiciiggdabigdibcjijjijgcbbcciiijjdbagjjjdcjjqtrr...............................',
    '...........sssqmoomortrrrrs...ssrtlakjijjjjgjgjjcdfgccicccigcijddijjdbijjcdbcjjccddgjdccjjdkaqtrr...............................',
    '...........stttsomolnqtrrrrrs.srrtlakjcidjgjcgggjigcbchiihdjichcbbijghidiihddiijcbhbgchhcdbkaqtrr...............................',
    '...........srrrtslmmllortrrrrsrtttlakcihcicgiifdbcjjggdjiciggijibcgdidijcdgiiddgdbiihhggihckaqtrrs..............................',
    '............strtrmmmnomoqrttrrtrttlakaabijjccggdjicigjjhhcghjjjdibdbbbjjihjdcjbbhjcbbidiiibkaqtrrs..............................',
    '.............qrrqmoooooomoqrtttrrrkakabjiigdjcddiigjgdidfdicchbdjjjidcficcgjgicdiddidhdddgbkaqtrrs..............................',
    '.............loomooooooooomoqsrrrrkjkcijddgjdddjjjidccciiicacdiidggddhidjgccigfibcjibcijggckaotrrs..............................',
    '.............lnmoooooooooooommrrrrkjkbdgjjgfjgigiihijjdbbbdcdjcgdhhihdijccjggdcdigghbcjicdckaotrrs..............................',
    '.............omooononnnnoooooosrrrkjkdfjijgicdgjddbdjgddciiiiggdijdddjddccdiigjjjchciijjidakaotrrs..............................',
    '............srqnmonnnnnooooooosrrrkjkddjjggdiggibdgiddjddidbdiciddddbacdgccijiihiddbicddigakaotrrs..............................',
    '...........srttsommooooooooooosrrrkjkcjidijjdcicjjjidcdiicbbbciidcbciiicgjjccdddgiciidiigdckaotrrs..............................',
    '...........srrrrrqommooooooooosrrrkjkbcidcjjcdicjjjibddiigcbbciiijgciiddbhhcbdidgihidiiigdckaotrrs..............................',
    '............srrrrtrqommmoooooosrrrkjkddiijigiijiijddjidddiddddiddddibdcbdijdbciddidiccjjcdckaotrrs..............................',
    '.............srttttttsqomlllmmstrrkckdijjccdjgcbccdjcddidbcgcgcccgbdhhjjcddiijiidijjgcjijcckaqtrrs..............................',
    '...............srrtrrttrsqqqqortttlakiicdddbhiidjdcdddijjjdbbigdiidibbdjiiigcddgjddiicccidbkaqtrrs..............................',
    '.................srrrrrrttttttttttlakacbbhdcdddiiiidijjjccciiiihbhabidccijidgjcdigcibcddggakaqtrr...............................',
    '...................ssrrrtrrrrrrrrtlakacacdiiijidiidbcgiggjdcccddibhiiiijjccbbiciiiicdiiicbdkaqtrr...............................',
    '......................ssrrrrrrrrrtlakbcijjjgjidjkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkibihcbiijidkcqtrr...............................',
    '..........................sssssrrtoakjjjjjjcaajaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacjcbgciidjgdkqtrs...............................',
    '..............................srrtoakkjjdbbaajakooooooooooooooooooooooooooooooookcjdijccabjakstrs...............................',
    '...............................rrtqakicccabakjksttttttttttttttttttttttttttttttttqkkjiiccaakakrtrr...............................',
    '...............................rrtqakjaaacckjkqtrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrtqakjcccabkalttrs...............................',
    '...............................srtskkkdijckkkqtrtrrrrrrrrrrrrrrrrrrrrrrrrrrrrrttrtoakjbcaakaltrrs...............................',
    '...............................srrrkjkkkjkakqtrttssssssssssssssssssssssssssssssrrrtoakkijjkaotrrs...............................',
    '...............................srrtlckkkjalstrtts..............................rrrrtqkakkkkaqtrs................................',
    '...............................srrtqaaaakortrrrs................................rrrrtsljaaalrrrs................................',
    '................................srrtqllostrrrrs..................................srrrttqollstrts................................',
    '................................srrrtttttrrrss....................................srtrrtttttrrs.................................',
    '.................................strrrrrrtrs.......................................srrtrrrrrtrs.................................',
    '..................................srrrrrrss..........................................ssrrrrrss..................................',
    '...................................sssss................................................srss....................................',
  ],
  palette: {
    'E': 0xFF181818,
    'a': 0xFFFFFFFF,
    'b': 0xFFFFFEFE,
    'c': 0xFFFEFEFE,
    'd': 0xFFFEFEFD,
    'f': 0xFFFEFEFC,
    'g': 0xFFFDFEFD,
    'h': 0xFFFFFDFE,
    'i': 0xFFFEFDFD,
    'j': 0xFFFDFDFD,
    'k': 0xFFFBFAFA,
    'l': 0xFFDCC6AF,
    'm': 0xFFD7BC9F,
    'n': 0xFFD6BB9E,
    'o': 0xFFD4B99C,
    'q': 0xFF7A7782,
    'r': 0xFF603A2C,
    's': 0xFF6C303B,
    't': 0xFF542F21,
  },
);
